import FlapjackRiscvCheck.Decode.Basic
import FlapjackRiscvCheck.Decode.Encoding
import FlapjackRiscvCheck.Decode.Imm

/-! GENERATED by scripts/gen-decode-proofs.py. Sail decodes the L3 encodings of the
tier-1 Control instructions to the Sail ASTs `toSail` assigns them. -/

namespace FlapjackRiscvCheck

open LeanRV64D LeanRV64D.Functions Flapjack.RiscV.L3

set_option maxRecDepth 100000

theorem dec_jal {t} (h : DecodeInv t) (rd : BitVec 5) (imm : BitVec 20)  :
    runSail (encdec_backwards (Encode (.Branch (.JAL (rd, imm))))) t = some (.JAL (imm ++ 0#1, .Regidx rd), t) := by
  obtain ⟨tail, htail⟩ := encdec_backwards_prefix
  rw [htail]
  have hw := enc_jal rd imm
  generalize Encode _ = w at hw ⊢
  have := rd.isLt; have := imm.isLt
  have := (imm.extractLsb 19 19).isLt; have := (imm.extractLsb 9 0).isLt; have := (imm.extractLsb 10 10).isLt; have := (imm.extractLsb 18 11).isLt
  have f0 : Sail.BitVec.extractLsb w 6 0 = 111#7 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f1 : Sail.BitVec.extractLsb w 11 7 = rd :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f2 : Sail.BitVec.extractLsb w 19 12 = imm.extractLsb 18 11 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f3 : Sail.BitVec.extractLsb w 20 20 = imm.extractLsb 10 10 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f4 : Sail.BitVec.extractLsb w 30 21 = imm.extractLsb 9 0 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f5 : Sail.BitVec.extractLsb w 31 31 = imm.extractLsb 19 19 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  unfold decodePrefix
  unfold decodeBlock1
  try guard_simp hw [f0, f1, f2, f3, f4, f5]
  unfold decodeBlock2
  try guard_simp hw [f0, f1, f2, f3, f4, f5]
  unfold decodeBlock3
  simp only [runSail_bind_of_eq (runSail_currentlyEnabled_pause t)]
  try guard_simp hw [f0, f1, f2, f3, f4, f5]
  simp only [runSail_bind_of_eq (runSail_currentlyEnabled_zicfilp h)]
  try guard_simp hw [f0, f1, f2, f3, f4, f5]
  unfold decodeBlock4
  try guard_simp hw [f0, f1, f2, f3, f4, f5]
  decode_finish
  all_goals first | exact imm_S _ | (rw [imm_B]) | (rw [imm_J]) | rfl

theorem dec_jalr {t} (h : DecodeInv t) (rd rs1 : BitVec 5) (imm : BitVec 12)  :
    runSail (encdec_backwards (Encode (.Branch (.JALR (rd, rs1, imm))))) t = some (.JALR (imm, .Regidx rs1, .Regidx rd), t) := by
  obtain ⟨tail, htail⟩ := encdec_backwards_prefix
  rw [htail]
  have hw := enc_jalr rd rs1 imm
  generalize Encode _ = w at hw ⊢
  have := rd.isLt; have := rs1.isLt; have := imm.isLt
  have f0 : Sail.BitVec.extractLsb w 6 0 = 103#7 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f1 : Sail.BitVec.extractLsb w 11 7 = rd :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f2 : Sail.BitVec.extractLsb w 12 12 = 0#1 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f3 : Sail.BitVec.extractLsb w 13 12 = 0#2 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f4 : Sail.BitVec.extractLsb w 14 12 = 0#3 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f5 : Sail.BitVec.extractLsb w 14 13 = 0#2 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f6 : Sail.BitVec.extractLsb w 14 14 = 0#1 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f7 : Sail.BitVec.extractLsb w 19 15 = rs1 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f8 : Sail.BitVec.extractLsb w 31 20 = imm :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  unfold decodePrefix
  unfold decodeBlock1
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8]
  unfold decodeBlock2
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8]
  unfold decodeBlock3
  simp only [runSail_bind_of_eq (runSail_currentlyEnabled_pause t)]
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8]
  simp only [runSail_bind_of_eq (runSail_currentlyEnabled_zicfilp h)]
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8]
  unfold decodeBlock4
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8]
  unfold decodeBlock5
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8]
  decode_finish
  all_goals first | exact imm_S _ | (rw [imm_B]) | (rw [imm_J]) | rfl

theorem dec_beq {t} (h : DecodeInv t) (rs1 rs2 : BitVec 5) (offs : BitVec 12)  :
    runSail (encdec_backwards (Encode (.Branch (.BEQ (rs1, rs2, offs))))) t = some (.BTYPE (offs ++ 0#1, .Regidx rs2, .Regidx rs1, .BEQ), t) := by
  obtain ⟨tail, htail⟩ := encdec_backwards_prefix
  rw [htail]
  have hw := enc_beq rs1 rs2 offs
  generalize Encode _ = w at hw ⊢
  have := rs1.isLt; have := rs2.isLt; have := offs.isLt
  have := (offs.extractLsb 11 11).isLt; have := (offs.extractLsb 9 4).isLt; have := (offs.extractLsb 3 0).isLt; have := (offs.extractLsb 10 10).isLt
  have f0 : Sail.BitVec.extractLsb w 6 0 = 99#7 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f1 : Sail.BitVec.extractLsb w 7 7 = offs.extractLsb 10 10 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f2 : Sail.BitVec.extractLsb w 11 8 = offs.extractLsb 3 0 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f3 : Sail.BitVec.extractLsb w 12 12 = 0#1 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f4 : Sail.BitVec.extractLsb w 13 12 = 0#2 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f5 : Sail.BitVec.extractLsb w 14 12 = 0#3 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f6 : Sail.BitVec.extractLsb w 14 13 = 0#2 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f7 : Sail.BitVec.extractLsb w 14 14 = 0#1 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f8 : Sail.BitVec.extractLsb w 19 15 = rs1 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f9 : Sail.BitVec.extractLsb w 24 20 = rs2 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f10 : Sail.BitVec.extractLsb w 30 25 = offs.extractLsb 9 4 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f11 : Sail.BitVec.extractLsb w 31 31 = offs.extractLsb 11 11 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  unfold decodePrefix
  unfold decodeBlock1
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11]
  unfold decodeBlock2
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11]
  unfold decodeBlock3
  simp only [runSail_bind_of_eq (runSail_currentlyEnabled_pause t)]
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11]
  simp only [runSail_bind_of_eq (runSail_currentlyEnabled_zicfilp h)]
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11]
  unfold decodeBlock4
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11]
  unfold decodeBlock5
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11]
  unfold decodeBlock6
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11]
  decode_finish
  all_goals first | exact imm_S _ | (rw [imm_B]) | (rw [imm_J]) | rfl

theorem dec_bne {t} (h : DecodeInv t) (rs1 rs2 : BitVec 5) (offs : BitVec 12)  :
    runSail (encdec_backwards (Encode (.Branch (.BNE (rs1, rs2, offs))))) t = some (.BTYPE (offs ++ 0#1, .Regidx rs2, .Regidx rs1, .BNE), t) := by
  obtain ⟨tail, htail⟩ := encdec_backwards_prefix
  rw [htail]
  have hw := enc_bne rs1 rs2 offs
  generalize Encode _ = w at hw ⊢
  have := rs1.isLt; have := rs2.isLt; have := offs.isLt
  have := (offs.extractLsb 11 11).isLt; have := (offs.extractLsb 9 4).isLt; have := (offs.extractLsb 3 0).isLt; have := (offs.extractLsb 10 10).isLt
  have f0 : Sail.BitVec.extractLsb w 6 0 = 99#7 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f1 : Sail.BitVec.extractLsb w 7 7 = offs.extractLsb 10 10 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f2 : Sail.BitVec.extractLsb w 11 8 = offs.extractLsb 3 0 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f3 : Sail.BitVec.extractLsb w 12 12 = 1#1 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f4 : Sail.BitVec.extractLsb w 13 12 = 1#2 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f5 : Sail.BitVec.extractLsb w 14 12 = 1#3 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f6 : Sail.BitVec.extractLsb w 14 13 = 0#2 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f7 : Sail.BitVec.extractLsb w 14 14 = 0#1 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f8 : Sail.BitVec.extractLsb w 19 15 = rs1 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f9 : Sail.BitVec.extractLsb w 24 20 = rs2 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f10 : Sail.BitVec.extractLsb w 30 25 = offs.extractLsb 9 4 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f11 : Sail.BitVec.extractLsb w 31 31 = offs.extractLsb 11 11 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  unfold decodePrefix
  unfold decodeBlock1
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11]
  unfold decodeBlock2
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11]
  unfold decodeBlock3
  simp only [runSail_bind_of_eq (runSail_currentlyEnabled_pause t)]
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11]
  simp only [runSail_bind_of_eq (runSail_currentlyEnabled_zicfilp h)]
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11]
  unfold decodeBlock4
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11]
  unfold decodeBlock5
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11]
  unfold decodeBlock6
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11]
  decode_finish
  all_goals first | exact imm_S _ | (rw [imm_B]) | (rw [imm_J]) | rfl

theorem dec_blt {t} (h : DecodeInv t) (rs1 rs2 : BitVec 5) (offs : BitVec 12)  :
    runSail (encdec_backwards (Encode (.Branch (.BLT (rs1, rs2, offs))))) t = some (.BTYPE (offs ++ 0#1, .Regidx rs2, .Regidx rs1, .BLT), t) := by
  obtain ⟨tail, htail⟩ := encdec_backwards_prefix
  rw [htail]
  have hw := enc_blt rs1 rs2 offs
  generalize Encode _ = w at hw ⊢
  have := rs1.isLt; have := rs2.isLt; have := offs.isLt
  have := (offs.extractLsb 11 11).isLt; have := (offs.extractLsb 9 4).isLt; have := (offs.extractLsb 3 0).isLt; have := (offs.extractLsb 10 10).isLt
  have f0 : Sail.BitVec.extractLsb w 6 0 = 99#7 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f1 : Sail.BitVec.extractLsb w 7 7 = offs.extractLsb 10 10 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f2 : Sail.BitVec.extractLsb w 11 8 = offs.extractLsb 3 0 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f3 : Sail.BitVec.extractLsb w 12 12 = 0#1 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f4 : Sail.BitVec.extractLsb w 13 12 = 0#2 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f5 : Sail.BitVec.extractLsb w 14 12 = 4#3 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f6 : Sail.BitVec.extractLsb w 14 13 = 2#2 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f7 : Sail.BitVec.extractLsb w 14 14 = 1#1 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f8 : Sail.BitVec.extractLsb w 19 15 = rs1 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f9 : Sail.BitVec.extractLsb w 24 20 = rs2 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f10 : Sail.BitVec.extractLsb w 30 25 = offs.extractLsb 9 4 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f11 : Sail.BitVec.extractLsb w 31 31 = offs.extractLsb 11 11 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  unfold decodePrefix
  unfold decodeBlock1
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11]
  unfold decodeBlock2
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11]
  unfold decodeBlock3
  simp only [runSail_bind_of_eq (runSail_currentlyEnabled_pause t)]
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11]
  simp only [runSail_bind_of_eq (runSail_currentlyEnabled_zicfilp h)]
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11]
  unfold decodeBlock4
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11]
  unfold decodeBlock5
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11]
  unfold decodeBlock6
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11]
  decode_finish
  all_goals first | exact imm_S _ | (rw [imm_B]) | (rw [imm_J]) | rfl

theorem dec_bge {t} (h : DecodeInv t) (rs1 rs2 : BitVec 5) (offs : BitVec 12)  :
    runSail (encdec_backwards (Encode (.Branch (.BGE (rs1, rs2, offs))))) t = some (.BTYPE (offs ++ 0#1, .Regidx rs2, .Regidx rs1, .BGE), t) := by
  obtain ⟨tail, htail⟩ := encdec_backwards_prefix
  rw [htail]
  have hw := enc_bge rs1 rs2 offs
  generalize Encode _ = w at hw ⊢
  have := rs1.isLt; have := rs2.isLt; have := offs.isLt
  have := (offs.extractLsb 11 11).isLt; have := (offs.extractLsb 9 4).isLt; have := (offs.extractLsb 3 0).isLt; have := (offs.extractLsb 10 10).isLt
  have f0 : Sail.BitVec.extractLsb w 6 0 = 99#7 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f1 : Sail.BitVec.extractLsb w 7 7 = offs.extractLsb 10 10 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f2 : Sail.BitVec.extractLsb w 11 8 = offs.extractLsb 3 0 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f3 : Sail.BitVec.extractLsb w 12 12 = 1#1 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f4 : Sail.BitVec.extractLsb w 13 12 = 1#2 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f5 : Sail.BitVec.extractLsb w 14 12 = 5#3 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f6 : Sail.BitVec.extractLsb w 14 13 = 2#2 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f7 : Sail.BitVec.extractLsb w 14 14 = 1#1 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f8 : Sail.BitVec.extractLsb w 19 15 = rs1 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f9 : Sail.BitVec.extractLsb w 24 20 = rs2 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f10 : Sail.BitVec.extractLsb w 30 25 = offs.extractLsb 9 4 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f11 : Sail.BitVec.extractLsb w 31 31 = offs.extractLsb 11 11 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  unfold decodePrefix
  unfold decodeBlock1
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11]
  unfold decodeBlock2
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11]
  unfold decodeBlock3
  simp only [runSail_bind_of_eq (runSail_currentlyEnabled_pause t)]
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11]
  simp only [runSail_bind_of_eq (runSail_currentlyEnabled_zicfilp h)]
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11]
  unfold decodeBlock4
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11]
  unfold decodeBlock5
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11]
  unfold decodeBlock6
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11]
  decode_finish
  all_goals first | exact imm_S _ | (rw [imm_B]) | (rw [imm_J]) | rfl

theorem dec_bltu {t} (h : DecodeInv t) (rs1 rs2 : BitVec 5) (offs : BitVec 12)  :
    runSail (encdec_backwards (Encode (.Branch (.BLTU (rs1, rs2, offs))))) t = some (.BTYPE (offs ++ 0#1, .Regidx rs2, .Regidx rs1, .BLTU), t) := by
  obtain ⟨tail, htail⟩ := encdec_backwards_prefix
  rw [htail]
  have hw := enc_bltu rs1 rs2 offs
  generalize Encode _ = w at hw ⊢
  have := rs1.isLt; have := rs2.isLt; have := offs.isLt
  have := (offs.extractLsb 11 11).isLt; have := (offs.extractLsb 9 4).isLt; have := (offs.extractLsb 3 0).isLt; have := (offs.extractLsb 10 10).isLt
  have f0 : Sail.BitVec.extractLsb w 6 0 = 99#7 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f1 : Sail.BitVec.extractLsb w 7 7 = offs.extractLsb 10 10 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f2 : Sail.BitVec.extractLsb w 11 8 = offs.extractLsb 3 0 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f3 : Sail.BitVec.extractLsb w 12 12 = 0#1 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f4 : Sail.BitVec.extractLsb w 13 12 = 2#2 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f5 : Sail.BitVec.extractLsb w 14 12 = 6#3 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f6 : Sail.BitVec.extractLsb w 14 13 = 3#2 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f7 : Sail.BitVec.extractLsb w 14 14 = 1#1 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f8 : Sail.BitVec.extractLsb w 19 15 = rs1 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f9 : Sail.BitVec.extractLsb w 24 20 = rs2 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f10 : Sail.BitVec.extractLsb w 30 25 = offs.extractLsb 9 4 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f11 : Sail.BitVec.extractLsb w 31 31 = offs.extractLsb 11 11 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  unfold decodePrefix
  unfold decodeBlock1
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11]
  unfold decodeBlock2
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11]
  unfold decodeBlock3
  simp only [runSail_bind_of_eq (runSail_currentlyEnabled_pause t)]
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11]
  simp only [runSail_bind_of_eq (runSail_currentlyEnabled_zicfilp h)]
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11]
  unfold decodeBlock4
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11]
  unfold decodeBlock5
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11]
  unfold decodeBlock6
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11]
  decode_finish
  all_goals first | exact imm_S _ | (rw [imm_B]) | (rw [imm_J]) | rfl

theorem dec_bgeu {t} (h : DecodeInv t) (rs1 rs2 : BitVec 5) (offs : BitVec 12)  :
    runSail (encdec_backwards (Encode (.Branch (.BGEU (rs1, rs2, offs))))) t = some (.BTYPE (offs ++ 0#1, .Regidx rs2, .Regidx rs1, .BGEU), t) := by
  obtain ⟨tail, htail⟩ := encdec_backwards_prefix
  rw [htail]
  have hw := enc_bgeu rs1 rs2 offs
  generalize Encode _ = w at hw ⊢
  have := rs1.isLt; have := rs2.isLt; have := offs.isLt
  have := (offs.extractLsb 11 11).isLt; have := (offs.extractLsb 9 4).isLt; have := (offs.extractLsb 3 0).isLt; have := (offs.extractLsb 10 10).isLt
  have f0 : Sail.BitVec.extractLsb w 6 0 = 99#7 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f1 : Sail.BitVec.extractLsb w 7 7 = offs.extractLsb 10 10 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f2 : Sail.BitVec.extractLsb w 11 8 = offs.extractLsb 3 0 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f3 : Sail.BitVec.extractLsb w 12 12 = 1#1 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f4 : Sail.BitVec.extractLsb w 13 12 = 3#2 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f5 : Sail.BitVec.extractLsb w 14 12 = 7#3 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f6 : Sail.BitVec.extractLsb w 14 13 = 3#2 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f7 : Sail.BitVec.extractLsb w 14 14 = 1#1 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f8 : Sail.BitVec.extractLsb w 19 15 = rs1 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f9 : Sail.BitVec.extractLsb w 24 20 = rs2 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f10 : Sail.BitVec.extractLsb w 30 25 = offs.extractLsb 9 4 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f11 : Sail.BitVec.extractLsb w 31 31 = offs.extractLsb 11 11 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  unfold decodePrefix
  unfold decodeBlock1
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11]
  unfold decodeBlock2
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11]
  unfold decodeBlock3
  simp only [runSail_bind_of_eq (runSail_currentlyEnabled_pause t)]
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11]
  simp only [runSail_bind_of_eq (runSail_currentlyEnabled_zicfilp h)]
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11]
  unfold decodeBlock4
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11]
  unfold decodeBlock5
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11]
  unfold decodeBlock6
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11]
  decode_finish
  all_goals first | exact imm_S _ | (rw [imm_B]) | (rw [imm_J]) | rfl

end FlapjackRiscvCheck
