import FlapjackRiscvCheck.Decode.RType
import FlapjackRiscvCheck.Decode.MulDiv
import FlapjackRiscvCheck.Decode.IType
import FlapjackRiscvCheck.Decode.Mem
import FlapjackRiscvCheck.Decode.Control
import FlapjackRiscvCheck.Exec.Dispatch
import Flapjack.RiscV.CorrectnessEncoding.DecodeBinop
import Flapjack.RiscV.CorrectnessEncoding.DecodeShift
import Flapjack.RiscV.CorrectnessEncoding.DecodeBranches
import Flapjack.RiscV.CorrectnessEncoding.DecodeControl
import Flapjack.RiscV.CorrectnessEncoding.DecodeLongMul
import Flapjack.RiscV.CorrectnessEncoding.DecodeDiv
import Flapjack.RiscV.CorrectnessEncoding.DecodeMemory
import Flapjack.RiscV.CorrectnessEncoding.DecodeConst
import Flapjack.RiscV.CorrectnessEncoding.DecodeSltu
import Flapjack.RiscV.CorrectnessEncoding.DecodeAddi
import Flapjack.RiscV.CorrectnessEncoding.DecodeUpperImmediates

/-! GENERATED by scripts/gen-decode-dispatch.py.

For every tier-1 instruction `i` (`toSail i = some si`), both models decode the
L3 encoding `Encode i`: L3 to `i` (Flapjack's `decode_encode_*`), Sail to `si`.
`HintFree i` excludes the two encodings Sail reads as hints: `ADD x0, …`
(Zihintntl `NTL`) and `ORI x0, …` (Zicbop prefetch). -/

namespace FlapjackRiscvCheck

open LeanRV64D LeanRV64D.Functions Flapjack.RiscV.L3

/-- Not one of the encodings Sail decodes as a hint instead. -/
def HintFree : Flapjack.RiscV.L3.instruction → Prop
  | .ArithR (.ADD (rd, _, _)) => rd ≠ 0
  | .ArithI (.ORI (rd, _, _)) => rd ≠ 0
  | _ => True

theorem sail_decode_sim {t : SailState} (h : DecodeInv t) (i : Flapjack.RiscV.L3.instruction)
    (si : LeanRV64D.instruction) (hi : toSail i = some si) (hh : HintFree i) :
    runSail (ext_decode (Encode i)) t = some (si, t) := by
  unfold ext_decode
  cases i with
  | ArithR a =>
    cases a with
    | ADD x =>
      obtain ⟨rd, rs1, rs2⟩ := x
      simp only [toSail, Option.some.injEq] at hi; subst hi
      exact dec_add h rd rs1 rs2 hh
    | SUB x =>
      obtain ⟨rd, rs1, rs2⟩ := x
      simp only [toSail, Option.some.injEq] at hi; subst hi
      exact dec_sub h rd rs1 rs2
    | AND x =>
      obtain ⟨rd, rs1, rs2⟩ := x
      simp only [toSail, Option.some.injEq] at hi; subst hi
      exact dec_and h rd rs1 rs2
    | OR x =>
      obtain ⟨rd, rs1, rs2⟩ := x
      simp only [toSail, Option.some.injEq] at hi; subst hi
      exact dec_or h rd rs1 rs2
    | XOR x =>
      obtain ⟨rd, rs1, rs2⟩ := x
      simp only [toSail, Option.some.injEq] at hi; subst hi
      exact dec_xor h rd rs1 rs2
    | SLTU x =>
      obtain ⟨rd, rs1, rs2⟩ := x
      simp only [toSail, Option.some.injEq] at hi; subst hi
      exact dec_sltu h rd rs1 rs2
    | _ => simp [toSail] at hi
  | Shift a =>
    cases a with
    | SLL x =>
      obtain ⟨rd, rs1, rs2⟩ := x
      simp only [toSail, Option.some.injEq] at hi; subst hi
      exact dec_sll h rd rs1 rs2
    | SRL x =>
      obtain ⟨rd, rs1, rs2⟩ := x
      simp only [toSail, Option.some.injEq] at hi; subst hi
      exact dec_srl h rd rs1 rs2
    | SRA x =>
      obtain ⟨rd, rs1, rs2⟩ := x
      simp only [toSail, Option.some.injEq] at hi; subst hi
      exact dec_sra h rd rs1 rs2
    | SLLI x =>
      obtain ⟨rd, rs1, sh⟩ := x
      simp only [toSail, Option.some.injEq] at hi; subst hi
      exact dec_slli h rd rs1 sh
    | SRLI x =>
      obtain ⟨rd, rs1, sh⟩ := x
      simp only [toSail, Option.some.injEq] at hi; subst hi
      exact dec_srli h rd rs1 sh
    | SRAI x =>
      obtain ⟨rd, rs1, sh⟩ := x
      simp only [toSail, Option.some.injEq] at hi; subst hi
      exact dec_srai h rd rs1 sh
    | _ => simp [toSail] at hi
  | MulDiv a =>
    cases a with
    | MUL x =>
      obtain ⟨rd, rs1, rs2⟩ := x
      simp only [toSail, Option.some.injEq] at hi; subst hi
      exact dec_mul h rd rs1 rs2
    | MULHU x =>
      obtain ⟨rd, rs1, rs2⟩ := x
      simp only [toSail, Option.some.injEq] at hi; subst hi
      exact dec_mulhu h rd rs1 rs2
    | DIV x =>
      obtain ⟨rd, rs1, rs2⟩ := x
      simp only [toSail, Option.some.injEq] at hi; subst hi
      exact dec_div h rd rs1 rs2
    | _ => simp [toSail] at hi
  | ArithI a =>
    cases a with
    | ADDI x =>
      obtain ⟨rd, rs1, imm⟩ := x
      simp only [toSail, Option.some.injEq] at hi; subst hi
      exact dec_addi h rd rs1 imm
    | ANDI x =>
      obtain ⟨rd, rs1, imm⟩ := x
      simp only [toSail, Option.some.injEq] at hi; subst hi
      exact dec_andi h rd rs1 imm
    | ORI x =>
      obtain ⟨rd, rs1, imm⟩ := x
      simp only [toSail, Option.some.injEq] at hi; subst hi
      exact dec_ori h rd rs1 imm hh
    | XORI x =>
      obtain ⟨rd, rs1, imm⟩ := x
      simp only [toSail, Option.some.injEq] at hi; subst hi
      exact dec_xori h rd rs1 imm
    | LUI x =>
      obtain ⟨rd, imm⟩ := x
      simp only [toSail, Option.some.injEq] at hi; subst hi
      exact dec_lui h rd imm
    | AUIPC x =>
      obtain ⟨rd, imm⟩ := x
      simp only [toSail, Option.some.injEq] at hi; subst hi
      exact dec_auipc h rd imm
    | _ => simp [toSail] at hi
  | Load a =>
    cases a with
    | LD x =>
      obtain ⟨rd, rs1, imm⟩ := x
      simp only [toSail, Option.some.injEq] at hi; subst hi
      exact dec_ld h rd rs1 imm
    | LWU x =>
      obtain ⟨rd, rs1, imm⟩ := x
      simp only [toSail, Option.some.injEq] at hi; subst hi
      exact dec_lwu h rd rs1 imm
    | LHU x =>
      obtain ⟨rd, rs1, imm⟩ := x
      simp only [toSail, Option.some.injEq] at hi; subst hi
      exact dec_lhu h rd rs1 imm
    | LBU x =>
      obtain ⟨rd, rs1, imm⟩ := x
      simp only [toSail, Option.some.injEq] at hi; subst hi
      exact dec_lbu h rd rs1 imm
    | _ => simp [toSail] at hi
  | Store a =>
    cases a with
    | SD x =>
      obtain ⟨rs1, rs2, imm⟩ := x
      simp only [toSail, Option.some.injEq] at hi; subst hi
      exact dec_sd h rs1 rs2 imm
    | SW x =>
      obtain ⟨rs1, rs2, imm⟩ := x
      simp only [toSail, Option.some.injEq] at hi; subst hi
      exact dec_sw h rs1 rs2 imm
    | SH x =>
      obtain ⟨rs1, rs2, imm⟩ := x
      simp only [toSail, Option.some.injEq] at hi; subst hi
      exact dec_sh h rs1 rs2 imm
    | SB x =>
      obtain ⟨rs1, rs2, imm⟩ := x
      simp only [toSail, Option.some.injEq] at hi; subst hi
      exact dec_sb h rs1 rs2 imm
  | Branch a =>
    cases a with
    | JAL x =>
      obtain ⟨rd, imm⟩ := x
      simp only [toSail, Option.some.injEq] at hi; subst hi
      exact dec_jal h rd imm
    | JALR x =>
      obtain ⟨rd, rs1, imm⟩ := x
      simp only [toSail, Option.some.injEq] at hi; subst hi
      exact dec_jalr h rd rs1 imm
    | BEQ x =>
      obtain ⟨rs1, rs2, offs⟩ := x
      simp only [toSail, Option.some.injEq] at hi; subst hi
      exact dec_beq h rs1 rs2 offs
    | BNE x =>
      obtain ⟨rs1, rs2, offs⟩ := x
      simp only [toSail, Option.some.injEq] at hi; subst hi
      exact dec_bne h rs1 rs2 offs
    | BLT x =>
      obtain ⟨rs1, rs2, offs⟩ := x
      simp only [toSail, Option.some.injEq] at hi; subst hi
      exact dec_blt h rs1 rs2 offs
    | BGE x =>
      obtain ⟨rs1, rs2, offs⟩ := x
      simp only [toSail, Option.some.injEq] at hi; subst hi
      exact dec_bge h rs1 rs2 offs
    | BLTU x =>
      obtain ⟨rs1, rs2, offs⟩ := x
      simp only [toSail, Option.some.injEq] at hi; subst hi
      exact dec_bltu h rs1 rs2 offs
    | BGEU x =>
      obtain ⟨rs1, rs2, offs⟩ := x
      simp only [toSail, Option.some.injEq] at hi; subst hi
      exact dec_bgeu h rs1 rs2 offs
  | _ => simp [toSail] at hi

theorem l3_decode_sim (i : Flapjack.RiscV.L3.instruction) (si : LeanRV64D.instruction)
    (hi : toSail i = some si) : Step.DecodeAny (.Word (Encode i)) = i := by
  cases i with
  | ArithR a =>
    cases a with
    | ADD x =>
      obtain ⟨rd, rs1, rs2⟩ := x
      exact decode_encode_add rd rs1 rs2
    | SUB x =>
      obtain ⟨rd, rs1, rs2⟩ := x
      exact decode_encode_sub rd rs1 rs2
    | AND x =>
      obtain ⟨rd, rs1, rs2⟩ := x
      exact decode_encode_and rd rs1 rs2
    | OR x =>
      obtain ⟨rd, rs1, rs2⟩ := x
      exact decode_encode_or rd rs1 rs2
    | XOR x =>
      obtain ⟨rd, rs1, rs2⟩ := x
      exact decode_encode_xor rd rs1 rs2
    | SLTU x =>
      obtain ⟨rd, rs1, rs2⟩ := x
      exact decode_encode_sltu rd rs1 rs2
    | _ => simp [toSail] at hi
  | Shift a =>
    cases a with
    | SLL x =>
      obtain ⟨rd, rs1, rs2⟩ := x
      exact decode_encode_sll rd rs1 rs2
    | SRL x =>
      obtain ⟨rd, rs1, rs2⟩ := x
      exact decode_encode_srl rd rs1 rs2
    | SRA x =>
      obtain ⟨rd, rs1, rs2⟩ := x
      exact decode_encode_sra rd rs1 rs2
    | SLLI x =>
      obtain ⟨rd, rs1, sh⟩ := x
      exact decode_encode_slli rd rs1 sh
    | SRLI x =>
      obtain ⟨rd, rs1, sh⟩ := x
      exact decode_encode_srli rd rs1 sh
    | SRAI x =>
      obtain ⟨rd, rs1, sh⟩ := x
      exact decode_encode_srai rd rs1 sh
    | _ => simp [toSail] at hi
  | MulDiv a =>
    cases a with
    | MUL x =>
      obtain ⟨rd, rs1, rs2⟩ := x
      exact decode_encode_mul rd rs1 rs2
    | MULHU x =>
      obtain ⟨rd, rs1, rs2⟩ := x
      exact decode_encode_mulhu rd rs1 rs2
    | DIV x =>
      obtain ⟨rd, rs1, rs2⟩ := x
      exact decode_encode_div rd rs1 rs2
    | _ => simp [toSail] at hi
  | ArithI a =>
    cases a with
    | ADDI x =>
      obtain ⟨rd, rs1, imm⟩ := x
      exact decode_encode_addi rd rs1 imm
    | ANDI x =>
      obtain ⟨rd, rs1, imm⟩ := x
      exact decode_encode_andi rd rs1 imm
    | ORI x =>
      obtain ⟨rd, rs1, imm⟩ := x
      exact decode_encode_ori rd rs1 imm
    | XORI x =>
      obtain ⟨rd, rs1, imm⟩ := x
      exact decode_encode_xori rd rs1 imm
    | LUI x =>
      obtain ⟨rd, imm⟩ := x
      exact decode_encode_lui rd imm
    | AUIPC x =>
      obtain ⟨rd, imm⟩ := x
      exact decode_encode_auipc rd imm
    | _ => simp [toSail] at hi
  | Load a =>
    cases a with
    | LD x =>
      obtain ⟨rd, rs1, imm⟩ := x
      exact decode_encode_ld rd rs1 imm
    | LWU x =>
      obtain ⟨rd, rs1, imm⟩ := x
      exact decode_encode_lwu rd rs1 imm
    | LHU x =>
      obtain ⟨rd, rs1, imm⟩ := x
      exact decode_encode_lhu rd rs1 imm
    | LBU x =>
      obtain ⟨rd, rs1, imm⟩ := x
      exact decode_encode_lbu rd rs1 imm
    | _ => simp [toSail] at hi
  | Store a =>
    cases a with
    | SD x =>
      obtain ⟨rs1, rs2, imm⟩ := x
      exact decode_encode_sd rs1 rs2 imm
    | SW x =>
      obtain ⟨rs1, rs2, imm⟩ := x
      exact decode_encode_sw rs1 rs2 imm
    | SH x =>
      obtain ⟨rs1, rs2, imm⟩ := x
      exact decode_encode_sh rs1 rs2 imm
    | SB x =>
      obtain ⟨rs1, rs2, imm⟩ := x
      exact decode_encode_sb rs1 rs2 imm
  | Branch a =>
    cases a with
    | JAL x =>
      obtain ⟨rd, imm⟩ := x
      exact decode_encode_jal rd imm
    | JALR x =>
      obtain ⟨rd, rs1, imm⟩ := x
      exact decode_encode_jalr rd rs1 imm
    | BEQ x =>
      obtain ⟨rs1, rs2, offs⟩ := x
      exact decode_encode_beq rs1 rs2 offs
    | BNE x =>
      obtain ⟨rs1, rs2, offs⟩ := x
      exact decode_encode_bne rs1 rs2 offs
    | BLT x =>
      obtain ⟨rs1, rs2, offs⟩ := x
      exact decode_encode_blt rs1 rs2 offs
    | BGE x =>
      obtain ⟨rs1, rs2, offs⟩ := x
      exact decode_encode_bge rs1 rs2 offs
    | BLTU x =>
      obtain ⟨rs1, rs2, offs⟩ := x
      exact decode_encode_bltu rs1 rs2 offs
    | BGEU x =>
      obtain ⟨rs1, rs2, offs⟩ := x
      exact decode_encode_bgeu rs1 rs2 offs
  | _ => simp [toSail] at hi

theorem encode_low_bits (i : Flapjack.RiscV.L3.instruction) (si : LeanRV64D.instruction)
    (hi : toSail i = some si) : (Encode i).toNat % 4 = 3 := by
  cases i with
  | ArithR a =>
    cases a with
    | ADD x =>
      obtain ⟨rd, rs1, rs2⟩ := x
      rw [enc_add rd rs1 rs2]
      omega
    | SUB x =>
      obtain ⟨rd, rs1, rs2⟩ := x
      rw [enc_sub rd rs1 rs2]
      omega
    | AND x =>
      obtain ⟨rd, rs1, rs2⟩ := x
      rw [enc_and rd rs1 rs2]
      omega
    | OR x =>
      obtain ⟨rd, rs1, rs2⟩ := x
      rw [enc_or rd rs1 rs2]
      omega
    | XOR x =>
      obtain ⟨rd, rs1, rs2⟩ := x
      rw [enc_xor rd rs1 rs2]
      omega
    | SLTU x =>
      obtain ⟨rd, rs1, rs2⟩ := x
      rw [enc_sltu rd rs1 rs2]
      omega
    | _ => simp [toSail] at hi
  | Shift a =>
    cases a with
    | SLL x =>
      obtain ⟨rd, rs1, rs2⟩ := x
      rw [enc_sll rd rs1 rs2]
      omega
    | SRL x =>
      obtain ⟨rd, rs1, rs2⟩ := x
      rw [enc_srl rd rs1 rs2]
      omega
    | SRA x =>
      obtain ⟨rd, rs1, rs2⟩ := x
      rw [enc_sra rd rs1 rs2]
      omega
    | SLLI x =>
      obtain ⟨rd, rs1, sh⟩ := x
      rw [enc_slli rd rs1 sh]
      omega
    | SRLI x =>
      obtain ⟨rd, rs1, sh⟩ := x
      rw [enc_srli rd rs1 sh]
      omega
    | SRAI x =>
      obtain ⟨rd, rs1, sh⟩ := x
      rw [enc_srai rd rs1 sh]
      omega
    | _ => simp [toSail] at hi
  | MulDiv a =>
    cases a with
    | MUL x =>
      obtain ⟨rd, rs1, rs2⟩ := x
      rw [enc_mul rd rs1 rs2]
      omega
    | MULHU x =>
      obtain ⟨rd, rs1, rs2⟩ := x
      rw [enc_mulhu rd rs1 rs2]
      omega
    | DIV x =>
      obtain ⟨rd, rs1, rs2⟩ := x
      rw [enc_div rd rs1 rs2]
      omega
    | _ => simp [toSail] at hi
  | ArithI a =>
    cases a with
    | ADDI x =>
      obtain ⟨rd, rs1, imm⟩ := x
      rw [enc_addi rd rs1 imm]
      omega
    | ANDI x =>
      obtain ⟨rd, rs1, imm⟩ := x
      rw [enc_andi rd rs1 imm]
      omega
    | ORI x =>
      obtain ⟨rd, rs1, imm⟩ := x
      rw [enc_ori rd rs1 imm]
      omega
    | XORI x =>
      obtain ⟨rd, rs1, imm⟩ := x
      rw [enc_xori rd rs1 imm]
      omega
    | LUI x =>
      obtain ⟨rd, imm⟩ := x
      rw [enc_lui rd imm]
      omega
    | AUIPC x =>
      obtain ⟨rd, imm⟩ := x
      rw [enc_auipc rd imm]
      omega
    | _ => simp [toSail] at hi
  | Load a =>
    cases a with
    | LD x =>
      obtain ⟨rd, rs1, imm⟩ := x
      rw [enc_ld rd rs1 imm]
      omega
    | LWU x =>
      obtain ⟨rd, rs1, imm⟩ := x
      rw [enc_lwu rd rs1 imm]
      omega
    | LHU x =>
      obtain ⟨rd, rs1, imm⟩ := x
      rw [enc_lhu rd rs1 imm]
      omega
    | LBU x =>
      obtain ⟨rd, rs1, imm⟩ := x
      rw [enc_lbu rd rs1 imm]
      omega
    | _ => simp [toSail] at hi
  | Store a =>
    cases a with
    | SD x =>
      obtain ⟨rs1, rs2, imm⟩ := x
      rw [enc_sd rs1 rs2 imm]
      omega
    | SW x =>
      obtain ⟨rs1, rs2, imm⟩ := x
      rw [enc_sw rs1 rs2 imm]
      omega
    | SH x =>
      obtain ⟨rs1, rs2, imm⟩ := x
      rw [enc_sh rs1 rs2 imm]
      omega
    | SB x =>
      obtain ⟨rs1, rs2, imm⟩ := x
      rw [enc_sb rs1 rs2 imm]
      omega
  | Branch a =>
    cases a with
    | JAL x =>
      obtain ⟨rd, imm⟩ := x
      rw [enc_jal rd imm]
      omega
    | JALR x =>
      obtain ⟨rd, rs1, imm⟩ := x
      rw [enc_jalr rd rs1 imm]
      omega
    | BEQ x =>
      obtain ⟨rs1, rs2, offs⟩ := x
      rw [enc_beq rs1 rs2 offs]
      omega
    | BNE x =>
      obtain ⟨rs1, rs2, offs⟩ := x
      rw [enc_bne rs1 rs2 offs]
      omega
    | BLT x =>
      obtain ⟨rs1, rs2, offs⟩ := x
      rw [enc_blt rs1 rs2 offs]
      omega
    | BGE x =>
      obtain ⟨rs1, rs2, offs⟩ := x
      rw [enc_bge rs1 rs2 offs]
      omega
    | BLTU x =>
      obtain ⟨rs1, rs2, offs⟩ := x
      rw [enc_bltu rs1 rs2 offs]
      omega
    | BGEU x =>
      obtain ⟨rs1, rs2, offs⟩ := x
      rw [enc_bgeu rs1 rs2 offs]
      omega
  | _ => simp [toSail] at hi

end FlapjackRiscvCheck
