import FlapjackRiscvCheck.Decode.Basic
import FlapjackRiscvCheck.Decode.Encoding
import FlapjackRiscvCheck.Decode.Imm

/-! GENERATED by scripts/gen-decode-proofs.py. Sail decodes the L3 encodings of the
tier-1 IType instructions to the Sail ASTs `toSail` assigns them. -/

namespace FlapjackRiscvCheck

open LeanRV64D LeanRV64D.Functions Flapjack.RiscV.L3

set_option maxRecDepth 100000

theorem dec_addi {t} (h : DecodeInv t) (rd rs1 : BitVec 5) (imm : BitVec 12)  :
    runSail (encdec_backwards (Encode (.ArithI (.ADDI (rd, rs1, imm))))) t = some (.ITYPE (imm, .Regidx rs1, .Regidx rd, .ADDI), t) := by
  obtain ⟨tail, htail⟩ := encdec_backwards_prefix
  rw [htail]
  have hw := enc_addi rd rs1 imm
  generalize Encode _ = w at hw ⊢
  have := rd.isLt; have := rs1.isLt; have := imm.isLt
  have f0 : Sail.BitVec.extractLsb w 6 0 = 19#7 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f1 : Sail.BitVec.extractLsb w 11 7 = rd :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f2 : Sail.BitVec.extractLsb w 12 12 = 0#1 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f3 : Sail.BitVec.extractLsb w 13 12 = 0#2 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f4 : Sail.BitVec.extractLsb w 14 12 = 0#3 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f5 : Sail.BitVec.extractLsb w 14 13 = 0#2 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f6 : Sail.BitVec.extractLsb w 14 14 = 0#1 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f7 : Sail.BitVec.extractLsb w 19 15 = rs1 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f8 : Sail.BitVec.extractLsb w 31 20 = imm :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  unfold decodePrefix
  unfold decodeBlock1
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8]
  unfold decodeBlock2
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8]
  unfold decodeBlock3
  simp only [runSail_bind_of_eq (runSail_currentlyEnabled_pause t)]
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8]
  simp only [runSail_bind_of_eq (runSail_currentlyEnabled_zicfilp h)]
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8]
  unfold decodeBlock4
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8]
  unfold decodeBlock5
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8]
  unfold decodeBlock6
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8]
  unfold decodeBlock7
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8]
  decode_finish

theorem dec_andi {t} (h : DecodeInv t) (rd rs1 : BitVec 5) (imm : BitVec 12)  :
    runSail (encdec_backwards (Encode (.ArithI (.ANDI (rd, rs1, imm))))) t = some (.ITYPE (imm, .Regidx rs1, .Regidx rd, .ANDI), t) := by
  obtain ⟨tail, htail⟩ := encdec_backwards_prefix
  rw [htail]
  have hw := enc_andi rd rs1 imm
  generalize Encode _ = w at hw ⊢
  have := rd.isLt; have := rs1.isLt; have := imm.isLt
  have f0 : Sail.BitVec.extractLsb w 6 0 = 19#7 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f1 : Sail.BitVec.extractLsb w 11 7 = rd :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f2 : Sail.BitVec.extractLsb w 12 12 = 1#1 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f3 : Sail.BitVec.extractLsb w 13 12 = 3#2 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f4 : Sail.BitVec.extractLsb w 14 12 = 7#3 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f5 : Sail.BitVec.extractLsb w 14 13 = 3#2 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f6 : Sail.BitVec.extractLsb w 14 14 = 1#1 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f7 : Sail.BitVec.extractLsb w 19 15 = rs1 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f8 : Sail.BitVec.extractLsb w 31 20 = imm :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  unfold decodePrefix
  unfold decodeBlock1
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8]
  unfold decodeBlock2
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8]
  unfold decodeBlock3
  simp only [runSail_bind_of_eq (runSail_currentlyEnabled_pause t)]
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8]
  simp only [runSail_bind_of_eq (runSail_currentlyEnabled_zicfilp h)]
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8]
  unfold decodeBlock4
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8]
  unfold decodeBlock5
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8]
  unfold decodeBlock6
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8]
  unfold decodeBlock7
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8]
  decode_finish

theorem dec_ori {t} (h : DecodeInv t) (rd rs1 : BitVec 5) (imm : BitVec 12) (hrd : rd ≠ 0) :
    runSail (encdec_backwards (Encode (.ArithI (.ORI (rd, rs1, imm))))) t = some (.ITYPE (imm, .Regidx rs1, .Regidx rd, .ORI), t) := by
  obtain ⟨tail, htail⟩ := encdec_backwards_prefix
  rw [htail]
  have hw := enc_ori rd rs1 imm
  generalize Encode _ = w at hw ⊢
  have := rd.isLt; have := rs1.isLt; have := imm.isLt
  have : rd.toNat ≠ 0 := fun e => hrd (BitVec.eq_of_toNat_eq e)
  have f0 : Sail.BitVec.extractLsb w 6 0 = 19#7 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f1 : Sail.BitVec.extractLsb w 11 7 = rd :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f2 : Sail.BitVec.extractLsb w 12 12 = 0#1 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f3 : Sail.BitVec.extractLsb w 13 12 = 2#2 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f4 : Sail.BitVec.extractLsb w 14 12 = 6#3 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f5 : Sail.BitVec.extractLsb w 14 13 = 3#2 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f6 : Sail.BitVec.extractLsb w 14 14 = 1#1 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f7 : Sail.BitVec.extractLsb w 19 15 = rs1 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f8 : Sail.BitVec.extractLsb w 31 20 = imm :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  unfold decodePrefix
  unfold decodeBlock1
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8]
  unfold decodeBlock2
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8]
  unfold decodeBlock3
  simp only [runSail_bind_of_eq (runSail_currentlyEnabled_pause t)]
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8]
  simp only [runSail_bind_of_eq (runSail_currentlyEnabled_zicfilp h)]
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8]
  unfold decodeBlock4
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8]
  unfold decodeBlock5
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8]
  unfold decodeBlock6
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8]
  unfold decodeBlock7
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8]
  decode_finish

theorem dec_xori {t} (h : DecodeInv t) (rd rs1 : BitVec 5) (imm : BitVec 12)  :
    runSail (encdec_backwards (Encode (.ArithI (.XORI (rd, rs1, imm))))) t = some (.ITYPE (imm, .Regidx rs1, .Regidx rd, .XORI), t) := by
  obtain ⟨tail, htail⟩ := encdec_backwards_prefix
  rw [htail]
  have hw := enc_xori rd rs1 imm
  generalize Encode _ = w at hw ⊢
  have := rd.isLt; have := rs1.isLt; have := imm.isLt
  have f0 : Sail.BitVec.extractLsb w 6 0 = 19#7 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f1 : Sail.BitVec.extractLsb w 11 7 = rd :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f2 : Sail.BitVec.extractLsb w 12 12 = 0#1 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f3 : Sail.BitVec.extractLsb w 13 12 = 0#2 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f4 : Sail.BitVec.extractLsb w 14 12 = 4#3 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f5 : Sail.BitVec.extractLsb w 14 13 = 2#2 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f6 : Sail.BitVec.extractLsb w 14 14 = 1#1 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f7 : Sail.BitVec.extractLsb w 19 15 = rs1 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f8 : Sail.BitVec.extractLsb w 31 20 = imm :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  unfold decodePrefix
  unfold decodeBlock1
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8]
  unfold decodeBlock2
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8]
  unfold decodeBlock3
  simp only [runSail_bind_of_eq (runSail_currentlyEnabled_pause t)]
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8]
  simp only [runSail_bind_of_eq (runSail_currentlyEnabled_zicfilp h)]
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8]
  unfold decodeBlock4
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8]
  unfold decodeBlock5
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8]
  unfold decodeBlock6
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8]
  unfold decodeBlock7
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8]
  decode_finish

theorem dec_slli {t} (h : DecodeInv t) (rd rs1 : BitVec 5) (sh : BitVec 6)  :
    runSail (encdec_backwards (Encode (.Shift (.SLLI (rd, rs1, sh))))) t = some (.SHIFTIOP (sh, .Regidx rs1, .Regidx rd, .SLLI), t) := by
  obtain ⟨tail, htail⟩ := encdec_backwards_prefix
  rw [htail]
  have hw := enc_slli rd rs1 sh
  generalize Encode _ = w at hw ⊢
  have := rd.isLt; have := rs1.isLt; have := sh.isLt
  have f0 : Sail.BitVec.extractLsb w 6 0 = 19#7 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f1 : Sail.BitVec.extractLsb w 11 7 = rd :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f2 : Sail.BitVec.extractLsb w 12 12 = 1#1 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f3 : Sail.BitVec.extractLsb w 13 12 = 1#2 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f4 : Sail.BitVec.extractLsb w 14 12 = 1#3 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f5 : Sail.BitVec.extractLsb w 14 13 = 0#2 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f6 : Sail.BitVec.extractLsb w 14 14 = 0#1 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f7 : Sail.BitVec.extractLsb w 19 15 = rs1 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f8 : Sail.BitVec.extractLsb w 25 20 = sh :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f9 : Sail.BitVec.extractLsb w 26 26 = 0#1 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f10 : Sail.BitVec.extractLsb w 31 26 = 0#6 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f11 : Sail.BitVec.extractLsb w 31 27 = 0#5 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f12 : Sail.BitVec.extractLsb w 31 28 = 0#4 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f13 : Sail.BitVec.extractLsb w 31 31 = 0#1 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  unfold decodePrefix
  unfold decodeBlock1
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13]
  unfold decodeBlock2
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13]
  unfold decodeBlock3
  simp only [runSail_bind_of_eq (runSail_currentlyEnabled_pause t)]
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13]
  simp only [runSail_bind_of_eq (runSail_currentlyEnabled_zicfilp h)]
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13]
  unfold decodeBlock4
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13]
  unfold decodeBlock5
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13]
  unfold decodeBlock6
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13]
  unfold decodeBlock7
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13]
  unfold decodeBlock8
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13]
  decode_finish

theorem dec_srli {t} (h : DecodeInv t) (rd rs1 : BitVec 5) (sh : BitVec 6)  :
    runSail (encdec_backwards (Encode (.Shift (.SRLI (rd, rs1, sh))))) t = some (.SHIFTIOP (sh, .Regidx rs1, .Regidx rd, .SRLI), t) := by
  obtain ⟨tail, htail⟩ := encdec_backwards_prefix
  rw [htail]
  have hw := enc_srli rd rs1 sh
  generalize Encode _ = w at hw ⊢
  have := rd.isLt; have := rs1.isLt; have := sh.isLt
  have f0 : Sail.BitVec.extractLsb w 6 0 = 19#7 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f1 : Sail.BitVec.extractLsb w 11 7 = rd :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f2 : Sail.BitVec.extractLsb w 12 12 = 1#1 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f3 : Sail.BitVec.extractLsb w 13 12 = 1#2 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f4 : Sail.BitVec.extractLsb w 14 12 = 5#3 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f5 : Sail.BitVec.extractLsb w 14 13 = 2#2 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f6 : Sail.BitVec.extractLsb w 14 14 = 1#1 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f7 : Sail.BitVec.extractLsb w 19 15 = rs1 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f8 : Sail.BitVec.extractLsb w 25 20 = sh :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f9 : Sail.BitVec.extractLsb w 26 26 = 0#1 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f10 : Sail.BitVec.extractLsb w 31 26 = 0#6 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f11 : Sail.BitVec.extractLsb w 31 27 = 0#5 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f12 : Sail.BitVec.extractLsb w 31 28 = 0#4 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f13 : Sail.BitVec.extractLsb w 31 31 = 0#1 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  unfold decodePrefix
  unfold decodeBlock1
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13]
  unfold decodeBlock2
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13]
  unfold decodeBlock3
  simp only [runSail_bind_of_eq (runSail_currentlyEnabled_pause t)]
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13]
  simp only [runSail_bind_of_eq (runSail_currentlyEnabled_zicfilp h)]
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13]
  unfold decodeBlock4
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13]
  unfold decodeBlock5
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13]
  unfold decodeBlock6
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13]
  unfold decodeBlock7
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13]
  unfold decodeBlock8
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13]
  unfold decodeBlock9
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13]
  decode_finish

theorem dec_srai {t} (h : DecodeInv t) (rd rs1 : BitVec 5) (sh : BitVec 6)  :
    runSail (encdec_backwards (Encode (.Shift (.SRAI (rd, rs1, sh))))) t = some (.SHIFTIOP (sh, .Regidx rs1, .Regidx rd, .SRAI), t) := by
  obtain ⟨tail, htail⟩ := encdec_backwards_prefix
  rw [htail]
  have hw := enc_srai rd rs1 sh
  generalize Encode _ = w at hw ⊢
  have := rd.isLt; have := rs1.isLt; have := sh.isLt
  have f0 : Sail.BitVec.extractLsb w 6 0 = 19#7 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f1 : Sail.BitVec.extractLsb w 11 7 = rd :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f2 : Sail.BitVec.extractLsb w 12 12 = 1#1 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f3 : Sail.BitVec.extractLsb w 13 12 = 1#2 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f4 : Sail.BitVec.extractLsb w 14 12 = 5#3 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f5 : Sail.BitVec.extractLsb w 14 13 = 2#2 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f6 : Sail.BitVec.extractLsb w 14 14 = 1#1 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f7 : Sail.BitVec.extractLsb w 19 15 = rs1 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f8 : Sail.BitVec.extractLsb w 25 20 = sh :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f9 : Sail.BitVec.extractLsb w 26 26 = 0#1 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f10 : Sail.BitVec.extractLsb w 31 26 = 16#6 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f11 : Sail.BitVec.extractLsb w 31 27 = 8#5 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f12 : Sail.BitVec.extractLsb w 31 28 = 4#4 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f13 : Sail.BitVec.extractLsb w 31 31 = 0#1 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  unfold decodePrefix
  unfold decodeBlock1
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13]
  unfold decodeBlock2
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13]
  unfold decodeBlock3
  simp only [runSail_bind_of_eq (runSail_currentlyEnabled_pause t)]
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13]
  simp only [runSail_bind_of_eq (runSail_currentlyEnabled_zicfilp h)]
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13]
  unfold decodeBlock4
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13]
  unfold decodeBlock5
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13]
  unfold decodeBlock6
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13]
  unfold decodeBlock7
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13]
  unfold decodeBlock8
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13]
  unfold decodeBlock9
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13]
  unfold decodeBlock10
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13]
  decode_finish

theorem dec_lui {t} (h : DecodeInv t) (rd : BitVec 5) (imm : BitVec 20)  :
    runSail (encdec_backwards (Encode (.ArithI (.LUI (rd, imm))))) t = some (.UTYPE (imm, .Regidx rd, .LUI), t) := by
  obtain ⟨tail, htail⟩ := encdec_backwards_prefix
  rw [htail]
  have hw := enc_lui rd imm
  generalize Encode _ = w at hw ⊢
  have := rd.isLt; have := imm.isLt
  have f0 : Sail.BitVec.extractLsb w 6 0 = 55#7 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f1 : Sail.BitVec.extractLsb w 11 7 = rd :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f2 : Sail.BitVec.extractLsb w 31 12 = imm :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  unfold decodePrefix
  unfold decodeBlock1
  try guard_simp hw [f0, f1, f2]
  unfold decodeBlock2
  try guard_simp hw [f0, f1, f2]
  unfold decodeBlock3
  simp only [runSail_bind_of_eq (runSail_currentlyEnabled_pause t)]
  try guard_simp hw [f0, f1, f2]
  simp only [runSail_bind_of_eq (runSail_currentlyEnabled_zicfilp h)]
  try guard_simp hw [f0, f1, f2]
  decode_finish

theorem dec_auipc {t} (h : DecodeInv t) (rd : BitVec 5) (imm : BitVec 20)  :
    runSail (encdec_backwards (Encode (.ArithI (.AUIPC (rd, imm))))) t = some (.UTYPE (imm, .Regidx rd, .AUIPC), t) := by
  obtain ⟨tail, htail⟩ := encdec_backwards_prefix
  rw [htail]
  have hw := enc_auipc rd imm
  generalize Encode _ = w at hw ⊢
  have := rd.isLt; have := imm.isLt
  have f0 : Sail.BitVec.extractLsb w 6 0 = 23#7 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f1 : Sail.BitVec.extractLsb w 11 7 = rd :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f2 : Sail.BitVec.extractLsb w 31 12 = imm :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  unfold decodePrefix
  unfold decodeBlock1
  try guard_simp hw [f0, f1, f2]
  unfold decodeBlock2
  try guard_simp hw [f0, f1, f2]
  unfold decodeBlock3
  simp only [runSail_bind_of_eq (runSail_currentlyEnabled_pause t)]
  try guard_simp hw [f0, f1, f2]
  simp only [runSail_bind_of_eq (runSail_currentlyEnabled_zicfilp h)]
  try guard_simp hw [f0, f1, f2]
  decode_finish

end FlapjackRiscvCheck
