import FlapjackRiscvCheck.Decode.Basic
import FlapjackRiscvCheck.Decode.Encoding
import FlapjackRiscvCheck.Decode.Imm

/-! GENERATED by scripts/gen-decode-proofs.py. Sail decodes the L3 encodings of the
tier-1 Mem instructions to the Sail ASTs `toSail` assigns them. -/

namespace FlapjackRiscvCheck

open LeanRV64D LeanRV64D.Functions Flapjack.RiscV.L3

set_option maxRecDepth 100000

theorem dec_ld {s t} (h : ExecPre s t) (rd rs1 : BitVec 5) (imm : BitVec 12)  :
    runSail (encdec_backwards (Encode (.Load (.LD (rd, rs1, imm))))) t = some (.LOAD (imm, .Regidx rs1, .Regidx rd, false, 8), t) := by
  obtain ⟨tail, htail⟩ := encdec_backwards_prefix
  rw [htail]
  have hw := enc_ld rd rs1 imm
  generalize Encode _ = w at hw ⊢
  have := rd.isLt; have := rs1.isLt; have := imm.isLt
  have f0 : Sail.BitVec.extractLsb w 6 0 = 3#7 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f1 : Sail.BitVec.extractLsb w 11 7 = rd :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f2 : Sail.BitVec.extractLsb w 12 12 = 1#1 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f3 : Sail.BitVec.extractLsb w 13 12 = 3#2 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f4 : Sail.BitVec.extractLsb w 14 12 = 3#3 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f5 : Sail.BitVec.extractLsb w 14 13 = 1#2 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f6 : Sail.BitVec.extractLsb w 14 14 = 0#1 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f7 : Sail.BitVec.extractLsb w 19 15 = rs1 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f8 : Sail.BitVec.extractLsb w 31 20 = imm :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  unfold decodePrefix
  unfold decodeBlock1
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8]
  unfold decodeBlock2
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8]
  unfold decodeBlock3
  simp only [runSail_bind_of_eq (runSail_currentlyEnabled_pause t)]
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8]
  simp only [runSail_bind_of_eq (runSail_currentlyEnabled_zicfilp h)]
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8]
  unfold decodeBlock4
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8]
  unfold decodeBlock5
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8]
  unfold decodeBlock6
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8]
  unfold decodeBlock7
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8]
  unfold decodeBlock8
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8]
  unfold decodeBlock9
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8]
  unfold decodeBlock10
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8]
  unfold decodeBlock11
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8]
  unfold decodeBlock12
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8]
  unfold decodeBlock13
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8]
  unfold decodeBlock14
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8]
  unfold decodeBlock15
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8]
  unfold decodeBlock16
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8]
  unfold decodeBlock17
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8]
  unfold decodeBlock18
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8]
  unfold decodeBlock19
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8]
  unfold decodeBlock20
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8]
  unfold decodeBlock21
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8]
  decode_finish
  all_goals first | exact imm_S _ | (rw [imm_B]) | (rw [imm_J]) | rfl

theorem dec_lwu {s t} (h : ExecPre s t) (rd rs1 : BitVec 5) (imm : BitVec 12)  :
    runSail (encdec_backwards (Encode (.Load (.LWU (rd, rs1, imm))))) t = some (.LOAD (imm, .Regidx rs1, .Regidx rd, true, 4), t) := by
  obtain ⟨tail, htail⟩ := encdec_backwards_prefix
  rw [htail]
  have hw := enc_lwu rd rs1 imm
  generalize Encode _ = w at hw ⊢
  have := rd.isLt; have := rs1.isLt; have := imm.isLt
  have f0 : Sail.BitVec.extractLsb w 6 0 = 3#7 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f1 : Sail.BitVec.extractLsb w 11 7 = rd :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f2 : Sail.BitVec.extractLsb w 12 12 = 0#1 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f3 : Sail.BitVec.extractLsb w 13 12 = 2#2 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f4 : Sail.BitVec.extractLsb w 14 12 = 6#3 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f5 : Sail.BitVec.extractLsb w 14 13 = 3#2 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f6 : Sail.BitVec.extractLsb w 14 14 = 1#1 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f7 : Sail.BitVec.extractLsb w 19 15 = rs1 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f8 : Sail.BitVec.extractLsb w 31 20 = imm :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  unfold decodePrefix
  unfold decodeBlock1
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8]
  unfold decodeBlock2
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8]
  unfold decodeBlock3
  simp only [runSail_bind_of_eq (runSail_currentlyEnabled_pause t)]
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8]
  simp only [runSail_bind_of_eq (runSail_currentlyEnabled_zicfilp h)]
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8]
  unfold decodeBlock4
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8]
  unfold decodeBlock5
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8]
  unfold decodeBlock6
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8]
  unfold decodeBlock7
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8]
  unfold decodeBlock8
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8]
  unfold decodeBlock9
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8]
  unfold decodeBlock10
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8]
  unfold decodeBlock11
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8]
  unfold decodeBlock12
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8]
  unfold decodeBlock13
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8]
  unfold decodeBlock14
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8]
  unfold decodeBlock15
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8]
  unfold decodeBlock16
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8]
  unfold decodeBlock17
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8]
  unfold decodeBlock18
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8]
  unfold decodeBlock19
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8]
  unfold decodeBlock20
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8]
  unfold decodeBlock21
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8]
  decode_finish
  all_goals first | exact imm_S _ | (rw [imm_B]) | (rw [imm_J]) | rfl

theorem dec_lhu {s t} (h : ExecPre s t) (rd rs1 : BitVec 5) (imm : BitVec 12)  :
    runSail (encdec_backwards (Encode (.Load (.LHU (rd, rs1, imm))))) t = some (.LOAD (imm, .Regidx rs1, .Regidx rd, true, 2), t) := by
  obtain ⟨tail, htail⟩ := encdec_backwards_prefix
  rw [htail]
  have hw := enc_lhu rd rs1 imm
  generalize Encode _ = w at hw ⊢
  have := rd.isLt; have := rs1.isLt; have := imm.isLt
  have f0 : Sail.BitVec.extractLsb w 6 0 = 3#7 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f1 : Sail.BitVec.extractLsb w 11 7 = rd :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f2 : Sail.BitVec.extractLsb w 12 12 = 1#1 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f3 : Sail.BitVec.extractLsb w 13 12 = 1#2 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f4 : Sail.BitVec.extractLsb w 14 12 = 5#3 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f5 : Sail.BitVec.extractLsb w 14 13 = 2#2 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f6 : Sail.BitVec.extractLsb w 14 14 = 1#1 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f7 : Sail.BitVec.extractLsb w 19 15 = rs1 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f8 : Sail.BitVec.extractLsb w 31 20 = imm :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  unfold decodePrefix
  unfold decodeBlock1
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8]
  unfold decodeBlock2
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8]
  unfold decodeBlock3
  simp only [runSail_bind_of_eq (runSail_currentlyEnabled_pause t)]
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8]
  simp only [runSail_bind_of_eq (runSail_currentlyEnabled_zicfilp h)]
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8]
  unfold decodeBlock4
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8]
  unfold decodeBlock5
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8]
  unfold decodeBlock6
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8]
  unfold decodeBlock7
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8]
  unfold decodeBlock8
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8]
  unfold decodeBlock9
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8]
  unfold decodeBlock10
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8]
  unfold decodeBlock11
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8]
  unfold decodeBlock12
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8]
  unfold decodeBlock13
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8]
  unfold decodeBlock14
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8]
  unfold decodeBlock15
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8]
  unfold decodeBlock16
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8]
  unfold decodeBlock17
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8]
  unfold decodeBlock18
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8]
  unfold decodeBlock19
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8]
  unfold decodeBlock20
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8]
  unfold decodeBlock21
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8]
  decode_finish
  all_goals first | exact imm_S _ | (rw [imm_B]) | (rw [imm_J]) | rfl

theorem dec_lbu {s t} (h : ExecPre s t) (rd rs1 : BitVec 5) (imm : BitVec 12)  :
    runSail (encdec_backwards (Encode (.Load (.LBU (rd, rs1, imm))))) t = some (.LOAD (imm, .Regidx rs1, .Regidx rd, true, 1), t) := by
  obtain ⟨tail, htail⟩ := encdec_backwards_prefix
  rw [htail]
  have hw := enc_lbu rd rs1 imm
  generalize Encode _ = w at hw ⊢
  have := rd.isLt; have := rs1.isLt; have := imm.isLt
  have f0 : Sail.BitVec.extractLsb w 6 0 = 3#7 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f1 : Sail.BitVec.extractLsb w 11 7 = rd :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f2 : Sail.BitVec.extractLsb w 12 12 = 0#1 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f3 : Sail.BitVec.extractLsb w 13 12 = 0#2 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f4 : Sail.BitVec.extractLsb w 14 12 = 4#3 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f5 : Sail.BitVec.extractLsb w 14 13 = 2#2 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f6 : Sail.BitVec.extractLsb w 14 14 = 1#1 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f7 : Sail.BitVec.extractLsb w 19 15 = rs1 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f8 : Sail.BitVec.extractLsb w 31 20 = imm :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  unfold decodePrefix
  unfold decodeBlock1
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8]
  unfold decodeBlock2
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8]
  unfold decodeBlock3
  simp only [runSail_bind_of_eq (runSail_currentlyEnabled_pause t)]
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8]
  simp only [runSail_bind_of_eq (runSail_currentlyEnabled_zicfilp h)]
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8]
  unfold decodeBlock4
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8]
  unfold decodeBlock5
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8]
  unfold decodeBlock6
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8]
  unfold decodeBlock7
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8]
  unfold decodeBlock8
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8]
  unfold decodeBlock9
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8]
  unfold decodeBlock10
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8]
  unfold decodeBlock11
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8]
  unfold decodeBlock12
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8]
  unfold decodeBlock13
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8]
  unfold decodeBlock14
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8]
  unfold decodeBlock15
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8]
  unfold decodeBlock16
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8]
  unfold decodeBlock17
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8]
  unfold decodeBlock18
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8]
  unfold decodeBlock19
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8]
  unfold decodeBlock20
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8]
  unfold decodeBlock21
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8]
  decode_finish
  all_goals first | exact imm_S _ | (rw [imm_B]) | (rw [imm_J]) | rfl

theorem dec_sd {s t} (h : ExecPre s t) (rs1 rs2 : BitVec 5) (imm : BitVec 12)  :
    runSail (encdec_backwards (Encode (.Store (.SD (rs1, rs2, imm))))) t = some (.STORE (imm, .Regidx rs2, .Regidx rs1, 8), t) := by
  obtain ⟨tail, htail⟩ := encdec_backwards_prefix
  rw [htail]
  have hw := enc_sd rs1 rs2 imm
  generalize Encode _ = w at hw ⊢
  have := rs1.isLt; have := rs2.isLt; have := imm.isLt
  have := (imm.extractLsb 11 5).isLt; have := (imm.extractLsb 4 0).isLt
  have f0 : Sail.BitVec.extractLsb w 6 0 = 35#7 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f1 : Sail.BitVec.extractLsb w 11 7 = imm.extractLsb 4 0 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f2 : Sail.BitVec.extractLsb w 12 12 = 1#1 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f3 : Sail.BitVec.extractLsb w 13 12 = 3#2 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f4 : Sail.BitVec.extractLsb w 14 12 = 3#3 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f5 : Sail.BitVec.extractLsb w 14 13 = 1#2 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f6 : Sail.BitVec.extractLsb w 14 14 = 0#1 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f7 : Sail.BitVec.extractLsb w 19 15 = rs1 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f8 : Sail.BitVec.extractLsb w 24 20 = rs2 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f9 : Sail.BitVec.extractLsb w 31 25 = imm.extractLsb 11 5 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  unfold decodePrefix
  unfold decodeBlock1
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9]
  unfold decodeBlock2
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9]
  unfold decodeBlock3
  simp only [runSail_bind_of_eq (runSail_currentlyEnabled_pause t)]
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9]
  simp only [runSail_bind_of_eq (runSail_currentlyEnabled_zicfilp h)]
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9]
  unfold decodeBlock4
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9]
  unfold decodeBlock5
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9]
  unfold decodeBlock6
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9]
  unfold decodeBlock7
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9]
  unfold decodeBlock8
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9]
  unfold decodeBlock9
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9]
  unfold decodeBlock10
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9]
  unfold decodeBlock11
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9]
  unfold decodeBlock12
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9]
  unfold decodeBlock13
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9]
  unfold decodeBlock14
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9]
  unfold decodeBlock15
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9]
  unfold decodeBlock16
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9]
  unfold decodeBlock17
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9]
  unfold decodeBlock18
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9]
  unfold decodeBlock19
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9]
  unfold decodeBlock20
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9]
  unfold decodeBlock21
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9]
  unfold decodeBlock22
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9]
  decode_finish
  all_goals first | exact imm_S _ | (rw [imm_B]) | (rw [imm_J]) | rfl

theorem dec_sw {s t} (h : ExecPre s t) (rs1 rs2 : BitVec 5) (imm : BitVec 12)  :
    runSail (encdec_backwards (Encode (.Store (.SW (rs1, rs2, imm))))) t = some (.STORE (imm, .Regidx rs2, .Regidx rs1, 4), t) := by
  obtain ⟨tail, htail⟩ := encdec_backwards_prefix
  rw [htail]
  have hw := enc_sw rs1 rs2 imm
  generalize Encode _ = w at hw ⊢
  have := rs1.isLt; have := rs2.isLt; have := imm.isLt
  have := (imm.extractLsb 11 5).isLt; have := (imm.extractLsb 4 0).isLt
  have f0 : Sail.BitVec.extractLsb w 6 0 = 35#7 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f1 : Sail.BitVec.extractLsb w 11 7 = imm.extractLsb 4 0 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f2 : Sail.BitVec.extractLsb w 12 12 = 0#1 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f3 : Sail.BitVec.extractLsb w 13 12 = 2#2 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f4 : Sail.BitVec.extractLsb w 14 12 = 2#3 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f5 : Sail.BitVec.extractLsb w 14 13 = 1#2 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f6 : Sail.BitVec.extractLsb w 14 14 = 0#1 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f7 : Sail.BitVec.extractLsb w 19 15 = rs1 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f8 : Sail.BitVec.extractLsb w 24 20 = rs2 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f9 : Sail.BitVec.extractLsb w 31 25 = imm.extractLsb 11 5 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  unfold decodePrefix
  unfold decodeBlock1
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9]
  unfold decodeBlock2
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9]
  unfold decodeBlock3
  simp only [runSail_bind_of_eq (runSail_currentlyEnabled_pause t)]
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9]
  simp only [runSail_bind_of_eq (runSail_currentlyEnabled_zicfilp h)]
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9]
  unfold decodeBlock4
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9]
  unfold decodeBlock5
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9]
  unfold decodeBlock6
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9]
  unfold decodeBlock7
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9]
  unfold decodeBlock8
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9]
  unfold decodeBlock9
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9]
  unfold decodeBlock10
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9]
  unfold decodeBlock11
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9]
  unfold decodeBlock12
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9]
  unfold decodeBlock13
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9]
  unfold decodeBlock14
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9]
  unfold decodeBlock15
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9]
  unfold decodeBlock16
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9]
  unfold decodeBlock17
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9]
  unfold decodeBlock18
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9]
  unfold decodeBlock19
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9]
  unfold decodeBlock20
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9]
  unfold decodeBlock21
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9]
  unfold decodeBlock22
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9]
  decode_finish
  all_goals first | exact imm_S _ | (rw [imm_B]) | (rw [imm_J]) | rfl

theorem dec_sh {s t} (h : ExecPre s t) (rs1 rs2 : BitVec 5) (imm : BitVec 12)  :
    runSail (encdec_backwards (Encode (.Store (.SH (rs1, rs2, imm))))) t = some (.STORE (imm, .Regidx rs2, .Regidx rs1, 2), t) := by
  obtain ⟨tail, htail⟩ := encdec_backwards_prefix
  rw [htail]
  have hw := enc_sh rs1 rs2 imm
  generalize Encode _ = w at hw ⊢
  have := rs1.isLt; have := rs2.isLt; have := imm.isLt
  have := (imm.extractLsb 11 5).isLt; have := (imm.extractLsb 4 0).isLt
  have f0 : Sail.BitVec.extractLsb w 6 0 = 35#7 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f1 : Sail.BitVec.extractLsb w 11 7 = imm.extractLsb 4 0 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f2 : Sail.BitVec.extractLsb w 12 12 = 1#1 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f3 : Sail.BitVec.extractLsb w 13 12 = 1#2 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f4 : Sail.BitVec.extractLsb w 14 12 = 1#3 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f5 : Sail.BitVec.extractLsb w 14 13 = 0#2 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f6 : Sail.BitVec.extractLsb w 14 14 = 0#1 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f7 : Sail.BitVec.extractLsb w 19 15 = rs1 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f8 : Sail.BitVec.extractLsb w 24 20 = rs2 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f9 : Sail.BitVec.extractLsb w 31 25 = imm.extractLsb 11 5 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  unfold decodePrefix
  unfold decodeBlock1
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9]
  unfold decodeBlock2
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9]
  unfold decodeBlock3
  simp only [runSail_bind_of_eq (runSail_currentlyEnabled_pause t)]
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9]
  simp only [runSail_bind_of_eq (runSail_currentlyEnabled_zicfilp h)]
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9]
  unfold decodeBlock4
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9]
  unfold decodeBlock5
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9]
  unfold decodeBlock6
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9]
  unfold decodeBlock7
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9]
  unfold decodeBlock8
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9]
  unfold decodeBlock9
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9]
  unfold decodeBlock10
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9]
  unfold decodeBlock11
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9]
  unfold decodeBlock12
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9]
  unfold decodeBlock13
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9]
  unfold decodeBlock14
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9]
  unfold decodeBlock15
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9]
  unfold decodeBlock16
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9]
  unfold decodeBlock17
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9]
  unfold decodeBlock18
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9]
  unfold decodeBlock19
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9]
  unfold decodeBlock20
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9]
  unfold decodeBlock21
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9]
  unfold decodeBlock22
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9]
  decode_finish
  all_goals first | exact imm_S _ | (rw [imm_B]) | (rw [imm_J]) | rfl

theorem dec_sb {s t} (h : ExecPre s t) (rs1 rs2 : BitVec 5) (imm : BitVec 12)  :
    runSail (encdec_backwards (Encode (.Store (.SB (rs1, rs2, imm))))) t = some (.STORE (imm, .Regidx rs2, .Regidx rs1, 1), t) := by
  obtain ⟨tail, htail⟩ := encdec_backwards_prefix
  rw [htail]
  have hw := enc_sb rs1 rs2 imm
  generalize Encode _ = w at hw ⊢
  have := rs1.isLt; have := rs2.isLt; have := imm.isLt
  have := (imm.extractLsb 11 5).isLt; have := (imm.extractLsb 4 0).isLt
  have f0 : Sail.BitVec.extractLsb w 6 0 = 35#7 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f1 : Sail.BitVec.extractLsb w 11 7 = imm.extractLsb 4 0 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f2 : Sail.BitVec.extractLsb w 12 12 = 0#1 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f3 : Sail.BitVec.extractLsb w 13 12 = 0#2 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f4 : Sail.BitVec.extractLsb w 14 12 = 0#3 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f5 : Sail.BitVec.extractLsb w 14 13 = 0#2 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f6 : Sail.BitVec.extractLsb w 14 14 = 0#1 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f7 : Sail.BitVec.extractLsb w 19 15 = rs1 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f8 : Sail.BitVec.extractLsb w 24 20 = rs2 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f9 : Sail.BitVec.extractLsb w 31 25 = imm.extractLsb 11 5 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  unfold decodePrefix
  unfold decodeBlock1
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9]
  unfold decodeBlock2
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9]
  unfold decodeBlock3
  simp only [runSail_bind_of_eq (runSail_currentlyEnabled_pause t)]
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9]
  simp only [runSail_bind_of_eq (runSail_currentlyEnabled_zicfilp h)]
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9]
  unfold decodeBlock4
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9]
  unfold decodeBlock5
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9]
  unfold decodeBlock6
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9]
  unfold decodeBlock7
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9]
  unfold decodeBlock8
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9]
  unfold decodeBlock9
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9]
  unfold decodeBlock10
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9]
  unfold decodeBlock11
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9]
  unfold decodeBlock12
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9]
  unfold decodeBlock13
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9]
  unfold decodeBlock14
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9]
  unfold decodeBlock15
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9]
  unfold decodeBlock16
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9]
  unfold decodeBlock17
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9]
  unfold decodeBlock18
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9]
  unfold decodeBlock19
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9]
  unfold decodeBlock20
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9]
  unfold decodeBlock21
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9]
  unfold decodeBlock22
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9]
  decode_finish
  all_goals first | exact imm_S _ | (rw [imm_B]) | (rw [imm_J]) | rfl

end FlapjackRiscvCheck
