import FlapjackRiscvCheck.Decode.Basic
import FlapjackRiscvCheck.Decode.Encoding
import FlapjackRiscvCheck.Decode.Imm

/-! GENERATED by scripts/gen-decode-proofs.py. Sail decodes the L3 encodings of the
tier-1 MulDiv instructions to the Sail ASTs `toSail` assigns them. -/

namespace FlapjackRiscvCheck

open LeanRV64D LeanRV64D.Functions Flapjack.RiscV.L3

set_option maxRecDepth 100000

theorem dec_mul {s t} (h : ExecPre s t) (rd rs1 rs2 : BitVec 5)  :
    runSail (encdec_backwards (Encode (.MulDiv (.MUL (rd, rs1, rs2))))) t = some (.MUL (.Regidx rs2, .Regidx rs1, .Regidx rd, ⟨.Low, .Signed, .Signed⟩), t) := by
  obtain ⟨tail, htail⟩ := encdec_backwards_prefix
  rw [htail]
  have hw := enc_mul rd rs1 rs2
  generalize Encode _ = w at hw ⊢
  have := rd.isLt; have := rs1.isLt; have := rs2.isLt
  have f0 : Sail.BitVec.extractLsb w 6 0 = 51#7 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f1 : Sail.BitVec.extractLsb w 11 7 = rd :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f2 : Sail.BitVec.extractLsb w 12 12 = 0#1 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f3 : Sail.BitVec.extractLsb w 13 12 = 0#2 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f4 : Sail.BitVec.extractLsb w 14 12 = 0#3 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f5 : Sail.BitVec.extractLsb w 14 13 = 0#2 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f6 : Sail.BitVec.extractLsb w 14 14 = 0#1 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f7 : Sail.BitVec.extractLsb w 19 15 = rs1 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f8 : Sail.BitVec.extractLsb w 24 20 = rs2 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f9 : Sail.BitVec.extractLsb w 25 25 = 1#1 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f10 : Sail.BitVec.extractLsb w 26 26 = 0#1 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f11 : Sail.BitVec.extractLsb w 30 25 = 1#6 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f12 : Sail.BitVec.extractLsb w 31 25 = 1#7 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f13 : Sail.BitVec.extractLsb w 31 26 = 0#6 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f14 : Sail.BitVec.extractLsb w 31 27 = 0#5 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f15 : Sail.BitVec.extractLsb w 31 28 = 0#4 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f16 : Sail.BitVec.extractLsb w 31 31 = 0#1 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  unfold decodePrefix
  unfold decodeBlock1
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, f15, f16]
  unfold decodeBlock2
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, f15, f16]
  unfold decodeBlock3
  simp only [runSail_bind_of_eq (runSail_currentlyEnabled_pause t)]
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, f15, f16]
  simp only [runSail_bind_of_eq (runSail_currentlyEnabled_zicfilp h)]
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, f15, f16]
  unfold decodeBlock4
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, f15, f16]
  unfold decodeBlock5
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, f15, f16]
  unfold decodeBlock6
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, f15, f16]
  unfold decodeBlock7
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, f15, f16]
  unfold decodeBlock8
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, f15, f16]
  unfold decodeBlock9
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, f15, f16]
  unfold decodeBlock10
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, f15, f16]
  unfold decodeBlock11
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, f15, f16]
  unfold decodeBlock12
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, f15, f16]
  unfold decodeBlock13
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, f15, f16]
  unfold decodeBlock14
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, f15, f16]
  unfold decodeBlock15
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, f15, f16]
  unfold decodeBlock16
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, f15, f16]
  unfold decodeBlock17
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, f15, f16]
  unfold decodeBlock18
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, f15, f16]
  unfold decodeBlock19
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, f15, f16]
  unfold decodeBlock20
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, f15, f16]
  unfold decodeBlock21
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, f15, f16]
  unfold decodeBlock22
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, f15, f16]
  unfold decodeBlock23
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, f15, f16]
  unfold decodeBlock24
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, f15, f16]
  unfold decodeBlock25
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, f15, f16]
  unfold decodeBlock26
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, f15, f16]
  unfold decodeBlock27
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, f15, f16]
  unfold decodeBlock28
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, f15, f16]
  unfold decodeBlock29
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, f15, f16]
  unfold decodeBlock30
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, f15, f16]
  unfold decodeBlock31
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, f15, f16]
  unfold decodeBlock32
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, f15, f16]
  unfold decodeBlock33
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, f15, f16]
  unfold decodeBlock34
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, f15, f16]
  unfold decodeBlock35
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, f15, f16]
  unfold decodeBlock36
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, f15, f16]
  unfold decodeBlock37
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, f15, f16]
  decode_finish
  try simp only [runSail_bind_of_eq (runSail_currentlyEnabled_M h),
    runSail_bind_of_eq (runSail_currentlyEnabled_Zmmul h)]
  try decode_finish

theorem dec_mulhu {s t} (h : ExecPre s t) (rd rs1 rs2 : BitVec 5)  :
    runSail (encdec_backwards (Encode (.MulDiv (.MULHU (rd, rs1, rs2))))) t = some (.MUL (.Regidx rs2, .Regidx rs1, .Regidx rd, ⟨.High, .Unsigned, .Unsigned⟩), t) := by
  obtain ⟨tail, htail⟩ := encdec_backwards_prefix
  rw [htail]
  have hw := enc_mulhu rd rs1 rs2
  generalize Encode _ = w at hw ⊢
  have := rd.isLt; have := rs1.isLt; have := rs2.isLt
  have f0 : Sail.BitVec.extractLsb w 6 0 = 51#7 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f1 : Sail.BitVec.extractLsb w 11 7 = rd :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f2 : Sail.BitVec.extractLsb w 12 12 = 1#1 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f3 : Sail.BitVec.extractLsb w 13 12 = 3#2 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f4 : Sail.BitVec.extractLsb w 14 12 = 3#3 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f5 : Sail.BitVec.extractLsb w 14 13 = 1#2 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f6 : Sail.BitVec.extractLsb w 14 14 = 0#1 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f7 : Sail.BitVec.extractLsb w 19 15 = rs1 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f8 : Sail.BitVec.extractLsb w 24 20 = rs2 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f9 : Sail.BitVec.extractLsb w 25 25 = 1#1 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f10 : Sail.BitVec.extractLsb w 26 26 = 0#1 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f11 : Sail.BitVec.extractLsb w 30 25 = 1#6 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f12 : Sail.BitVec.extractLsb w 31 25 = 1#7 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f13 : Sail.BitVec.extractLsb w 31 26 = 0#6 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f14 : Sail.BitVec.extractLsb w 31 27 = 0#5 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f15 : Sail.BitVec.extractLsb w 31 28 = 0#4 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f16 : Sail.BitVec.extractLsb w 31 31 = 0#1 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  unfold decodePrefix
  unfold decodeBlock1
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, f15, f16]
  unfold decodeBlock2
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, f15, f16]
  unfold decodeBlock3
  simp only [runSail_bind_of_eq (runSail_currentlyEnabled_pause t)]
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, f15, f16]
  simp only [runSail_bind_of_eq (runSail_currentlyEnabled_zicfilp h)]
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, f15, f16]
  unfold decodeBlock4
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, f15, f16]
  unfold decodeBlock5
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, f15, f16]
  unfold decodeBlock6
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, f15, f16]
  unfold decodeBlock7
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, f15, f16]
  unfold decodeBlock8
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, f15, f16]
  unfold decodeBlock9
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, f15, f16]
  unfold decodeBlock10
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, f15, f16]
  unfold decodeBlock11
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, f15, f16]
  unfold decodeBlock12
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, f15, f16]
  unfold decodeBlock13
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, f15, f16]
  unfold decodeBlock14
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, f15, f16]
  unfold decodeBlock15
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, f15, f16]
  unfold decodeBlock16
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, f15, f16]
  unfold decodeBlock17
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, f15, f16]
  unfold decodeBlock18
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, f15, f16]
  unfold decodeBlock19
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, f15, f16]
  unfold decodeBlock20
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, f15, f16]
  unfold decodeBlock21
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, f15, f16]
  unfold decodeBlock22
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, f15, f16]
  unfold decodeBlock23
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, f15, f16]
  unfold decodeBlock24
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, f15, f16]
  unfold decodeBlock25
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, f15, f16]
  unfold decodeBlock26
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, f15, f16]
  unfold decodeBlock27
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, f15, f16]
  unfold decodeBlock28
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, f15, f16]
  unfold decodeBlock29
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, f15, f16]
  unfold decodeBlock30
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, f15, f16]
  unfold decodeBlock31
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, f15, f16]
  unfold decodeBlock32
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, f15, f16]
  unfold decodeBlock33
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, f15, f16]
  unfold decodeBlock34
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, f15, f16]
  unfold decodeBlock35
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, f15, f16]
  unfold decodeBlock36
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, f15, f16]
  unfold decodeBlock37
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, f15, f16]
  decode_finish
  try simp only [runSail_bind_of_eq (runSail_currentlyEnabled_M h),
    runSail_bind_of_eq (runSail_currentlyEnabled_Zmmul h)]
  try decode_finish

theorem dec_div {s t} (h : ExecPre s t) (rd rs1 rs2 : BitVec 5)  :
    runSail (encdec_backwards (Encode (.MulDiv (.DIV (rd, rs1, rs2))))) t = some (.DIV (.Regidx rs2, .Regidx rs1, .Regidx rd, false), t) := by
  obtain ⟨tail, htail⟩ := encdec_backwards_prefix
  rw [htail]
  have hw := enc_div rd rs1 rs2
  generalize Encode _ = w at hw ⊢
  have := rd.isLt; have := rs1.isLt; have := rs2.isLt
  have f0 : Sail.BitVec.extractLsb w 6 0 = 51#7 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f1 : Sail.BitVec.extractLsb w 11 7 = rd :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f2 : Sail.BitVec.extractLsb w 12 12 = 0#1 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f3 : Sail.BitVec.extractLsb w 13 12 = 0#2 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f4 : Sail.BitVec.extractLsb w 14 12 = 4#3 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f5 : Sail.BitVec.extractLsb w 14 13 = 2#2 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f6 : Sail.BitVec.extractLsb w 14 14 = 1#1 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f7 : Sail.BitVec.extractLsb w 19 15 = rs1 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f8 : Sail.BitVec.extractLsb w 24 20 = rs2 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f9 : Sail.BitVec.extractLsb w 25 25 = 1#1 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f10 : Sail.BitVec.extractLsb w 26 26 = 0#1 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f11 : Sail.BitVec.extractLsb w 30 25 = 1#6 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f12 : Sail.BitVec.extractLsb w 31 25 = 1#7 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f13 : Sail.BitVec.extractLsb w 31 26 = 0#6 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f14 : Sail.BitVec.extractLsb w 31 27 = 0#5 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f15 : Sail.BitVec.extractLsb w 31 28 = 0#4 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f16 : Sail.BitVec.extractLsb w 31 31 = 0#1 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  unfold decodePrefix
  unfold decodeBlock1
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, f15, f16]
  unfold decodeBlock2
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, f15, f16]
  unfold decodeBlock3
  simp only [runSail_bind_of_eq (runSail_currentlyEnabled_pause t)]
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, f15, f16]
  simp only [runSail_bind_of_eq (runSail_currentlyEnabled_zicfilp h)]
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, f15, f16]
  unfold decodeBlock4
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, f15, f16]
  unfold decodeBlock5
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, f15, f16]
  unfold decodeBlock6
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, f15, f16]
  unfold decodeBlock7
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, f15, f16]
  unfold decodeBlock8
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, f15, f16]
  unfold decodeBlock9
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, f15, f16]
  unfold decodeBlock10
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, f15, f16]
  unfold decodeBlock11
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, f15, f16]
  unfold decodeBlock12
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, f15, f16]
  unfold decodeBlock13
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, f15, f16]
  unfold decodeBlock14
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, f15, f16]
  unfold decodeBlock15
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, f15, f16]
  unfold decodeBlock16
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, f15, f16]
  unfold decodeBlock17
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, f15, f16]
  unfold decodeBlock18
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, f15, f16]
  unfold decodeBlock19
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, f15, f16]
  unfold decodeBlock20
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, f15, f16]
  unfold decodeBlock21
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, f15, f16]
  unfold decodeBlock22
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, f15, f16]
  unfold decodeBlock23
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, f15, f16]
  unfold decodeBlock24
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, f15, f16]
  unfold decodeBlock25
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, f15, f16]
  unfold decodeBlock26
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, f15, f16]
  unfold decodeBlock27
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, f15, f16]
  unfold decodeBlock28
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, f15, f16]
  unfold decodeBlock29
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, f15, f16]
  unfold decodeBlock30
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, f15, f16]
  unfold decodeBlock31
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, f15, f16]
  unfold decodeBlock32
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, f15, f16]
  unfold decodeBlock33
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, f15, f16]
  unfold decodeBlock34
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, f15, f16]
  unfold decodeBlock35
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, f15, f16]
  unfold decodeBlock36
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, f15, f16]
  unfold decodeBlock37
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, f15, f16]
  unfold decodeBlock38
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, f15, f16]
  decode_finish
  try simp only [runSail_bind_of_eq (runSail_currentlyEnabled_M h),
    runSail_bind_of_eq (runSail_currentlyEnabled_Zmmul h)]
  try decode_finish

end FlapjackRiscvCheck
