import FlapjackRiscvCheck.Decode.Basic
import FlapjackRiscvCheck.Decode.Encoding
import FlapjackRiscvCheck.Decode.Imm

/-! GENERATED by scripts/gen-decode-proofs.py. Sail decodes the L3 encodings of the
tier-1 RType instructions to the Sail ASTs `toSail` assigns them. -/

namespace FlapjackRiscvCheck

open LeanRV64D LeanRV64D.Functions Flapjack.RiscV.L3

set_option maxRecDepth 100000

theorem dec_add {t} (h : DecodeInv t) (rd rs1 rs2 : BitVec 5) (hrd : rd ≠ 0) :
    runSail (encdec_backwards (Encode (.ArithR (.ADD (rd, rs1, rs2))))) t = some (.RTYPE (.Regidx rs2, .Regidx rs1, .Regidx rd, .ADD), t) := by
  obtain ⟨tail, htail⟩ := encdec_backwards_prefix
  rw [htail]
  have hw := enc_add rd rs1 rs2
  generalize Encode _ = w at hw ⊢
  have := rd.isLt; have := rs1.isLt; have := rs2.isLt
  have : rd.toNat ≠ 0 := fun e => hrd (BitVec.eq_of_toNat_eq e)
  have f0 : Sail.BitVec.extractLsb w 6 0 = 51#7 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f1 : Sail.BitVec.extractLsb w 11 7 = rd :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f2 : Sail.BitVec.extractLsb w 12 12 = 0#1 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f3 : Sail.BitVec.extractLsb w 13 12 = 0#2 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f4 : Sail.BitVec.extractLsb w 14 12 = 0#3 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f5 : Sail.BitVec.extractLsb w 14 13 = 0#2 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f6 : Sail.BitVec.extractLsb w 14 14 = 0#1 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f7 : Sail.BitVec.extractLsb w 19 15 = rs1 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f8 : Sail.BitVec.extractLsb w 24 20 = rs2 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f9 : Sail.BitVec.extractLsb w 25 25 = 0#1 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f10 : Sail.BitVec.extractLsb w 26 26 = 0#1 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f11 : Sail.BitVec.extractLsb w 30 25 = 0#6 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f12 : Sail.BitVec.extractLsb w 31 25 = 0#7 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f13 : Sail.BitVec.extractLsb w 31 26 = 0#6 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f14 : Sail.BitVec.extractLsb w 31 27 = 0#5 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f15 : Sail.BitVec.extractLsb w 31 28 = 0#4 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f16 : Sail.BitVec.extractLsb w 31 31 = 0#1 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  unfold decodePrefix
  unfold decodeBlock1
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, f15, f16]
  unfold decodeBlock2
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, f15, f16]
  unfold decodeBlock3
  simp only [runSail_bind_of_eq (runSail_currentlyEnabled_pause t)]
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, f15, f16]
  simp only [runSail_bind_of_eq (runSail_currentlyEnabled_zicfilp h)]
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, f15, f16]
  unfold decodeBlock4
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, f15, f16]
  unfold decodeBlock5
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, f15, f16]
  unfold decodeBlock6
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, f15, f16]
  unfold decodeBlock7
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, f15, f16]
  unfold decodeBlock8
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, f15, f16]
  unfold decodeBlock9
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, f15, f16]
  unfold decodeBlock10
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, f15, f16]
  unfold decodeBlock11
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, f15, f16]
  decode_finish

theorem dec_sub {t} (h : DecodeInv t) (rd rs1 rs2 : BitVec 5)  :
    runSail (encdec_backwards (Encode (.ArithR (.SUB (rd, rs1, rs2))))) t = some (.RTYPE (.Regidx rs2, .Regidx rs1, .Regidx rd, .SUB), t) := by
  obtain ⟨tail, htail⟩ := encdec_backwards_prefix
  rw [htail]
  have hw := enc_sub rd rs1 rs2
  generalize Encode _ = w at hw ⊢
  have := rd.isLt; have := rs1.isLt; have := rs2.isLt
  have f0 : Sail.BitVec.extractLsb w 6 0 = 51#7 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f1 : Sail.BitVec.extractLsb w 11 7 = rd :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f2 : Sail.BitVec.extractLsb w 12 12 = 0#1 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f3 : Sail.BitVec.extractLsb w 13 12 = 0#2 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f4 : Sail.BitVec.extractLsb w 14 12 = 0#3 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f5 : Sail.BitVec.extractLsb w 14 13 = 0#2 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f6 : Sail.BitVec.extractLsb w 14 14 = 0#1 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f7 : Sail.BitVec.extractLsb w 19 15 = rs1 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f8 : Sail.BitVec.extractLsb w 24 20 = rs2 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f9 : Sail.BitVec.extractLsb w 25 25 = 0#1 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f10 : Sail.BitVec.extractLsb w 26 26 = 0#1 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f11 : Sail.BitVec.extractLsb w 30 25 = 32#6 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f12 : Sail.BitVec.extractLsb w 31 25 = 32#7 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f13 : Sail.BitVec.extractLsb w 31 26 = 16#6 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f14 : Sail.BitVec.extractLsb w 31 27 = 8#5 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f15 : Sail.BitVec.extractLsb w 31 28 = 4#4 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f16 : Sail.BitVec.extractLsb w 31 31 = 0#1 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  unfold decodePrefix
  unfold decodeBlock1
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, f15, f16]
  unfold decodeBlock2
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, f15, f16]
  unfold decodeBlock3
  simp only [runSail_bind_of_eq (runSail_currentlyEnabled_pause t)]
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, f15, f16]
  simp only [runSail_bind_of_eq (runSail_currentlyEnabled_zicfilp h)]
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, f15, f16]
  unfold decodeBlock4
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, f15, f16]
  unfold decodeBlock5
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, f15, f16]
  unfold decodeBlock6
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, f15, f16]
  unfold decodeBlock7
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, f15, f16]
  unfold decodeBlock8
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, f15, f16]
  unfold decodeBlock9
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, f15, f16]
  unfold decodeBlock10
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, f15, f16]
  unfold decodeBlock11
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, f15, f16]
  unfold decodeBlock12
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, f15, f16]
  unfold decodeBlock13
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, f15, f16]
  unfold decodeBlock14
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, f15, f16]
  unfold decodeBlock15
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, f15, f16]
  unfold decodeBlock16
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, f15, f16]
  unfold decodeBlock17
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, f15, f16]
  unfold decodeBlock18
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, f15, f16]
  unfold decodeBlock19
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, f15, f16]
  decode_finish

theorem dec_and {t} (h : DecodeInv t) (rd rs1 rs2 : BitVec 5)  :
    runSail (encdec_backwards (Encode (.ArithR (.AND (rd, rs1, rs2))))) t = some (.RTYPE (.Regidx rs2, .Regidx rs1, .Regidx rd, .AND), t) := by
  obtain ⟨tail, htail⟩ := encdec_backwards_prefix
  rw [htail]
  have hw := enc_and rd rs1 rs2
  generalize Encode _ = w at hw ⊢
  have := rd.isLt; have := rs1.isLt; have := rs2.isLt
  have f0 : Sail.BitVec.extractLsb w 6 0 = 51#7 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f1 : Sail.BitVec.extractLsb w 11 7 = rd :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f2 : Sail.BitVec.extractLsb w 12 12 = 1#1 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f3 : Sail.BitVec.extractLsb w 13 12 = 3#2 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f4 : Sail.BitVec.extractLsb w 14 12 = 7#3 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f5 : Sail.BitVec.extractLsb w 14 13 = 3#2 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f6 : Sail.BitVec.extractLsb w 14 14 = 1#1 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f7 : Sail.BitVec.extractLsb w 19 15 = rs1 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f8 : Sail.BitVec.extractLsb w 24 20 = rs2 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f9 : Sail.BitVec.extractLsb w 25 25 = 0#1 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f10 : Sail.BitVec.extractLsb w 26 26 = 0#1 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f11 : Sail.BitVec.extractLsb w 30 25 = 0#6 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f12 : Sail.BitVec.extractLsb w 31 25 = 0#7 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f13 : Sail.BitVec.extractLsb w 31 26 = 0#6 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f14 : Sail.BitVec.extractLsb w 31 27 = 0#5 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f15 : Sail.BitVec.extractLsb w 31 28 = 0#4 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f16 : Sail.BitVec.extractLsb w 31 31 = 0#1 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  unfold decodePrefix
  unfold decodeBlock1
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, f15, f16]
  unfold decodeBlock2
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, f15, f16]
  unfold decodeBlock3
  simp only [runSail_bind_of_eq (runSail_currentlyEnabled_pause t)]
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, f15, f16]
  simp only [runSail_bind_of_eq (runSail_currentlyEnabled_zicfilp h)]
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, f15, f16]
  unfold decodeBlock4
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, f15, f16]
  unfold decodeBlock5
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, f15, f16]
  unfold decodeBlock6
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, f15, f16]
  unfold decodeBlock7
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, f15, f16]
  unfold decodeBlock8
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, f15, f16]
  unfold decodeBlock9
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, f15, f16]
  unfold decodeBlock10
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, f15, f16]
  unfold decodeBlock11
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, f15, f16]
  unfold decodeBlock12
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, f15, f16]
  unfold decodeBlock13
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, f15, f16]
  unfold decodeBlock14
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, f15, f16]
  decode_finish

theorem dec_or {t} (h : DecodeInv t) (rd rs1 rs2 : BitVec 5)  :
    runSail (encdec_backwards (Encode (.ArithR (.OR (rd, rs1, rs2))))) t = some (.RTYPE (.Regidx rs2, .Regidx rs1, .Regidx rd, .OR), t) := by
  obtain ⟨tail, htail⟩ := encdec_backwards_prefix
  rw [htail]
  have hw := enc_or rd rs1 rs2
  generalize Encode _ = w at hw ⊢
  have := rd.isLt; have := rs1.isLt; have := rs2.isLt
  have f0 : Sail.BitVec.extractLsb w 6 0 = 51#7 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f1 : Sail.BitVec.extractLsb w 11 7 = rd :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f2 : Sail.BitVec.extractLsb w 12 12 = 0#1 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f3 : Sail.BitVec.extractLsb w 13 12 = 2#2 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f4 : Sail.BitVec.extractLsb w 14 12 = 6#3 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f5 : Sail.BitVec.extractLsb w 14 13 = 3#2 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f6 : Sail.BitVec.extractLsb w 14 14 = 1#1 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f7 : Sail.BitVec.extractLsb w 19 15 = rs1 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f8 : Sail.BitVec.extractLsb w 24 20 = rs2 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f9 : Sail.BitVec.extractLsb w 25 25 = 0#1 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f10 : Sail.BitVec.extractLsb w 26 26 = 0#1 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f11 : Sail.BitVec.extractLsb w 30 25 = 0#6 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f12 : Sail.BitVec.extractLsb w 31 25 = 0#7 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f13 : Sail.BitVec.extractLsb w 31 26 = 0#6 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f14 : Sail.BitVec.extractLsb w 31 27 = 0#5 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f15 : Sail.BitVec.extractLsb w 31 28 = 0#4 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f16 : Sail.BitVec.extractLsb w 31 31 = 0#1 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  unfold decodePrefix
  unfold decodeBlock1
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, f15, f16]
  unfold decodeBlock2
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, f15, f16]
  unfold decodeBlock3
  simp only [runSail_bind_of_eq (runSail_currentlyEnabled_pause t)]
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, f15, f16]
  simp only [runSail_bind_of_eq (runSail_currentlyEnabled_zicfilp h)]
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, f15, f16]
  unfold decodeBlock4
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, f15, f16]
  unfold decodeBlock5
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, f15, f16]
  unfold decodeBlock6
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, f15, f16]
  unfold decodeBlock7
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, f15, f16]
  unfold decodeBlock8
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, f15, f16]
  unfold decodeBlock9
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, f15, f16]
  unfold decodeBlock10
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, f15, f16]
  unfold decodeBlock11
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, f15, f16]
  unfold decodeBlock12
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, f15, f16]
  unfold decodeBlock13
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, f15, f16]
  unfold decodeBlock14
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, f15, f16]
  unfold decodeBlock15
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, f15, f16]
  decode_finish

theorem dec_xor {t} (h : DecodeInv t) (rd rs1 rs2 : BitVec 5)  :
    runSail (encdec_backwards (Encode (.ArithR (.XOR (rd, rs1, rs2))))) t = some (.RTYPE (.Regidx rs2, .Regidx rs1, .Regidx rd, .XOR), t) := by
  obtain ⟨tail, htail⟩ := encdec_backwards_prefix
  rw [htail]
  have hw := enc_xor rd rs1 rs2
  generalize Encode _ = w at hw ⊢
  have := rd.isLt; have := rs1.isLt; have := rs2.isLt
  have f0 : Sail.BitVec.extractLsb w 6 0 = 51#7 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f1 : Sail.BitVec.extractLsb w 11 7 = rd :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f2 : Sail.BitVec.extractLsb w 12 12 = 0#1 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f3 : Sail.BitVec.extractLsb w 13 12 = 0#2 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f4 : Sail.BitVec.extractLsb w 14 12 = 4#3 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f5 : Sail.BitVec.extractLsb w 14 13 = 2#2 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f6 : Sail.BitVec.extractLsb w 14 14 = 1#1 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f7 : Sail.BitVec.extractLsb w 19 15 = rs1 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f8 : Sail.BitVec.extractLsb w 24 20 = rs2 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f9 : Sail.BitVec.extractLsb w 25 25 = 0#1 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f10 : Sail.BitVec.extractLsb w 26 26 = 0#1 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f11 : Sail.BitVec.extractLsb w 30 25 = 0#6 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f12 : Sail.BitVec.extractLsb w 31 25 = 0#7 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f13 : Sail.BitVec.extractLsb w 31 26 = 0#6 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f14 : Sail.BitVec.extractLsb w 31 27 = 0#5 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f15 : Sail.BitVec.extractLsb w 31 28 = 0#4 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f16 : Sail.BitVec.extractLsb w 31 31 = 0#1 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  unfold decodePrefix
  unfold decodeBlock1
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, f15, f16]
  unfold decodeBlock2
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, f15, f16]
  unfold decodeBlock3
  simp only [runSail_bind_of_eq (runSail_currentlyEnabled_pause t)]
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, f15, f16]
  simp only [runSail_bind_of_eq (runSail_currentlyEnabled_zicfilp h)]
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, f15, f16]
  unfold decodeBlock4
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, f15, f16]
  unfold decodeBlock5
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, f15, f16]
  unfold decodeBlock6
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, f15, f16]
  unfold decodeBlock7
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, f15, f16]
  unfold decodeBlock8
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, f15, f16]
  unfold decodeBlock9
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, f15, f16]
  unfold decodeBlock10
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, f15, f16]
  unfold decodeBlock11
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, f15, f16]
  unfold decodeBlock12
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, f15, f16]
  unfold decodeBlock13
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, f15, f16]
  unfold decodeBlock14
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, f15, f16]
  unfold decodeBlock15
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, f15, f16]
  unfold decodeBlock16
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, f15, f16]
  decode_finish

theorem dec_sltu {t} (h : DecodeInv t) (rd rs1 rs2 : BitVec 5)  :
    runSail (encdec_backwards (Encode (.ArithR (.SLTU (rd, rs1, rs2))))) t = some (.RTYPE (.Regidx rs2, .Regidx rs1, .Regidx rd, .SLTU), t) := by
  obtain ⟨tail, htail⟩ := encdec_backwards_prefix
  rw [htail]
  have hw := enc_sltu rd rs1 rs2
  generalize Encode _ = w at hw ⊢
  have := rd.isLt; have := rs1.isLt; have := rs2.isLt
  have f0 : Sail.BitVec.extractLsb w 6 0 = 51#7 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f1 : Sail.BitVec.extractLsb w 11 7 = rd :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f2 : Sail.BitVec.extractLsb w 12 12 = 1#1 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f3 : Sail.BitVec.extractLsb w 13 12 = 3#2 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f4 : Sail.BitVec.extractLsb w 14 12 = 3#3 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f5 : Sail.BitVec.extractLsb w 14 13 = 1#2 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f6 : Sail.BitVec.extractLsb w 14 14 = 0#1 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f7 : Sail.BitVec.extractLsb w 19 15 = rs1 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f8 : Sail.BitVec.extractLsb w 24 20 = rs2 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f9 : Sail.BitVec.extractLsb w 25 25 = 0#1 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f10 : Sail.BitVec.extractLsb w 26 26 = 0#1 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f11 : Sail.BitVec.extractLsb w 30 25 = 0#6 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f12 : Sail.BitVec.extractLsb w 31 25 = 0#7 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f13 : Sail.BitVec.extractLsb w 31 26 = 0#6 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f14 : Sail.BitVec.extractLsb w 31 27 = 0#5 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f15 : Sail.BitVec.extractLsb w 31 28 = 0#4 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f16 : Sail.BitVec.extractLsb w 31 31 = 0#1 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  unfold decodePrefix
  unfold decodeBlock1
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, f15, f16]
  unfold decodeBlock2
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, f15, f16]
  unfold decodeBlock3
  simp only [runSail_bind_of_eq (runSail_currentlyEnabled_pause t)]
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, f15, f16]
  simp only [runSail_bind_of_eq (runSail_currentlyEnabled_zicfilp h)]
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, f15, f16]
  unfold decodeBlock4
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, f15, f16]
  unfold decodeBlock5
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, f15, f16]
  unfold decodeBlock6
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, f15, f16]
  unfold decodeBlock7
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, f15, f16]
  unfold decodeBlock8
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, f15, f16]
  unfold decodeBlock9
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, f15, f16]
  unfold decodeBlock10
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, f15, f16]
  unfold decodeBlock11
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, f15, f16]
  unfold decodeBlock12
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, f15, f16]
  unfold decodeBlock13
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, f15, f16]
  decode_finish

theorem dec_sll {t} (h : DecodeInv t) (rd rs1 rs2 : BitVec 5)  :
    runSail (encdec_backwards (Encode (.Shift (.SLL (rd, rs1, rs2))))) t = some (.RTYPE (.Regidx rs2, .Regidx rs1, .Regidx rd, .SLL), t) := by
  obtain ⟨tail, htail⟩ := encdec_backwards_prefix
  rw [htail]
  have hw := enc_sll rd rs1 rs2
  generalize Encode _ = w at hw ⊢
  have := rd.isLt; have := rs1.isLt; have := rs2.isLt
  have f0 : Sail.BitVec.extractLsb w 6 0 = 51#7 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f1 : Sail.BitVec.extractLsb w 11 7 = rd :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f2 : Sail.BitVec.extractLsb w 12 12 = 1#1 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f3 : Sail.BitVec.extractLsb w 13 12 = 1#2 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f4 : Sail.BitVec.extractLsb w 14 12 = 1#3 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f5 : Sail.BitVec.extractLsb w 14 13 = 0#2 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f6 : Sail.BitVec.extractLsb w 14 14 = 0#1 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f7 : Sail.BitVec.extractLsb w 19 15 = rs1 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f8 : Sail.BitVec.extractLsb w 24 20 = rs2 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f9 : Sail.BitVec.extractLsb w 25 25 = 0#1 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f10 : Sail.BitVec.extractLsb w 26 26 = 0#1 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f11 : Sail.BitVec.extractLsb w 30 25 = 0#6 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f12 : Sail.BitVec.extractLsb w 31 25 = 0#7 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f13 : Sail.BitVec.extractLsb w 31 26 = 0#6 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f14 : Sail.BitVec.extractLsb w 31 27 = 0#5 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f15 : Sail.BitVec.extractLsb w 31 28 = 0#4 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f16 : Sail.BitVec.extractLsb w 31 31 = 0#1 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  unfold decodePrefix
  unfold decodeBlock1
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, f15, f16]
  unfold decodeBlock2
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, f15, f16]
  unfold decodeBlock3
  simp only [runSail_bind_of_eq (runSail_currentlyEnabled_pause t)]
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, f15, f16]
  simp only [runSail_bind_of_eq (runSail_currentlyEnabled_zicfilp h)]
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, f15, f16]
  unfold decodeBlock4
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, f15, f16]
  unfold decodeBlock5
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, f15, f16]
  unfold decodeBlock6
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, f15, f16]
  unfold decodeBlock7
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, f15, f16]
  unfold decodeBlock8
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, f15, f16]
  unfold decodeBlock9
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, f15, f16]
  unfold decodeBlock10
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, f15, f16]
  unfold decodeBlock11
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, f15, f16]
  unfold decodeBlock12
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, f15, f16]
  unfold decodeBlock13
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, f15, f16]
  unfold decodeBlock14
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, f15, f16]
  unfold decodeBlock15
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, f15, f16]
  unfold decodeBlock16
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, f15, f16]
  unfold decodeBlock17
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, f15, f16]
  decode_finish

theorem dec_srl {t} (h : DecodeInv t) (rd rs1 rs2 : BitVec 5)  :
    runSail (encdec_backwards (Encode (.Shift (.SRL (rd, rs1, rs2))))) t = some (.RTYPE (.Regidx rs2, .Regidx rs1, .Regidx rd, .SRL), t) := by
  obtain ⟨tail, htail⟩ := encdec_backwards_prefix
  rw [htail]
  have hw := enc_srl rd rs1 rs2
  generalize Encode _ = w at hw ⊢
  have := rd.isLt; have := rs1.isLt; have := rs2.isLt
  have f0 : Sail.BitVec.extractLsb w 6 0 = 51#7 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f1 : Sail.BitVec.extractLsb w 11 7 = rd :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f2 : Sail.BitVec.extractLsb w 12 12 = 1#1 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f3 : Sail.BitVec.extractLsb w 13 12 = 1#2 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f4 : Sail.BitVec.extractLsb w 14 12 = 5#3 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f5 : Sail.BitVec.extractLsb w 14 13 = 2#2 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f6 : Sail.BitVec.extractLsb w 14 14 = 1#1 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f7 : Sail.BitVec.extractLsb w 19 15 = rs1 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f8 : Sail.BitVec.extractLsb w 24 20 = rs2 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f9 : Sail.BitVec.extractLsb w 25 25 = 0#1 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f10 : Sail.BitVec.extractLsb w 26 26 = 0#1 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f11 : Sail.BitVec.extractLsb w 30 25 = 0#6 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f12 : Sail.BitVec.extractLsb w 31 25 = 0#7 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f13 : Sail.BitVec.extractLsb w 31 26 = 0#6 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f14 : Sail.BitVec.extractLsb w 31 27 = 0#5 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f15 : Sail.BitVec.extractLsb w 31 28 = 0#4 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f16 : Sail.BitVec.extractLsb w 31 31 = 0#1 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  unfold decodePrefix
  unfold decodeBlock1
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, f15, f16]
  unfold decodeBlock2
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, f15, f16]
  unfold decodeBlock3
  simp only [runSail_bind_of_eq (runSail_currentlyEnabled_pause t)]
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, f15, f16]
  simp only [runSail_bind_of_eq (runSail_currentlyEnabled_zicfilp h)]
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, f15, f16]
  unfold decodeBlock4
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, f15, f16]
  unfold decodeBlock5
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, f15, f16]
  unfold decodeBlock6
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, f15, f16]
  unfold decodeBlock7
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, f15, f16]
  unfold decodeBlock8
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, f15, f16]
  unfold decodeBlock9
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, f15, f16]
  unfold decodeBlock10
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, f15, f16]
  unfold decodeBlock11
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, f15, f16]
  unfold decodeBlock12
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, f15, f16]
  unfold decodeBlock13
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, f15, f16]
  unfold decodeBlock14
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, f15, f16]
  unfold decodeBlock15
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, f15, f16]
  unfold decodeBlock16
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, f15, f16]
  unfold decodeBlock17
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, f15, f16]
  unfold decodeBlock18
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, f15, f16]
  decode_finish

theorem dec_sra {t} (h : DecodeInv t) (rd rs1 rs2 : BitVec 5)  :
    runSail (encdec_backwards (Encode (.Shift (.SRA (rd, rs1, rs2))))) t = some (.RTYPE (.Regidx rs2, .Regidx rs1, .Regidx rd, .SRA), t) := by
  obtain ⟨tail, htail⟩ := encdec_backwards_prefix
  rw [htail]
  have hw := enc_sra rd rs1 rs2
  generalize Encode _ = w at hw ⊢
  have := rd.isLt; have := rs1.isLt; have := rs2.isLt
  have f0 : Sail.BitVec.extractLsb w 6 0 = 51#7 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f1 : Sail.BitVec.extractLsb w 11 7 = rd :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f2 : Sail.BitVec.extractLsb w 12 12 = 1#1 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f3 : Sail.BitVec.extractLsb w 13 12 = 1#2 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f4 : Sail.BitVec.extractLsb w 14 12 = 5#3 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f5 : Sail.BitVec.extractLsb w 14 13 = 2#2 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f6 : Sail.BitVec.extractLsb w 14 14 = 1#1 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f7 : Sail.BitVec.extractLsb w 19 15 = rs1 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f8 : Sail.BitVec.extractLsb w 24 20 = rs2 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f9 : Sail.BitVec.extractLsb w 25 25 = 0#1 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f10 : Sail.BitVec.extractLsb w 26 26 = 0#1 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f11 : Sail.BitVec.extractLsb w 30 25 = 32#6 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f12 : Sail.BitVec.extractLsb w 31 25 = 32#7 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f13 : Sail.BitVec.extractLsb w 31 26 = 16#6 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f14 : Sail.BitVec.extractLsb w 31 27 = 8#5 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f15 : Sail.BitVec.extractLsb w 31 28 = 4#4 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  have f16 : Sail.BitVec.extractLsb w 31 31 = 0#1 :=
    BitVec.eq_of_toNat_eq (by guard_omega hw)
  unfold decodePrefix
  unfold decodeBlock1
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, f15, f16]
  unfold decodeBlock2
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, f15, f16]
  unfold decodeBlock3
  simp only [runSail_bind_of_eq (runSail_currentlyEnabled_pause t)]
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, f15, f16]
  simp only [runSail_bind_of_eq (runSail_currentlyEnabled_zicfilp h)]
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, f15, f16]
  unfold decodeBlock4
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, f15, f16]
  unfold decodeBlock5
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, f15, f16]
  unfold decodeBlock6
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, f15, f16]
  unfold decodeBlock7
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, f15, f16]
  unfold decodeBlock8
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, f15, f16]
  unfold decodeBlock9
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, f15, f16]
  unfold decodeBlock10
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, f15, f16]
  unfold decodeBlock11
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, f15, f16]
  unfold decodeBlock12
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, f15, f16]
  unfold decodeBlock13
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, f15, f16]
  unfold decodeBlock14
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, f15, f16]
  unfold decodeBlock15
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, f15, f16]
  unfold decodeBlock16
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, f15, f16]
  unfold decodeBlock17
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, f15, f16]
  unfold decodeBlock18
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, f15, f16]
  unfold decodeBlock19
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, f15, f16]
  unfold decodeBlock20
  try guard_simp hw [f0, f1, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, f15, f16]
  decode_finish

end FlapjackRiscvCheck
