#!/usr/bin/env python3
"""Generate FlapjackRiscvCheck/Decode/Dispatch.lean from the instruction table in
gen-decode-proofs.py: the combined Sail/L3 decode theorems and encoding facts."""
import re
from pathlib import Path

root = Path(__file__).resolve().parent.parent
gen = (root / "scripts/gen-decode-proofs.py").read_text()
ns = {"__file__": str(root / "scripts/gen-decode-proofs.py")}
exec(gen.split("for fam, items in FAM.items():")[0], ns)
FAM = ns["FAM"]
COMPLETE = {"Store", "Branch"}  # groups whose constructors are all tier 1

def vars_(args):
    vs = []
    for part in args.split(")"):
        part = part.strip(" (")
        if ":" in part:
            vs += part.split(":")[0].split()
    return vs

items = [it for fam in FAM.values() for it in fam]

def cases(proof_of):
    lines = ["  cases i with"]
    groups = {}
    for (name, args, inst, ast, layout, block, hyp) in items:
        m = re.match(r"\.(\w+) \(\.(\w+) \((.*)\)\)", inst)
        groups.setdefault(m.group(1), []).append((m.group(2), m.group(3), name, args, hyp))
    for grp, lst in groups.items():
        lines += [f"  | {grp} a =>", "    cases a with"]
        for ctor, fields, name, args, hyp in lst:
            lines += [f"    | {ctor} x =>", f"      obtain ⟨{fields}⟩ := x", proof_of(name, args, hyp)]
        if grp not in COMPLETE:
            lines.append("    | _ => simp [toSail] at hi")
    lines.append("  | _ => simp [toSail] at hi")
    return lines

out = [
    "import FlapjackRiscvCheck.Decode.RType", "import FlapjackRiscvCheck.Decode.MulDiv",
    "import FlapjackRiscvCheck.Decode.IType", "import FlapjackRiscvCheck.Decode.Mem",
    "import FlapjackRiscvCheck.Decode.Control", "import FlapjackRiscvCheck.Exec.Dispatch",
] + [f"import Flapjack.RiscV.CorrectnessEncoding.{m}" for m in
     ["DecodeBinop", "DecodeShift", "DecodeBranches", "DecodeControl", "DecodeLongMul",
      "DecodeDiv", "DecodeMemory", "DecodeConst", "DecodeSltu", "DecodeAddi",
      "DecodeUpperImmediates"]] + ["", '''/-! GENERATED by scripts/gen-decode-dispatch.py.

For every tier-1 instruction `i` (`toSail i = some si`), both models decode the
L3 encoding `Encode i`: L3 to `i` (Flapjack's `decode_encode_*`), Sail to `si`.
`HintFree i` excludes the two encodings Sail reads as hints: `ADD x0, …`
(Zihintntl `NTL`) and `ORI x0, …` (Zicbop prefetch). -/

namespace FlapjackRiscvCheck

open LeanRV64D LeanRV64D.Functions Flapjack.RiscV.L3

/-- Not one of the encodings Sail decodes as a hint instead. -/
def HintFree : Flapjack.RiscV.L3.instruction → Prop
  | .ArithR (.ADD (rd, _, _)) => rd ≠ 0
  | .ArithI (.ORI (rd, _, _)) => rd ≠ 0
  | _ => True
''', '''theorem sail_decode_sim {t : SailState} (h : DecodeInv t) (i : Flapjack.RiscV.L3.instruction)
    (si : LeanRV64D.instruction) (hi : toSail i = some si) (hh : HintFree i) :
    runSail (ext_decode (Encode i)) t = some (si, t) := by
  unfold ext_decode''']
out += cases(lambda n, a, h: "      simp only [toSail, Option.some.injEq] at hi; subst hi\n"
             f"      exact dec_{n} h {' '.join(vars_(a))}{' hh' if h else ''}")
out.append('''
theorem l3_decode_sim (i : Flapjack.RiscV.L3.instruction) (si : LeanRV64D.instruction)
    (hi : toSail i = some si) : Step.DecodeAny (.Word (Encode i)) = i := by''')
out += cases(lambda n, a, h: f"      exact decode_encode_{n} {' '.join(vars_(a))}")
out.append('''
theorem encode_low_bits (i : Flapjack.RiscV.L3.instruction) (si : LeanRV64D.instruction)
    (hi : toSail i = some si) : (Encode i).toNat % 4 = 3 := by''')
out += cases(lambda n, a, h: f"      rw [enc_{n} {' '.join(vars_(a))}]\n      omega")
out.append("\nend FlapjackRiscvCheck\n")
(root / "FlapjackRiscvCheck/Decode/Dispatch.lean").write_text("\n".join(out))
