#!/usr/bin/env python3
"""Generate FlapjackRiscvCheck/Sail/DecodePrefixDef.lean.

Sail's `encdec_backwards` (LeanRV64D/InstsEnd.lean) is a ~56k-line chain

    match (← block_1) with | .some result => (pure result) | none => (do match (← block_2) ...

This script copies the first K blocks verbatim, each as its own definition
`decodeBlock<k> : BitVec 32 → SailM (Option instruction)`, and chains them in
`decodePrefix tail`, whose final `none` continuation is `tail`.
`DecodePrefix.lean` proves `encdec_backwards = decodePrefix tail` for some
`tail` by `rfl`, so decode proofs handle one small block at a time.
"""
import re, sys
from pathlib import Path

K = int(sys.argv[1]) if len(sys.argv) > 1 else 41
root = Path(__file__).resolve().parent.parent
src = root / ".lake/packages/Lean_RV64D/LeanRV64D/InstsEnd.lean"
lines = src.read_text().splitlines()

start = next(i for i, l in enumerate(lines)
             if l.startswith("noncomputable def encdec_backwards (arg_ : (BitVec 32))"))
first_open = next(i for i, l in enumerate(lines) if l.startswith("open "))
context = [l for l in lines[first_open:start] if l.strip()]

blocks = []
i = start
for k in range(K):
    ind_k = " " * (2 + 4 * k)
    m = next(j for j in range(i, len(lines)) if lines[j] == ind_k + "match (← do")
    s = next(j for j in range(m, len(lines)) if lines[j].startswith(ind_k + "| .some result =>"))
    body = lines[m + 1:s]
    assert body[-1].endswith(") with"), body[-1]
    body[-1] = body[-1][: -len(") with")]
    ind = min(len(l) - len(l.lstrip()) for l in body if l.strip())
    blocks.append([l[ind:] if l.strip() else l for l in body])
    i = s + 1

out = ["import LeanRV64D.InstsEnd", "",
       "/-! GENERATED by scripts/gen-decode-prefix.py from LeanRV64D/InstsEnd.lean.",
       f"The first {K} pattern blocks of Sail's `encdec_backwards`, verbatim, one",
       "definition per block. Do not edit by hand. -/", "",
       "set_option maxRecDepth 100000", "set_option linter.all false", ""]
out += context
out.append("")
for k, b in enumerate(blocks, 1):
    out.append(f"/-- Block {k} of `encdec_backwards`, passing its result to the continuation `jp`. -/")
    out.append(f"def _root_.FlapjackRiscvCheck.decodeBlock{k} (jp : Option instruction → SailM instruction)")
    out.append("    (head_exp_ : BitVec 32) : SailM instruction := do")
    out.append("  match (← do")
    out += ["    " + l if l.strip() else l for l in b]
    out[-1] += ") with"
    out.append("  | r => jp r")
    out.append("")

def chain(k):
    if k > K:
        return "tail head_exp_"
    return (f"FlapjackRiscvCheck.decodeBlock{k} (fun r => match r with\n"
            f"    | .some result => pure result\n"
            f"    | none => {chain(k + 1)}) head_exp_")

out.append("/-- The first blocks of `encdec_backwards`, continuing with `tail` when none match. -/")
out.append("def _root_.FlapjackRiscvCheck.decodePrefix (tail : BitVec 32 → SailM instruction)")
out.append("    (head_exp_ : BitVec 32) : SailM instruction :=")
out.append("  " + chain(1))
out += ["", "end Functions", "end LeanRV64D", "end"]
(root / "FlapjackRiscvCheck/Sail/DecodePrefixDef.lean").write_text("\n".join(out) + "\n")
print(f"{K} blocks, last ends at InstsEnd line {i}")
