import LeanRV64D.InstsEnd

/-! GENERATED by scripts/gen-decode-prefix.py from LeanRV64D/InstsEnd.lean.
The first 41 pattern blocks of Sail's `encdec_backwards`, verbatim, one
definition per block. Do not edit by hand. -/

set_option maxRecDepth 100000
set_option linter.all false

open Sail
open Sail.ConcurrencyInterfaceV1
noncomputable section
namespace LeanRV64D
open ConcurrencyInterfaceV1
namespace Functions
open zvk_vsm4r_funct6
open zvk_vsha2_funct6
open zvk_vaesem_funct6
open zvk_vaesef_funct6
open zvk_vaesdm_funct6
open zvk_vaesdf_funct6
open zvabd_vwabda_func6
open zvabd_vabd_func6
open zicondop
open xRET_type
open wxfunct6
open wvxfunct6
open wvvfunct6
open wvfunct6
open wrsop
open write_kind
open wmvxfunct6
open wmvvfunct6
open vxsgfunct6
open vxmsfunct6
open vxmfunct6
open vxmcfunct6
open vxfunct6
open vxcmpfunct6
open vvmsfunct6
open vvmfunct6
open vvmcfunct6
open vvfunct6
open vvcmpfunct6
open vstart_class
open vregno
open vregidx
open vmlsop
open vlewidth
open visgfunct6
open virtaddr
open vimsfunct6
open vimfunct6
open vimcfunct6
open vifunct6
open vicmpfunct6
open vfwunary0
open vfunary1
open vfunary0
open vfnunary0
open vextfunct6
open vector_support
open uop
open stateen_bit
open sopw
open sop
open seed_opst
open rounding_mode
open ropw
open rop
open rmvvfunct6
open rivvfunct6
open rfwvvfunct6
open rfvvfunct6
open regno
open regidx
open read_kind
open pte_check_failure
open pmpAddrMatch
open physaddr
open page_based_mem_type
open option
open nxsfunct6
open nxfunct6
open nvsfunct6
open nvfunct6
open ntl_type
open nisfunct6
open nifunct6
open mvxmafunct6
open mvxfunct6
open mvvmafunct6
open mvvfunct6
open mmfunct6
open misaligned_exception
open mem_payload
open maskfunct3
open landing_pad_expectation
open iop
open instruction
open indexed_mop
open fwvvmafunct6
open fwvvfunct6
open fwvfunct6
open fwvfmafunct6
open fwvffunct6
open fwffunct6
open fvvmfunct6
open fvvmafunct6
open fvvfunct6
open fvfmfunct6
open fvfmafunct6
open fvffunct6
open fregno
open fregidx
open float_class
open f_un_x_op_H
open f_un_x_op_D
open f_un_rm_xf_op_S
open f_un_rm_xf_op_H
open f_un_rm_xf_op_D
open f_un_rm_fx_op_S
open f_un_rm_fx_op_H
open f_un_rm_fx_op_D
open f_un_rm_ff_op_S
open f_un_rm_ff_op_H
open f_un_rm_ff_op_D
open f_un_op_x_S
open f_un_op_f_S
open f_un_f_op_H
open f_un_f_op_D
open f_madd_op_S
open f_madd_op_H
open f_madd_op_D
open f_bin_x_op_H
open f_bin_x_op_D
open f_bin_rm_op_S
open f_bin_rm_op_H
open f_bin_rm_op_D
open f_bin_op_x_S
open f_bin_op_f_S
open f_bin_f_op_H
open f_bin_f_op_D
open extop_zbb
open extension
open exception
open csrop
open cregidx
open checked_cbop
open cfregidx
open cbop_zicbop
open cbop_zicbom
open cbie
open cacheop
open bropw_zbb
open brop_zbs
open brop_zbkb
open brop_zbb
open breakpoint_cause
open bop
open biop_zbs
open biop
open barrier_kind
open amoop
open agtype
open XtvecModeReservedBehavior
open XipReadType
open XenvcfgCbieReservedBehavior
open WaitReason
open VectorHalf
open TrapVectorMode
open TrapCause
open Step
open Splittability
open Software_Check_Code
open Signedness
open SWCheckCodes
open SATPMode
open Reservability
open Register
open RV32ZdinxOddRegisterReservedBehavior
open Privileged_ISA_Version
open Privilege
open PointerMaskingMode
open PmpWriteOnlyReservedBehavior
open PmpAddrMatchType
open PTW_Error
open PTE_Check
open PM_Ext
open OOBVstartReservedBehavior
open MemoryRegionType
open MemoryAccessType
open InterruptType
open IllegalVtypeReservedBehavior
open ISA_Format
open HartState
open FflagsDirtyPolicy
open FetchResult
open FetchBytes_Result
open FeatureEnabledResult
open FcsrRmReservedBehavior
open Ext_DataAddr_Check
open ExtStatus
open ExtContextPolicy
open ExecutionResult
open ExceptionType
open CSRCheckResult
open CSRAccessType
open AtomicSupport
open Architecture
open AmocasOddRegisterReservedBehavior

/-- Block 1 of `encdec_backwards`, passing its result to the continuation `jp`. -/
def _root_.FlapjackRiscvCheck.decodeBlock1 (jp : Option instruction → SailM instruction)
    (head_exp_ : BitVec 32) : SailM instruction := do
  match (← do
    let v__1673 := head_exp_
    if (((let mapping1_ : (BitVec 5) := (Sail.BitVec.extractLsb v__1673 19 15)
         let mapping0_ : (BitVec 5) := (Sail.BitVec.extractLsb v__1673 24 20)
         ((encdec_cbop_zicbop_backwards_matches mapping0_) && (encdec_reg_backwards_matches
             mapping1_))) && ((Sail.BitVec.extractLsb v__1673 14 0) == (0b110000000010011#15 : (BitVec 15)))) : Bool)
    then
      (do
        let offset11_5 : (BitVec 7) := (Sail.BitVec.extractLsb v__1673 31 25)
        let offset11_5 : (BitVec 7) := (Sail.BitVec.extractLsb v__1673 31 25)
        let mapping1_ : (BitVec 5) := (Sail.BitVec.extractLsb v__1673 19 15)
        let mapping0_ : (BitVec 5) := (Sail.BitVec.extractLsb v__1673 24 20)
        match ((← (encdec_cbop_zicbop_backwards mapping0_)), (← (encdec_reg_backwards mapping1_))) with
        | (cbop, rs1) =>
          (do
            if ((← (currentlyEnabled Ext_Zicbop)) : Bool)
            then (pure (some (ZICBOP (cbop, rs1, ((offset11_5 : (BitVec 7)) +++ 0b00000#5)))))
            else (pure none)))
    else (pure none)) with
  | r => jp r

/-- Block 2 of `encdec_backwards`, passing its result to the continuation `jp`. -/
def _root_.FlapjackRiscvCheck.decodeBlock2 (jp : Option instruction → SailM instruction)
    (head_exp_ : BitVec 32) : SailM instruction := do
  match (← do
    let v__1667 := head_exp_
    if (((let mapping2_ : (BitVec 5) := (Sail.BitVec.extractLsb v__1667 24 20)
         (encdec_ntl_backwards_matches mapping2_)) && (((Sail.BitVec.extractLsb v__1667 31 25) == (0b0000000#7 : (BitVec 7))) && ((Sail.BitVec.extractLsb
               v__1667 19 0) == (0x00033#20 : (BitVec 20))))) : Bool)
    then
      (do
        let mapping2_ : (BitVec 5) := (Sail.BitVec.extractLsb v__1667 24 20)
        let op ← do (encdec_ntl_backwards mapping2_)
        if ((← (currentlyEnabled Ext_Zihintntl)) : Bool)
        then (pure (some (NTL op)))
        else (pure none))
    else (pure none)) with
  | r => jp r

/-- Block 3 of `encdec_backwards`, passing its result to the continuation `jp`. -/
def _root_.FlapjackRiscvCheck.decodeBlock3 (jp : Option instruction → SailM instruction)
    (head_exp_ : BitVec 32) : SailM instruction := do
  match (← do
    let v__1655 := head_exp_
    if (((← (currentlyEnabled Ext_Zihintpause)) && (v__1655 == (0x0100000F#32 : (BitVec 32)))) : Bool)
    then (pure (some (PAUSE ())))
    else
      (do
        if (((← (currentlyEnabled Ext_Zicfilp)) && ((Sail.BitVec.extractLsb v__1655 11 0) == (0x017#12 : (BitVec 12)))) : Bool)
        then
          (let lpl : (BitVec 20) := (Sail.BitVec.extractLsb v__1655 31 12)
          let lpl : (BitVec 20) := (Sail.BitVec.extractLsb v__1655 31 12)
          (pure (some (LPAD lpl))))
        else
          (do
            if ((let mapping4_ : (BitVec 7) := (Sail.BitVec.extractLsb v__1655 6 0)
               let mapping3_ : (BitVec 5) := (Sail.BitVec.extractLsb v__1655 11 7)
               ((encdec_reg_backwards_matches mapping3_) && (encdec_uop_backwards_matches
                   mapping4_))) : Bool)
            then
              (do
                let imm : (BitVec 20) := (Sail.BitVec.extractLsb v__1655 31 12)
                let mapping4_ : (BitVec 7) := (Sail.BitVec.extractLsb v__1655 6 0)
                let mapping3_ : (BitVec 5) := (Sail.BitVec.extractLsb v__1655 11 7)
                let imm : (BitVec 20) := (Sail.BitVec.extractLsb v__1655 31 12)
                match ((← (encdec_reg_backwards mapping3_)), (← (encdec_uop_backwards
                    mapping4_))) with
                | (rd, op) => (pure (some (UTYPE (imm, rd, op)))))
            else (pure none)))) with
  | r => jp r

/-- Block 4 of `encdec_backwards`, passing its result to the continuation `jp`. -/
def _root_.FlapjackRiscvCheck.decodeBlock4 (jp : Option instruction → SailM instruction)
    (head_exp_ : BitVec 32) : SailM instruction := do
  match (← do
    let v__1653 := head_exp_
    if (((let mapping5_ : (BitVec 5) := (Sail.BitVec.extractLsb v__1653 11 7)
         (encdec_reg_backwards_matches mapping5_)) && ((Sail.BitVec.extractLsb v__1653 6
             0) == (0b1101111#7 : (BitVec 7)))) : Bool)
    then
      (do
        let imm_19_19_ : (BitVec 1) := (Sail.BitVec.extractLsb v__1653 31 31)
        let mapping5_ : (BitVec 5) := (Sail.BitVec.extractLsb v__1653 11 7)
        let imm_9_0_ : (BitVec 10) := (Sail.BitVec.extractLsb v__1653 30 21)
        let imm_19_19_ : (BitVec 1) := (Sail.BitVec.extractLsb v__1653 31 31)
        let imm_18_11_ : (BitVec 8) := (Sail.BitVec.extractLsb v__1653 19 12)
        let imm_10_10_ : (BitVec 1) := (Sail.BitVec.extractLsb v__1653 20 20)
        match (← (encdec_reg_backwards mapping5_)) with
        | rd =>
          (pure (some
              (let imm := (((imm_19_19_ +++ imm_18_11_) +++ imm_10_10_) +++ imm_9_0_)
              (JAL ((imm +++ 0#1), rd))))))
    else (pure none)) with
  | r => jp r

/-- Block 5 of `encdec_backwards`, passing its result to the continuation `jp`. -/
def _root_.FlapjackRiscvCheck.decodeBlock5 (jp : Option instruction → SailM instruction)
    (head_exp_ : BitVec 32) : SailM instruction := do
  match (← do
    let v__1650 := head_exp_
    if (((let mapping7_ : (BitVec 5) := (Sail.BitVec.extractLsb v__1650 11 7)
         let mapping6_ : (BitVec 5) := (Sail.BitVec.extractLsb v__1650 19 15)
         ((encdec_reg_backwards_matches mapping6_) && (encdec_reg_backwards_matches
             mapping7_))) && (((Sail.BitVec.extractLsb v__1650 14 12) == (0b000#3 : (BitVec 3))) && ((Sail.BitVec.extractLsb
               v__1650 6 0) == (0b1100111#7 : (BitVec 7))))) : Bool)
    then
      (do
        let imm : (BitVec 12) := (Sail.BitVec.extractLsb v__1650 31 20)
        let mapping7_ : (BitVec 5) := (Sail.BitVec.extractLsb v__1650 11 7)
        let mapping6_ : (BitVec 5) := (Sail.BitVec.extractLsb v__1650 19 15)
        let imm : (BitVec 12) := (Sail.BitVec.extractLsb v__1650 31 20)
        match ((← (encdec_reg_backwards mapping6_)), (← (encdec_reg_backwards
            mapping7_))) with
        | (rs1, rd) => (pure (some (JALR (imm, rs1, rd)))))
    else (pure none)) with
  | r => jp r

/-- Block 6 of `encdec_backwards`, passing its result to the continuation `jp`. -/
def _root_.FlapjackRiscvCheck.decodeBlock6 (jp : Option instruction → SailM instruction)
    (head_exp_ : BitVec 32) : SailM instruction := do
  match (← do
    let v__1648 := head_exp_
    if (((let mapping9_ : (BitVec 5) := (Sail.BitVec.extractLsb v__1648 19 15)
         let mapping8_ : (BitVec 5) := (Sail.BitVec.extractLsb v__1648 24 20)
         let mapping10_ : (BitVec 3) := (Sail.BitVec.extractLsb v__1648 14 12)
         ((encdec_reg_backwards_matches mapping8_) && ((encdec_reg_backwards_matches
               mapping9_) && (encdec_bop_backwards_matches mapping10_)))) && ((Sail.BitVec.extractLsb
             v__1648 6 0) == (0b1100011#7 : (BitVec 7)))) : Bool)
    then
      (do
        let imm_11_11_ : (BitVec 1) := (Sail.BitVec.extractLsb v__1648 31 31)
        let mapping9_ : (BitVec 5) := (Sail.BitVec.extractLsb v__1648 19 15)
        let mapping8_ : (BitVec 5) := (Sail.BitVec.extractLsb v__1648 24 20)
        let mapping10_ : (BitVec 3) := (Sail.BitVec.extractLsb v__1648 14 12)
        let imm_9_4_ : (BitVec 6) := (Sail.BitVec.extractLsb v__1648 30 25)
        let imm_3_0_ : (BitVec 4) := (Sail.BitVec.extractLsb v__1648 11 8)
        let imm_11_11_ : (BitVec 1) := (Sail.BitVec.extractLsb v__1648 31 31)
        let imm_10_10_ : (BitVec 1) := (Sail.BitVec.extractLsb v__1648 7 7)
        match ((← (encdec_reg_backwards mapping8_)), (← (encdec_reg_backwards
            mapping9_)), (← (encdec_bop_backwards mapping10_))) with
        | (rs2, rs1, op) =>
          (pure (some
              (let imm :=
                (((imm_11_11_ +++ imm_10_10_) +++ imm_9_4_) +++ imm_3_0_)
              (BTYPE ((imm +++ 0#1), rs2, rs1, op))))))
    else (pure none)) with
  | r => jp r

/-- Block 7 of `encdec_backwards`, passing its result to the continuation `jp`. -/
def _root_.FlapjackRiscvCheck.decodeBlock7 (jp : Option instruction → SailM instruction)
    (head_exp_ : BitVec 32) : SailM instruction := do
  match (← do
    let v__1646 := head_exp_
    if (((let mapping13_ : (BitVec 5) :=
           (Sail.BitVec.extractLsb v__1646 11 7)
         let mapping12_ : (BitVec 3) :=
           (Sail.BitVec.extractLsb v__1646 14 12)
         let mapping11_ : (BitVec 5) :=
           (Sail.BitVec.extractLsb v__1646 19 15)
         ((encdec_reg_backwards_matches mapping11_) && ((encdec_iop_backwards_matches
               mapping12_) && (encdec_reg_backwards_matches mapping13_)))) && ((Sail.BitVec.extractLsb
             v__1646 6 0) == (0b0010011#7 : (BitVec 7)))) : Bool)
    then
      (do
        let imm : (BitVec 12) := (Sail.BitVec.extractLsb v__1646 31 20)
        let mapping13_ : (BitVec 5) := (Sail.BitVec.extractLsb v__1646 11 7)
        let mapping12_ : (BitVec 3) :=
          (Sail.BitVec.extractLsb v__1646 14 12)
        let mapping11_ : (BitVec 5) :=
          (Sail.BitVec.extractLsb v__1646 19 15)
        let imm : (BitVec 12) := (Sail.BitVec.extractLsb v__1646 31 20)
        match ((← (encdec_reg_backwards mapping11_)), (← (encdec_iop_backwards
            mapping12_)), (← (encdec_reg_backwards mapping13_))) with
        | (rs1, op, rd) => (pure (some (ITYPE (imm, rs1, rd, op)))))
    else (pure none)) with
  | r => jp r

/-- Block 8 of `encdec_backwards`, passing its result to the continuation `jp`. -/
def _root_.FlapjackRiscvCheck.decodeBlock8 (jp : Option instruction → SailM instruction)
    (head_exp_ : BitVec 32) : SailM instruction := do
  match (← do
    let v__1642 := head_exp_
    if (((let mapping15_ : (BitVec 5) :=
           (Sail.BitVec.extractLsb v__1642 11 7)
         let mapping14_ : (BitVec 5) :=
           (Sail.BitVec.extractLsb v__1642 19 15)
         ((encdec_reg_backwards_matches mapping14_) && (encdec_reg_backwards_matches
             mapping15_))) && (((Sail.BitVec.extractLsb v__1642 31 26) == (0b000000#6 : (BitVec 6))) && (((Sail.BitVec.extractLsb
                 v__1642 14 12) == (0b001#3 : (BitVec 3))) && ((Sail.BitVec.extractLsb
                 v__1642 6 0) == (0b0010011#7 : (BitVec 7)))))) : Bool)
    then
      (do
        let shamt : (BitVec 6) := (Sail.BitVec.extractLsb v__1642 25 20)
        let mapping15_ : (BitVec 5) :=
          (Sail.BitVec.extractLsb v__1642 11 7)
        let mapping14_ : (BitVec 5) :=
          (Sail.BitVec.extractLsb v__1642 19 15)
        match ((← (encdec_reg_backwards mapping14_)), (← (encdec_reg_backwards
            mapping15_))) with
        | (rs1, rd) =>
          (if (((xlen == 64) || ((BitVec.access shamt 5) == 0#1)) : Bool)
          then (pure (some (SHIFTIOP (shamt, rs1, rd, SLLI))))
          else (pure none)))
    else (pure none)) with
  | r => jp r

/-- Block 9 of `encdec_backwards`, passing its result to the continuation `jp`. -/
def _root_.FlapjackRiscvCheck.decodeBlock9 (jp : Option instruction → SailM instruction)
    (head_exp_ : BitVec 32) : SailM instruction := do
  match (← do
    let v__1638 := head_exp_
    if (((let mapping17_ : (BitVec 5) :=
           (Sail.BitVec.extractLsb v__1638 11 7)
         let mapping16_ : (BitVec 5) :=
           (Sail.BitVec.extractLsb v__1638 19 15)
         ((encdec_reg_backwards_matches mapping16_) && (encdec_reg_backwards_matches
             mapping17_))) && (((Sail.BitVec.extractLsb v__1638 31
               26) == (0b000000#6 : (BitVec 6))) && (((Sail.BitVec.extractLsb
                 v__1638 14 12) == (0b101#3 : (BitVec 3))) && ((Sail.BitVec.extractLsb
                 v__1638 6 0) == (0b0010011#7 : (BitVec 7)))))) : Bool)
    then
      (do
        let shamt : (BitVec 6) :=
          (Sail.BitVec.extractLsb v__1638 25 20)
        let mapping17_ : (BitVec 5) :=
          (Sail.BitVec.extractLsb v__1638 11 7)
        let mapping16_ : (BitVec 5) :=
          (Sail.BitVec.extractLsb v__1638 19 15)
        match ((← (encdec_reg_backwards mapping16_)), (← (encdec_reg_backwards
            mapping17_))) with
        | (rs1, rd) =>
          (if (((xlen == 64) || ((BitVec.access shamt 5) == 0#1)) : Bool)
          then (pure (some (SHIFTIOP (shamt, rs1, rd, SRLI))))
          else (pure none)))
    else (pure none)) with
  | r => jp r

/-- Block 10 of `encdec_backwards`, passing its result to the continuation `jp`. -/
def _root_.FlapjackRiscvCheck.decodeBlock10 (jp : Option instruction → SailM instruction)
    (head_exp_ : BitVec 32) : SailM instruction := do
  match (← do
    let v__1634 := head_exp_
    if (((let mapping19_ : (BitVec 5) :=
           (Sail.BitVec.extractLsb v__1634 11 7)
         let mapping18_ : (BitVec 5) :=
           (Sail.BitVec.extractLsb v__1634 19 15)
         ((encdec_reg_backwards_matches mapping18_) && (encdec_reg_backwards_matches
             mapping19_))) && (((Sail.BitVec.extractLsb v__1634
               31 26) == (0b010000#6 : (BitVec 6))) && (((Sail.BitVec.extractLsb
                 v__1634 14 12) == (0b101#3 : (BitVec 3))) && ((Sail.BitVec.extractLsb
                 v__1634 6 0) == (0b0010011#7 : (BitVec 7)))))) : Bool)
    then
      (do
        let shamt : (BitVec 6) :=
          (Sail.BitVec.extractLsb v__1634 25 20)
        let mapping19_ : (BitVec 5) :=
          (Sail.BitVec.extractLsb v__1634 11 7)
        let mapping18_ : (BitVec 5) :=
          (Sail.BitVec.extractLsb v__1634 19 15)
        match ((← (encdec_reg_backwards mapping18_)), (← (encdec_reg_backwards
            mapping19_))) with
        | (rs1, rd) =>
          (if (((xlen == 64) || ((BitVec.access shamt 5) == 0#1)) : Bool)
          then (pure (some (SHIFTIOP (shamt, rs1, rd, SRAI))))
          else (pure none)))
    else (pure none)) with
  | r => jp r

/-- Block 11 of `encdec_backwards`, passing its result to the continuation `jp`. -/
def _root_.FlapjackRiscvCheck.decodeBlock11 (jp : Option instruction → SailM instruction)
    (head_exp_ : BitVec 32) : SailM instruction := do
  match (← do
    let v__1630 := head_exp_
    if (((let mapping22_ : (BitVec 5) :=
           (Sail.BitVec.extractLsb v__1630 11 7)
         let mapping21_ : (BitVec 5) :=
           (Sail.BitVec.extractLsb v__1630 19 15)
         let mapping20_ : (BitVec 5) :=
           (Sail.BitVec.extractLsb v__1630 24 20)
         ((encdec_reg_backwards_matches mapping20_) && ((encdec_reg_backwards_matches
               mapping21_) && (encdec_reg_backwards_matches
               mapping22_)))) && (((Sail.BitVec.extractLsb
               v__1630 31 25) == (0b0000000#7 : (BitVec 7))) && (((Sail.BitVec.extractLsb
                 v__1630 14 12) == (0b000#3 : (BitVec 3))) && ((Sail.BitVec.extractLsb
                 v__1630 6 0) == (0b0110011#7 : (BitVec 7)))))) : Bool)
    then
      (do
        let mapping22_ : (BitVec 5) :=
          (Sail.BitVec.extractLsb v__1630 11 7)
        let mapping21_ : (BitVec 5) :=
          (Sail.BitVec.extractLsb v__1630 19 15)
        let mapping20_ : (BitVec 5) :=
          (Sail.BitVec.extractLsb v__1630 24 20)
        match ((← (encdec_reg_backwards mapping20_)), (← (encdec_reg_backwards
            mapping21_)), (← (encdec_reg_backwards
            mapping22_))) with
        | (rs2, rs1, rd) =>
          (pure (some (RTYPE (rs2, rs1, rd, ADD)))))
    else (pure none)) with
  | r => jp r

/-- Block 12 of `encdec_backwards`, passing its result to the continuation `jp`. -/
def _root_.FlapjackRiscvCheck.decodeBlock12 (jp : Option instruction → SailM instruction)
    (head_exp_ : BitVec 32) : SailM instruction := do
  match (← do
    let v__1626 := head_exp_
    if (((let mapping25_ : (BitVec 5) :=
           (Sail.BitVec.extractLsb v__1626 11 7)
         let mapping24_ : (BitVec 5) :=
           (Sail.BitVec.extractLsb v__1626 19 15)
         let mapping23_ : (BitVec 5) :=
           (Sail.BitVec.extractLsb v__1626 24 20)
         ((encdec_reg_backwards_matches mapping23_) && ((encdec_reg_backwards_matches
               mapping24_) && (encdec_reg_backwards_matches
               mapping25_)))) && (((Sail.BitVec.extractLsb
               v__1626 31 25) == (0b0000000#7 : (BitVec 7))) && (((Sail.BitVec.extractLsb
                 v__1626 14 12) == (0b010#3 : (BitVec 3))) && ((Sail.BitVec.extractLsb
                 v__1626 6 0) == (0b0110011#7 : (BitVec 7)))))) : Bool)
    then
      (do
        let mapping25_ : (BitVec 5) :=
          (Sail.BitVec.extractLsb v__1626 11 7)
        let mapping24_ : (BitVec 5) :=
          (Sail.BitVec.extractLsb v__1626 19 15)
        let mapping23_ : (BitVec 5) :=
          (Sail.BitVec.extractLsb v__1626 24 20)
        match ((← (encdec_reg_backwards mapping23_)), (← (encdec_reg_backwards
            mapping24_)), (← (encdec_reg_backwards
            mapping25_))) with
        | (rs2, rs1, rd) =>
          (pure (some (RTYPE (rs2, rs1, rd, SLT)))))
    else (pure none)) with
  | r => jp r

/-- Block 13 of `encdec_backwards`, passing its result to the continuation `jp`. -/
def _root_.FlapjackRiscvCheck.decodeBlock13 (jp : Option instruction → SailM instruction)
    (head_exp_ : BitVec 32) : SailM instruction := do
  match (← do
    let v__1622 := head_exp_
    if (((let mapping28_ : (BitVec 5) :=
           (Sail.BitVec.extractLsb v__1622 11 7)
         let mapping27_ : (BitVec 5) :=
           (Sail.BitVec.extractLsb v__1622 19 15)
         let mapping26_ : (BitVec 5) :=
           (Sail.BitVec.extractLsb v__1622 24 20)
         ((encdec_reg_backwards_matches mapping26_) && ((encdec_reg_backwards_matches
               mapping27_) && (encdec_reg_backwards_matches
               mapping28_)))) && (((Sail.BitVec.extractLsb
               v__1622 31 25) == (0b0000000#7 : (BitVec 7))) && (((Sail.BitVec.extractLsb
                 v__1622 14 12) == (0b011#3 : (BitVec 3))) && ((Sail.BitVec.extractLsb
                 v__1622 6 0) == (0b0110011#7 : (BitVec 7)))))) : Bool)
    then
      (do
        let mapping28_ : (BitVec 5) :=
          (Sail.BitVec.extractLsb v__1622 11 7)
        let mapping27_ : (BitVec 5) :=
          (Sail.BitVec.extractLsb v__1622 19 15)
        let mapping26_ : (BitVec 5) :=
          (Sail.BitVec.extractLsb v__1622 24 20)
        match ((← (encdec_reg_backwards mapping26_)), (← (encdec_reg_backwards
            mapping27_)), (← (encdec_reg_backwards
            mapping28_))) with
        | (rs2, rs1, rd) =>
          (pure (some (RTYPE (rs2, rs1, rd, SLTU)))))
    else (pure none)) with
  | r => jp r

/-- Block 14 of `encdec_backwards`, passing its result to the continuation `jp`. -/
def _root_.FlapjackRiscvCheck.decodeBlock14 (jp : Option instruction → SailM instruction)
    (head_exp_ : BitVec 32) : SailM instruction := do
  match (← do
    let v__1618 := head_exp_
    if (((let mapping31_ : (BitVec 5) :=
           (Sail.BitVec.extractLsb v__1618 11 7)
         let mapping30_ : (BitVec 5) :=
           (Sail.BitVec.extractLsb v__1618 19 15)
         let mapping29_ : (BitVec 5) :=
           (Sail.BitVec.extractLsb v__1618 24 20)
         ((encdec_reg_backwards_matches
             mapping29_) && ((encdec_reg_backwards_matches
               mapping30_) && (encdec_reg_backwards_matches
               mapping31_)))) && (((Sail.BitVec.extractLsb
               v__1618 31 25) == (0b0000000#7 : (BitVec 7))) && (((Sail.BitVec.extractLsb
                 v__1618 14 12) == (0b111#3 : (BitVec 3))) && ((Sail.BitVec.extractLsb
                 v__1618 6 0) == (0b0110011#7 : (BitVec 7)))))) : Bool)
    then
      (do
        let mapping31_ : (BitVec 5) :=
          (Sail.BitVec.extractLsb v__1618 11 7)
        let mapping30_ : (BitVec 5) :=
          (Sail.BitVec.extractLsb v__1618 19 15)
        let mapping29_ : (BitVec 5) :=
          (Sail.BitVec.extractLsb v__1618 24 20)
        match ((← (encdec_reg_backwards
            mapping29_)), (← (encdec_reg_backwards
            mapping30_)), (← (encdec_reg_backwards
            mapping31_))) with
        | (rs2, rs1, rd) =>
          (pure (some
              (RTYPE (rs2, rs1, rd, AND)))))
    else (pure none)) with
  | r => jp r

/-- Block 15 of `encdec_backwards`, passing its result to the continuation `jp`. -/
def _root_.FlapjackRiscvCheck.decodeBlock15 (jp : Option instruction → SailM instruction)
    (head_exp_ : BitVec 32) : SailM instruction := do
  match (← do
    let v__1614 := head_exp_
    if (((let mapping34_ : (BitVec 5) :=
           (Sail.BitVec.extractLsb v__1614
             11 7)
         let mapping33_ : (BitVec 5) :=
           (Sail.BitVec.extractLsb v__1614
             19 15)
         let mapping32_ : (BitVec 5) :=
           (Sail.BitVec.extractLsb v__1614
             24 20)
         ((encdec_reg_backwards_matches
             mapping32_) && ((encdec_reg_backwards_matches
               mapping33_) && (encdec_reg_backwards_matches
               mapping34_)))) && (((Sail.BitVec.extractLsb
               v__1614 31 25) == (0b0000000#7 : (BitVec 7))) && (((Sail.BitVec.extractLsb
                 v__1614 14 12) == (0b110#3 : (BitVec 3))) && ((Sail.BitVec.extractLsb
                 v__1614 6 0) == (0b0110011#7 : (BitVec 7)))))) : Bool)
    then
      (do
        let mapping34_ : (BitVec 5) :=
          (Sail.BitVec.extractLsb v__1614 11
            7)
        let mapping33_ : (BitVec 5) :=
          (Sail.BitVec.extractLsb v__1614 19
            15)
        let mapping32_ : (BitVec 5) :=
          (Sail.BitVec.extractLsb v__1614 24
            20)
        match ((← (encdec_reg_backwards
            mapping32_)), (← (encdec_reg_backwards
            mapping33_)), (← (encdec_reg_backwards
            mapping34_))) with
        | (rs2, rs1, rd) =>
          (pure (some
              (RTYPE (rs2, rs1, rd, OR)))))
    else (pure none)) with
  | r => jp r

/-- Block 16 of `encdec_backwards`, passing its result to the continuation `jp`. -/
def _root_.FlapjackRiscvCheck.decodeBlock16 (jp : Option instruction → SailM instruction)
    (head_exp_ : BitVec 32) : SailM instruction := do
  match (← do
    let v__1610 := head_exp_
    if (((let mapping37_ : (BitVec 5) :=
           (Sail.BitVec.extractLsb
             v__1610 11 7)
         let mapping36_ : (BitVec 5) :=
           (Sail.BitVec.extractLsb
             v__1610 19 15)
         let mapping35_ : (BitVec 5) :=
           (Sail.BitVec.extractLsb
             v__1610 24 20)
         ((encdec_reg_backwards_matches
             mapping35_) && ((encdec_reg_backwards_matches
               mapping36_) && (encdec_reg_backwards_matches
               mapping37_)))) && (((Sail.BitVec.extractLsb
               v__1610 31 25) == (0b0000000#7 : (BitVec 7))) && (((Sail.BitVec.extractLsb
                 v__1610 14 12) == (0b100#3 : (BitVec 3))) && ((Sail.BitVec.extractLsb
                 v__1610 6 0) == (0b0110011#7 : (BitVec 7)))))) : Bool)
    then
      (do
        let mapping37_ : (BitVec 5) :=
          (Sail.BitVec.extractLsb
            v__1610 11 7)
        let mapping36_ : (BitVec 5) :=
          (Sail.BitVec.extractLsb
            v__1610 19 15)
        let mapping35_ : (BitVec 5) :=
          (Sail.BitVec.extractLsb
            v__1610 24 20)
        match ((← (encdec_reg_backwards
            mapping35_)), (← (encdec_reg_backwards
            mapping36_)), (← (encdec_reg_backwards
            mapping37_))) with
        | (rs2, rs1, rd) =>
          (pure (some
              (RTYPE (rs2, rs1, rd, XOR)))))
    else (pure none)) with
  | r => jp r

/-- Block 17 of `encdec_backwards`, passing its result to the continuation `jp`. -/
def _root_.FlapjackRiscvCheck.decodeBlock17 (jp : Option instruction → SailM instruction)
    (head_exp_ : BitVec 32) : SailM instruction := do
  match (← do
    let v__1606 := head_exp_
    if (((let mapping40_ : (BitVec 5) :=
           (Sail.BitVec.extractLsb
             v__1606 11 7)
         let mapping39_ : (BitVec 5) :=
           (Sail.BitVec.extractLsb
             v__1606 19 15)
         let mapping38_ : (BitVec 5) :=
           (Sail.BitVec.extractLsb
             v__1606 24 20)
         ((encdec_reg_backwards_matches
             mapping38_) && ((encdec_reg_backwards_matches
               mapping39_) && (encdec_reg_backwards_matches
               mapping40_)))) && (((Sail.BitVec.extractLsb
               v__1606 31 25) == (0b0000000#7 : (BitVec 7))) && (((Sail.BitVec.extractLsb
                 v__1606 14 12) == (0b001#3 : (BitVec 3))) && ((Sail.BitVec.extractLsb
                 v__1606 6 0) == (0b0110011#7 : (BitVec 7)))))) : Bool)
    then
      (do
        let mapping40_ : (BitVec 5) :=
          (Sail.BitVec.extractLsb
            v__1606 11 7)
        let mapping39_ : (BitVec 5) :=
          (Sail.BitVec.extractLsb
            v__1606 19 15)
        let mapping38_ : (BitVec 5) :=
          (Sail.BitVec.extractLsb
            v__1606 24 20)
        match ((← (encdec_reg_backwards
            mapping38_)), (← (encdec_reg_backwards
            mapping39_)), (← (encdec_reg_backwards
            mapping40_))) with
        | (rs2, rs1, rd) =>
          (pure (some
              (RTYPE
                (rs2, rs1, rd, SLL)))))
    else (pure none)) with
  | r => jp r

/-- Block 18 of `encdec_backwards`, passing its result to the continuation `jp`. -/
def _root_.FlapjackRiscvCheck.decodeBlock18 (jp : Option instruction → SailM instruction)
    (head_exp_ : BitVec 32) : SailM instruction := do
  match (← do
    let v__1602 := head_exp_
    if (((let mapping43_ : (BitVec 5) :=
           (Sail.BitVec.extractLsb
             v__1602 11 7)
         let mapping42_ : (BitVec 5) :=
           (Sail.BitVec.extractLsb
             v__1602 19 15)
         let mapping41_ : (BitVec 5) :=
           (Sail.BitVec.extractLsb
             v__1602 24 20)
         ((encdec_reg_backwards_matches
             mapping41_) && ((encdec_reg_backwards_matches
               mapping42_) && (encdec_reg_backwards_matches
               mapping43_)))) && (((Sail.BitVec.extractLsb
               v__1602 31 25) == (0b0000000#7 : (BitVec 7))) && (((Sail.BitVec.extractLsb
                 v__1602 14 12) == (0b101#3 : (BitVec 3))) && ((Sail.BitVec.extractLsb
                 v__1602 6 0) == (0b0110011#7 : (BitVec 7)))))) : Bool)
    then
      (do
        let mapping43_ : (BitVec 5) :=
          (Sail.BitVec.extractLsb
            v__1602 11 7)
        let mapping42_ : (BitVec 5) :=
          (Sail.BitVec.extractLsb
            v__1602 19 15)
        let mapping41_ : (BitVec 5) :=
          (Sail.BitVec.extractLsb
            v__1602 24 20)
        match ((← (encdec_reg_backwards
            mapping41_)), (← (encdec_reg_backwards
            mapping42_)), (← (encdec_reg_backwards
            mapping43_))) with
        | (rs2, rs1, rd) =>
          (pure (some
              (RTYPE
                (rs2, rs1, rd, SRL)))))
    else (pure none)) with
  | r => jp r

/-- Block 19 of `encdec_backwards`, passing its result to the continuation `jp`. -/
def _root_.FlapjackRiscvCheck.decodeBlock19 (jp : Option instruction → SailM instruction)
    (head_exp_ : BitVec 32) : SailM instruction := do
  match (← do
    let v__1598 := head_exp_
    if (((let mapping46_ : (BitVec 5) :=
           (Sail.BitVec.extractLsb
             v__1598 11 7)
         let mapping45_ : (BitVec 5) :=
           (Sail.BitVec.extractLsb
             v__1598 19 15)
         let mapping44_ : (BitVec 5) :=
           (Sail.BitVec.extractLsb
             v__1598 24 20)
         ((encdec_reg_backwards_matches
             mapping44_) && ((encdec_reg_backwards_matches
               mapping45_) && (encdec_reg_backwards_matches
               mapping46_)))) && (((Sail.BitVec.extractLsb
               v__1598 31 25) == (0b0100000#7 : (BitVec 7))) && (((Sail.BitVec.extractLsb
                 v__1598 14
                 12) == (0b000#3 : (BitVec 3))) && ((Sail.BitVec.extractLsb
                 v__1598 6 0) == (0b0110011#7 : (BitVec 7)))))) : Bool)
    then
      (do
        let mapping46_ : (BitVec 5) :=
          (Sail.BitVec.extractLsb
            v__1598 11 7)
        let mapping45_ : (BitVec 5) :=
          (Sail.BitVec.extractLsb
            v__1598 19 15)
        let mapping44_ : (BitVec 5) :=
          (Sail.BitVec.extractLsb
            v__1598 24 20)
        match ((← (encdec_reg_backwards
            mapping44_)), (← (encdec_reg_backwards
            mapping45_)), (← (encdec_reg_backwards
            mapping46_))) with
        | (rs2, rs1, rd) =>
          (pure (some
              (RTYPE
                (rs2, rs1, rd, SUB)))))
    else (pure none)) with
  | r => jp r

/-- Block 20 of `encdec_backwards`, passing its result to the continuation `jp`. -/
def _root_.FlapjackRiscvCheck.decodeBlock20 (jp : Option instruction → SailM instruction)
    (head_exp_ : BitVec 32) : SailM instruction := do
  match (← do
    let v__1594 :=
      head_exp_
    if (((let mapping49_ : (BitVec 5) :=
           (Sail.BitVec.extractLsb
             v__1594 11
             7)
         let mapping48_ : (BitVec 5) :=
           (Sail.BitVec.extractLsb
             v__1594 19
             15)
         let mapping47_ : (BitVec 5) :=
           (Sail.BitVec.extractLsb
             v__1594 24
             20)
         ((encdec_reg_backwards_matches
             mapping47_) && ((encdec_reg_backwards_matches
               mapping48_) && (encdec_reg_backwards_matches
               mapping49_)))) && (((Sail.BitVec.extractLsb
               v__1594
               31 25) == (0b0100000#7 : (BitVec 7))) && (((Sail.BitVec.extractLsb
                 v__1594
                 14 12) == (0b101#3 : (BitVec 3))) && ((Sail.BitVec.extractLsb
                 v__1594
                 6 0) == (0b0110011#7 : (BitVec 7)))))) : Bool)
    then
      (do
        let mapping49_ : (BitVec 5) :=
          (Sail.BitVec.extractLsb
            v__1594 11 7)
        let mapping48_ : (BitVec 5) :=
          (Sail.BitVec.extractLsb
            v__1594 19
            15)
        let mapping47_ : (BitVec 5) :=
          (Sail.BitVec.extractLsb
            v__1594 24
            20)
        match ((← (encdec_reg_backwards
            mapping47_)), (← (encdec_reg_backwards
            mapping48_)), (← (encdec_reg_backwards
            mapping49_))) with
        | (rs2, rs1, rd) =>
          (pure (some
              (RTYPE
                (rs2, rs1, rd, SRA)))))
    else (pure none)) with
  | r => jp r

/-- Block 21 of `encdec_backwards`, passing its result to the continuation `jp`. -/
def _root_.FlapjackRiscvCheck.decodeBlock21 (jp : Option instruction → SailM instruction)
    (head_exp_ : BitVec 32) : SailM instruction := do
  match (← do
    let v__1592 :=
      head_exp_
    if (((let mapping53_ : (BitVec 5) :=
           (Sail.BitVec.extractLsb
             v__1592
             11 7)
         let mapping52_ : (BitVec 2) :=
           (Sail.BitVec.extractLsb
             v__1592
             13 12)
         let mapping51_ : (BitVec 1) :=
           (Sail.BitVec.extractLsb
             v__1592
             14 14)
         let mapping50_ : (BitVec 5) :=
           (Sail.BitVec.extractLsb
             v__1592
             19 15)
         ((encdec_reg_backwards_matches
             mapping50_) && ((bool_bit_backwards_matches
               mapping51_) && ((width_enc_backwards_matches
                 mapping52_) && (encdec_reg_backwards_matches
                 mapping53_))))) && ((Sail.BitVec.extractLsb
             v__1592
             6 0) == (0b0000011#7 : (BitVec 7)))) : Bool)
    then
      (do
        let imm : (BitVec 12) :=
          (Sail.BitVec.extractLsb
            v__1592
            31 20)
        let mapping53_ : (BitVec 5) :=
          (Sail.BitVec.extractLsb
            v__1592
            11 7)
        let mapping52_ : (BitVec 2) :=
          (Sail.BitVec.extractLsb
            v__1592
            13 12)
        let mapping51_ : (BitVec 1) :=
          (Sail.BitVec.extractLsb
            v__1592
            14 14)
        let mapping50_ : (BitVec 5) :=
          (Sail.BitVec.extractLsb
            v__1592
            19 15)
        let imm : (BitVec 12) :=
          (Sail.BitVec.extractLsb
            v__1592
            31 20)
        match ((← (encdec_reg_backwards
            mapping50_)), (bool_bit_backwards
          mapping51_), (width_enc_backwards
          mapping52_), (← (encdec_reg_backwards
            mapping53_))) with
        | (rs1, is_unsigned, width, rd) =>
          (if ((valid_load_encdec
               width
               is_unsigned) : Bool)
          then
            (pure (some
                (LOAD
                  (imm, rs1, rd, is_unsigned, width))))
          else
            (pure none)))
    else (pure none)) with
  | r => jp r

/-- Block 22 of `encdec_backwards`, passing its result to the continuation `jp`. -/
def _root_.FlapjackRiscvCheck.decodeBlock22 (jp : Option instruction → SailM instruction)
    (head_exp_ : BitVec 32) : SailM instruction := do
  match (← do
    let v__1589 :=
      head_exp_
    if (((let mapping56_ : (BitVec 2) :=
           (Sail.BitVec.extractLsb
             v__1589
             13
             12)
         let mapping55_ : (BitVec 5) :=
           (Sail.BitVec.extractLsb
             v__1589
             19
             15)
         let mapping54_ : (BitVec 5) :=
           (Sail.BitVec.extractLsb
             v__1589
             24
             20)
         ((encdec_reg_backwards_matches
             mapping54_) && ((encdec_reg_backwards_matches
               mapping55_) && (width_enc_backwards_matches
               mapping56_)))) && (((Sail.BitVec.extractLsb
               v__1589
               14
               14) == (0#1 : (BitVec 1))) && ((Sail.BitVec.extractLsb
               v__1589
               6
               0) == (0b0100011#7 : (BitVec 7))))) : Bool)
    then
      (do
        let imm_11_5_ : (BitVec 7) :=
          (Sail.BitVec.extractLsb
            v__1589
            31
            25)
        let mapping56_ : (BitVec 2) :=
          (Sail.BitVec.extractLsb
            v__1589
            13
            12)
        let mapping55_ : (BitVec 5) :=
          (Sail.BitVec.extractLsb
            v__1589
            19
            15)
        let mapping54_ : (BitVec 5) :=
          (Sail.BitVec.extractLsb
            v__1589
            24
            20)
        let imm_4_0_ : (BitVec 5) :=
          (Sail.BitVec.extractLsb
            v__1589
            11 7)
        let imm_11_5_ : (BitVec 7) :=
          (Sail.BitVec.extractLsb
            v__1589
            31
            25)
        match ((← (encdec_reg_backwards
            mapping54_)), (← (encdec_reg_backwards
            mapping55_)), (width_enc_backwards
          mapping56_)) with
        | (rs2, rs1, width) =>
          (if ((let imm :=
               (imm_11_5_ +++ imm_4_0_)
             (width ≤b xlen_bytes)) : Bool)
          then
            (pure (some
                (let imm :=
                  (imm_11_5_ +++ imm_4_0_)
                (STORE
                  (imm, rs2, rs1, width)))))
          else
            (pure none)))
    else
      (pure none)) with
  | r => jp r

/-- Block 23 of `encdec_backwards`, passing its result to the continuation `jp`. -/
def _root_.FlapjackRiscvCheck.decodeBlock23 (jp : Option instruction → SailM instruction)
    (head_exp_ : BitVec 32) : SailM instruction := do
  match (← do
    let v__1586 :=
      head_exp_
    if (((let mapping58_ : (BitVec 5) :=
           (Sail.BitVec.extractLsb
             v__1586
             11
             7)
         let mapping57_ : (BitVec 5) :=
           (Sail.BitVec.extractLsb
             v__1586
             19
             15)
         ((encdec_reg_backwards_matches
             mapping57_) && (encdec_reg_backwards_matches
             mapping58_))) && (((Sail.BitVec.extractLsb
               v__1586
               14
               12) == (0b000#3 : (BitVec 3))) && ((Sail.BitVec.extractLsb
               v__1586
               6
               0) == (0b0011011#7 : (BitVec 7))))) : Bool)
    then
      (do
        let imm : (BitVec 12) :=
          (Sail.BitVec.extractLsb
            v__1586
            31
            20)
        let mapping58_ : (BitVec 5) :=
          (Sail.BitVec.extractLsb
            v__1586
            11
            7)
        let mapping57_ : (BitVec 5) :=
          (Sail.BitVec.extractLsb
            v__1586
            19
            15)
        let imm : (BitVec 12) :=
          (Sail.BitVec.extractLsb
            v__1586
            31
            20)
        match ((← (encdec_reg_backwards
            mapping57_)), (← (encdec_reg_backwards
            mapping58_))) with
        | (rs1, rd) =>
          (if ((xlen == 64) : Bool)
          then
            (pure (some
                (ADDIW
                  (imm, rs1, rd))))
          else
            (pure none)))
    else
      (pure none)) with
  | r => jp r

/-- Block 24 of `encdec_backwards`, passing its result to the continuation `jp`. -/
def _root_.FlapjackRiscvCheck.decodeBlock24 (jp : Option instruction → SailM instruction)
    (head_exp_ : BitVec 32) : SailM instruction := do
  match (← do
    let v__1582 :=
      head_exp_
    if (((let mapping61_ : (BitVec 5) :=
           (Sail.BitVec.extractLsb
             v__1582
             11
             7)
         let mapping60_ : (BitVec 5) :=
           (Sail.BitVec.extractLsb
             v__1582
             19
             15)
         let mapping59_ : (BitVec 5) :=
           (Sail.BitVec.extractLsb
             v__1582
             24
             20)
         ((encdec_reg_backwards_matches
             mapping59_) && ((encdec_reg_backwards_matches
               mapping60_) && (encdec_reg_backwards_matches
               mapping61_)))) && (((Sail.BitVec.extractLsb
               v__1582
               31
               25) == (0b0000000#7 : (BitVec 7))) && (((Sail.BitVec.extractLsb
                 v__1582
                 14
                 12) == (0b000#3 : (BitVec 3))) && ((Sail.BitVec.extractLsb
                 v__1582
                 6
                 0) == (0b0111011#7 : (BitVec 7)))))) : Bool)
    then
      (do
        let mapping61_ : (BitVec 5) :=
          (Sail.BitVec.extractLsb
            v__1582
            11
            7)
        let mapping60_ : (BitVec 5) :=
          (Sail.BitVec.extractLsb
            v__1582
            19
            15)
        let mapping59_ : (BitVec 5) :=
          (Sail.BitVec.extractLsb
            v__1582
            24
            20)
        match ((← (encdec_reg_backwards
            mapping59_)), (← (encdec_reg_backwards
            mapping60_)), (← (encdec_reg_backwards
            mapping61_))) with
        | (rs2, rs1, rd) =>
          (if ((xlen == 64) : Bool)
          then
            (pure (some
                (RTYPEW
                  (rs2, rs1, rd, ADDW))))
          else
            (pure none)))
    else
      (pure none)) with
  | r => jp r

/-- Block 25 of `encdec_backwards`, passing its result to the continuation `jp`. -/
def _root_.FlapjackRiscvCheck.decodeBlock25 (jp : Option instruction → SailM instruction)
    (head_exp_ : BitVec 32) : SailM instruction := do
  match (← do
    let v__1578 :=
      head_exp_
    if (((let mapping64_ : (BitVec 5) :=
           (Sail.BitVec.extractLsb
             v__1578
             11
             7)
         let mapping63_ : (BitVec 5) :=
           (Sail.BitVec.extractLsb
             v__1578
             19
             15)
         let mapping62_ : (BitVec 5) :=
           (Sail.BitVec.extractLsb
             v__1578
             24
             20)
         ((encdec_reg_backwards_matches
             mapping62_) && ((encdec_reg_backwards_matches
               mapping63_) && (encdec_reg_backwards_matches
               mapping64_)))) && (((Sail.BitVec.extractLsb
               v__1578
               31
               25) == (0b0100000#7 : (BitVec 7))) && (((Sail.BitVec.extractLsb
                 v__1578
                 14
                 12) == (0b000#3 : (BitVec 3))) && ((Sail.BitVec.extractLsb
                 v__1578
                 6
                 0) == (0b0111011#7 : (BitVec 7)))))) : Bool)
    then
      (do
        let mapping64_ : (BitVec 5) :=
          (Sail.BitVec.extractLsb
            v__1578
            11
            7)
        let mapping63_ : (BitVec 5) :=
          (Sail.BitVec.extractLsb
            v__1578
            19
            15)
        let mapping62_ : (BitVec 5) :=
          (Sail.BitVec.extractLsb
            v__1578
            24
            20)
        match ((← (encdec_reg_backwards
            mapping62_)), (← (encdec_reg_backwards
            mapping63_)), (← (encdec_reg_backwards
            mapping64_))) with
        | (rs2, rs1, rd) =>
          (if ((xlen == 64) : Bool)
          then
            (pure (some
                (RTYPEW
                  (rs2, rs1, rd, SUBW))))
          else
            (pure none)))
    else
      (pure none)) with
  | r => jp r

/-- Block 26 of `encdec_backwards`, passing its result to the continuation `jp`. -/
def _root_.FlapjackRiscvCheck.decodeBlock26 (jp : Option instruction → SailM instruction)
    (head_exp_ : BitVec 32) : SailM instruction := do
  match (← do
    let v__1574 :=
      head_exp_
    if (((let mapping67_ : (BitVec 5) :=
           (Sail.BitVec.extractLsb
             v__1574
             11
             7)
         let mapping66_ : (BitVec 5) :=
           (Sail.BitVec.extractLsb
             v__1574
             19
             15)
         let mapping65_ : (BitVec 5) :=
           (Sail.BitVec.extractLsb
             v__1574
             24
             20)
         ((encdec_reg_backwards_matches
             mapping65_) && ((encdec_reg_backwards_matches
               mapping66_) && (encdec_reg_backwards_matches
               mapping67_)))) && (((Sail.BitVec.extractLsb
               v__1574
               31
               25) == (0b0000000#7 : (BitVec 7))) && (((Sail.BitVec.extractLsb
                 v__1574
                 14
                 12) == (0b001#3 : (BitVec 3))) && ((Sail.BitVec.extractLsb
                 v__1574
                 6
                 0) == (0b0111011#7 : (BitVec 7)))))) : Bool)
    then
      (do
        let mapping67_ : (BitVec 5) :=
          (Sail.BitVec.extractLsb
            v__1574
            11
            7)
        let mapping66_ : (BitVec 5) :=
          (Sail.BitVec.extractLsb
            v__1574
            19
            15)
        let mapping65_ : (BitVec 5) :=
          (Sail.BitVec.extractLsb
            v__1574
            24
            20)
        match ((← (encdec_reg_backwards
            mapping65_)), (← (encdec_reg_backwards
            mapping66_)), (← (encdec_reg_backwards
            mapping67_))) with
        | (rs2, rs1, rd) =>
          (if ((xlen == 64) : Bool)
          then
            (pure (some
                (RTYPEW
                  (rs2, rs1, rd, SLLW))))
          else
            (pure none)))
    else
      (pure none)) with
  | r => jp r

/-- Block 27 of `encdec_backwards`, passing its result to the continuation `jp`. -/
def _root_.FlapjackRiscvCheck.decodeBlock27 (jp : Option instruction → SailM instruction)
    (head_exp_ : BitVec 32) : SailM instruction := do
  match (← do
    let v__1570 :=
      head_exp_
    if (((let mapping70_ : (BitVec 5) :=
           (Sail.BitVec.extractLsb
             v__1570
             11
             7)
         let mapping69_ : (BitVec 5) :=
           (Sail.BitVec.extractLsb
             v__1570
             19
             15)
         let mapping68_ : (BitVec 5) :=
           (Sail.BitVec.extractLsb
             v__1570
             24
             20)
         ((encdec_reg_backwards_matches
             mapping68_) && ((encdec_reg_backwards_matches
               mapping69_) && (encdec_reg_backwards_matches
               mapping70_)))) && (((Sail.BitVec.extractLsb
               v__1570
               31
               25) == (0b0000000#7 : (BitVec 7))) && (((Sail.BitVec.extractLsb
                 v__1570
                 14
                 12) == (0b101#3 : (BitVec 3))) && ((Sail.BitVec.extractLsb
                 v__1570
                 6
                 0) == (0b0111011#7 : (BitVec 7)))))) : Bool)
    then
      (do
        let mapping70_ : (BitVec 5) :=
          (Sail.BitVec.extractLsb
            v__1570
            11
            7)
        let mapping69_ : (BitVec 5) :=
          (Sail.BitVec.extractLsb
            v__1570
            19
            15)
        let mapping68_ : (BitVec 5) :=
          (Sail.BitVec.extractLsb
            v__1570
            24
            20)
        match ((← (encdec_reg_backwards
            mapping68_)), (← (encdec_reg_backwards
            mapping69_)), (← (encdec_reg_backwards
            mapping70_))) with
        | (rs2, rs1, rd) =>
          (if ((xlen == 64) : Bool)
          then
            (pure (some
                (RTYPEW
                  (rs2, rs1, rd, SRLW))))
          else
            (pure none)))
    else
      (pure none)) with
  | r => jp r

/-- Block 28 of `encdec_backwards`, passing its result to the continuation `jp`. -/
def _root_.FlapjackRiscvCheck.decodeBlock28 (jp : Option instruction → SailM instruction)
    (head_exp_ : BitVec 32) : SailM instruction := do
  match (← do
    let v__1566 :=
      head_exp_
    if (((let mapping73_ : (BitVec 5) :=
           (Sail.BitVec.extractLsb
             v__1566
             11
             7)
         let mapping72_ : (BitVec 5) :=
           (Sail.BitVec.extractLsb
             v__1566
             19
             15)
         let mapping71_ : (BitVec 5) :=
           (Sail.BitVec.extractLsb
             v__1566
             24
             20)
         ((encdec_reg_backwards_matches
             mapping71_) && ((encdec_reg_backwards_matches
               mapping72_) && (encdec_reg_backwards_matches
               mapping73_)))) && (((Sail.BitVec.extractLsb
               v__1566
               31
               25) == (0b0100000#7 : (BitVec 7))) && (((Sail.BitVec.extractLsb
                 v__1566
                 14
                 12) == (0b101#3 : (BitVec 3))) && ((Sail.BitVec.extractLsb
                 v__1566
                 6
                 0) == (0b0111011#7 : (BitVec 7)))))) : Bool)
    then
      (do
        let mapping73_ : (BitVec 5) :=
          (Sail.BitVec.extractLsb
            v__1566
            11
            7)
        let mapping72_ : (BitVec 5) :=
          (Sail.BitVec.extractLsb
            v__1566
            19
            15)
        let mapping71_ : (BitVec 5) :=
          (Sail.BitVec.extractLsb
            v__1566
            24
            20)
        match ((← (encdec_reg_backwards
            mapping71_)), (← (encdec_reg_backwards
            mapping72_)), (← (encdec_reg_backwards
            mapping73_))) with
        | (rs2, rs1, rd) =>
          (if ((xlen == 64) : Bool)
          then
            (pure (some
                (RTYPEW
                  (rs2, rs1, rd, SRAW))))
          else
            (pure none)))
    else
      (pure none)) with
  | r => jp r

/-- Block 29 of `encdec_backwards`, passing its result to the continuation `jp`. -/
def _root_.FlapjackRiscvCheck.decodeBlock29 (jp : Option instruction → SailM instruction)
    (head_exp_ : BitVec 32) : SailM instruction := do
  match (← do
    let v__1562 :=
      head_exp_
    if (((let mapping75_ : (BitVec 5) :=
           (Sail.BitVec.extractLsb
             v__1562
             11
             7)
         let mapping74_ : (BitVec 5) :=
           (Sail.BitVec.extractLsb
             v__1562
             19
             15)
         ((encdec_reg_backwards_matches
             mapping74_) && (encdec_reg_backwards_matches
             mapping75_))) && (((Sail.BitVec.extractLsb
               v__1562
               31
               25) == (0b0000000#7 : (BitVec 7))) && (((Sail.BitVec.extractLsb
                 v__1562
                 14
                 12) == (0b001#3 : (BitVec 3))) && ((Sail.BitVec.extractLsb
                 v__1562
                 6
                 0) == (0b0011011#7 : (BitVec 7)))))) : Bool)
    then
      (do
        let shamt : (BitVec 5) :=
          (Sail.BitVec.extractLsb
            v__1562
            24
            20)
        let mapping75_ : (BitVec 5) :=
          (Sail.BitVec.extractLsb
            v__1562
            11
            7)
        let mapping74_ : (BitVec 5) :=
          (Sail.BitVec.extractLsb
            v__1562
            19
            15)
        match ((← (encdec_reg_backwards
            mapping74_)), (← (encdec_reg_backwards
            mapping75_))) with
        | (rs1, rd) =>
          (if ((xlen == 64) : Bool)
          then
            (pure (some
                (SHIFTIWOP
                  (shamt, rs1, rd, SLLIW))))
          else
            (pure none)))
    else
      (pure none)) with
  | r => jp r

/-- Block 30 of `encdec_backwards`, passing its result to the continuation `jp`. -/
def _root_.FlapjackRiscvCheck.decodeBlock30 (jp : Option instruction → SailM instruction)
    (head_exp_ : BitVec 32) : SailM instruction := do
  match (← do
    let v__1558 :=
      head_exp_
    if (((let mapping77_ : (BitVec 5) :=
           (Sail.BitVec.extractLsb
             v__1558
             11
             7)
         let mapping76_ : (BitVec 5) :=
           (Sail.BitVec.extractLsb
             v__1558
             19
             15)
         ((encdec_reg_backwards_matches
             mapping76_) && (encdec_reg_backwards_matches
             mapping77_))) && (((Sail.BitVec.extractLsb
               v__1558
               31
               25) == (0b0000000#7 : (BitVec 7))) && (((Sail.BitVec.extractLsb
                 v__1558
                 14
                 12) == (0b101#3 : (BitVec 3))) && ((Sail.BitVec.extractLsb
                 v__1558
                 6
                 0) == (0b0011011#7 : (BitVec 7)))))) : Bool)
    then
      (do
        let shamt : (BitVec 5) :=
          (Sail.BitVec.extractLsb
            v__1558
            24
            20)
        let mapping77_ : (BitVec 5) :=
          (Sail.BitVec.extractLsb
            v__1558
            11
            7)
        let mapping76_ : (BitVec 5) :=
          (Sail.BitVec.extractLsb
            v__1558
            19
            15)
        match ((← (encdec_reg_backwards
            mapping76_)), (← (encdec_reg_backwards
            mapping77_))) with
        | (rs1, rd) =>
          (if ((xlen == 64) : Bool)
          then
            (pure (some
                (SHIFTIWOP
                  (shamt, rs1, rd, SRLIW))))
          else
            (pure none)))
    else
      (pure none)) with
  | r => jp r

/-- Block 31 of `encdec_backwards`, passing its result to the continuation `jp`. -/
def _root_.FlapjackRiscvCheck.decodeBlock31 (jp : Option instruction → SailM instruction)
    (head_exp_ : BitVec 32) : SailM instruction := do
  match (← do
    let v__1554 :=
      head_exp_
    if (((let mapping79_ : (BitVec 5) :=
           (Sail.BitVec.extractLsb
             v__1554
             11
             7)
         let mapping78_ : (BitVec 5) :=
           (Sail.BitVec.extractLsb
             v__1554
             19
             15)
         ((encdec_reg_backwards_matches
             mapping78_) && (encdec_reg_backwards_matches
             mapping79_))) && (((Sail.BitVec.extractLsb
               v__1554
               31
               25) == (0b0100000#7 : (BitVec 7))) && (((Sail.BitVec.extractLsb
                 v__1554
                 14
                 12) == (0b101#3 : (BitVec 3))) && ((Sail.BitVec.extractLsb
                 v__1554
                 6
                 0) == (0b0011011#7 : (BitVec 7)))))) : Bool)
    then
      (do
        let shamt : (BitVec 5) :=
          (Sail.BitVec.extractLsb
            v__1554
            24
            20)
        let mapping79_ : (BitVec 5) :=
          (Sail.BitVec.extractLsb
            v__1554
            11
            7)
        let mapping78_ : (BitVec 5) :=
          (Sail.BitVec.extractLsb
            v__1554
            19
            15)
        match ((← (encdec_reg_backwards
            mapping78_)), (← (encdec_reg_backwards
            mapping79_))) with
        | (rs1, rd) =>
          (if ((xlen == 64) : Bool)
          then
            (pure (some
                (SHIFTIWOP
                  (shamt, rs1, rd, SRAIW))))
          else
            (pure none)))
    else
      (pure none)) with
  | r => jp r

/-- Block 32 of `encdec_backwards`, passing its result to the continuation `jp`. -/
def _root_.FlapjackRiscvCheck.decodeBlock32 (jp : Option instruction → SailM instruction)
    (head_exp_ : BitVec 32) : SailM instruction := do
  match (← do
    let v__1543 :=
      head_exp_
    if ((v__1543 == (0x8330000F#32 : (BitVec 32))) : Bool)
    then
      (pure (some
          (FENCE_TSO
            ())))
    else
      (do
        if (((let mapping81_ : (BitVec 5) :=
               (Sail.BitVec.extractLsb
                 v__1543
                 11
                 7)
             let mapping80_ : (BitVec 5) :=
               (Sail.BitVec.extractLsb
                 v__1543
                 19
                 15)
             ((encdec_reg_backwards_matches
                 mapping80_) && (encdec_reg_backwards_matches
                 mapping81_))) && (((Sail.BitVec.extractLsb
                   v__1543
                   14
                   12) == (0b000#3 : (BitVec 3))) && ((Sail.BitVec.extractLsb
                   v__1543
                   6
                   0) == (0b0001111#7 : (BitVec 7))))) : Bool)
        then
          (do
            let fm : (BitVec 4) :=
              (Sail.BitVec.extractLsb
                v__1543
                31
                28)
            let succ : (BitVec 4) :=
              (Sail.BitVec.extractLsb
                v__1543
                23
                20)
            let pred : (BitVec 4) :=
              (Sail.BitVec.extractLsb
                v__1543
                27
                24)
            let mapping81_ : (BitVec 5) :=
              (Sail.BitVec.extractLsb
                v__1543
                11
                7)
            let mapping80_ : (BitVec 5) :=
              (Sail.BitVec.extractLsb
                v__1543
                19
                15)
            let fm : (BitVec 4) :=
              (Sail.BitVec.extractLsb
                v__1543
                31
                28)
            match ((← (encdec_reg_backwards
                mapping80_)), (← (encdec_reg_backwards
                mapping81_))) with
            | (rs, rd) =>
              (pure (some
                  (FENCE
                    (fm, pred, succ, rs, rd)))))
        else
          (pure none))) with
  | r => jp r

/-- Block 33 of `encdec_backwards`, passing its result to the continuation `jp`. -/
def _root_.FlapjackRiscvCheck.decodeBlock33 (jp : Option instruction → SailM instruction)
    (head_exp_ : BitVec 32) : SailM instruction := do
  match (← do
    let v__1506 :=
      head_exp_
    if ((v__1506 == (0x00000073#32 : (BitVec 32))) : Bool)
    then
      (pure (some
          (ECALL
            ())))
    else
      (do
        if ((v__1506 == (0x30200073#32 : (BitVec 32))) : Bool)
        then
          (pure (some
              (MRET
                ())))
        else
          (do
            if ((v__1506 == (0x10200073#32 : (BitVec 32))) : Bool)
            then
              (pure (some
                  (SRET
                    ())))
            else
              (do
                if ((v__1506 == (0x00100073#32 : (BitVec 32))) : Bool)
                then
                  (pure (some
                      (EBREAK
                        ())))
                else
                  (do
                    if ((v__1506 == (0x10500073#32 : (BitVec 32))) : Bool)
                    then
                      (pure (some
                          (WFI
                            ())))
                    else
                      (do
                        if (((let mapping83_ : (BitVec 5) :=
                               (Sail.BitVec.extractLsb
                                 v__1506
                                 19
                                 15)
                             let mapping82_ : (BitVec 5) :=
                               (Sail.BitVec.extractLsb
                                 v__1506
                                 24
                                 20)
                             ((encdec_reg_backwards_matches
                                 mapping82_) && (encdec_reg_backwards_matches
                                 mapping83_))) && (((Sail.BitVec.extractLsb
                                   v__1506
                                   31
                                   25) == (0b0001001#7 : (BitVec 7))) && ((Sail.BitVec.extractLsb
                                   v__1506
                                   14
                                   0) == (0b000000001110011#15 : (BitVec 15))))) : Bool)
                        then
                          (do
                            let mapping83_ : (BitVec 5) :=
                              (Sail.BitVec.extractLsb
                                v__1506
                                19
                                15)
                            let mapping82_ : (BitVec 5) :=
                              (Sail.BitVec.extractLsb
                                v__1506
                                24
                                20)
                            match ((← (encdec_reg_backwards
                                mapping82_)), (← (encdec_reg_backwards
                                mapping83_))) with
                            | (rs2, rs1) =>
                              (do
                                if (((← (virtual_memory_supported
                                         ())) || (not
                                       (true : Bool))) : Bool)
                                then
                                  (pure (some
                                      (SFENCE_VMA
                                        (rs1, rs2))))
                                else
                                  (pure none)))
                        else
                          (pure none))))))) with
  | r => jp r

/-- Block 34 of `encdec_backwards`, passing its result to the continuation `jp`. -/
def _root_.FlapjackRiscvCheck.decodeBlock34 (jp : Option instruction → SailM instruction)
    (head_exp_ : BitVec 32) : SailM instruction := do
  match (← do
    let v__1504 :=
      head_exp_
    if (((let mapping84_ : (BitVec 5) :=
           (Sail.BitVec.extractLsb
             v__1504
             31
             27)
         let mapping90_ : (BitVec 5) :=
           (Sail.BitVec.extractLsb
             v__1504
             11
             7)
         let mapping89_ : (BitVec 3) :=
           (Sail.BitVec.extractLsb
             v__1504
             14
             12)
         let mapping88_ : (BitVec 5) :=
           (Sail.BitVec.extractLsb
             v__1504
             19
             15)
         let mapping87_ : (BitVec 5) :=
           (Sail.BitVec.extractLsb
             v__1504
             24
             20)
         let mapping86_ : (BitVec 1) :=
           (Sail.BitVec.extractLsb
             v__1504
             25
             25)
         let mapping85_ : (BitVec 1) :=
           (Sail.BitVec.extractLsb
             v__1504
             26
             26)
         let mapping84_ : (BitVec 5) :=
           (Sail.BitVec.extractLsb
             v__1504
             31
             27)
         ((encdec_amoop_backwards_matches
             mapping84_) && ((bool_bit_backwards_matches
               mapping85_) && ((bool_bit_backwards_matches
                 mapping86_) && ((encdec_reg_backwards_matches
                   mapping87_) && ((encdec_reg_backwards_matches
                     mapping88_) && ((width_enc_wide_backwards_matches
                       mapping89_) && (encdec_reg_backwards_matches
                       mapping90_)))))))) && ((Sail.BitVec.extractLsb
             v__1504
             6
             0) == (0b0101111#7 : (BitVec 7)))) : Bool)
    then
      (do
        let mapping84_ : (BitVec 5) :=
          (Sail.BitVec.extractLsb
            v__1504
            31
            27)
        let mapping90_ : (BitVec 5) :=
          (Sail.BitVec.extractLsb
            v__1504
            11
            7)
        let mapping89_ : (BitVec 3) :=
          (Sail.BitVec.extractLsb
            v__1504
            14
            12)
        let mapping88_ : (BitVec 5) :=
          (Sail.BitVec.extractLsb
            v__1504
            19
            15)
        let mapping87_ : (BitVec 5) :=
          (Sail.BitVec.extractLsb
            v__1504
            24
            20)
        let mapping86_ : (BitVec 1) :=
          (Sail.BitVec.extractLsb
            v__1504
            25
            25)
        let mapping85_ : (BitVec 1) :=
          (Sail.BitVec.extractLsb
            v__1504
            26
            26)
        let mapping84_ : (BitVec 5) :=
          (Sail.BitVec.extractLsb
            v__1504
            31
            27)
        match ((← (encdec_amoop_backwards
            mapping84_)), (bool_bit_backwards
          mapping85_), (bool_bit_backwards
          mapping86_), (← (encdec_reg_backwards
            mapping87_)), (← (encdec_reg_backwards
            mapping88_)), (← (width_enc_wide_backwards
            mapping89_)), (← (encdec_reg_backwards
            mapping90_))) with
        | (op, aq, rl, rs2, rs1, size, rd) =>
          (do
            if ((← (amo_encoding_valid
                   size
                   op
                   rs2
                   rd)) : Bool)
            then
              (pure (some
                  (AMO
                    (op, aq, rl, rs2, rs1, size, rd))))
            else
              (pure none)))
    else
      (pure none)) with
  | r => jp r

/-- Block 35 of `encdec_backwards`, passing its result to the continuation `jp`. -/
def _root_.FlapjackRiscvCheck.decodeBlock35 (jp : Option instruction → SailM instruction)
    (head_exp_ : BitVec 32) : SailM instruction := do
  match (← do
    let v__1499 :=
      head_exp_
    if (((let mapping95_ : (BitVec 5) :=
           (Sail.BitVec.extractLsb
             v__1499
             11
             7)
         let mapping94_ : (BitVec 2) :=
           (Sail.BitVec.extractLsb
             v__1499
             13
             12)
         let mapping93_ : (BitVec 5) :=
           (Sail.BitVec.extractLsb
             v__1499
             19
             15)
         let mapping92_ : (BitVec 1) :=
           (Sail.BitVec.extractLsb
             v__1499
             25
             25)
         let mapping91_ : (BitVec 1) :=
           (Sail.BitVec.extractLsb
             v__1499
             26
             26)
         ((bool_bit_backwards_matches
             mapping91_) && ((bool_bit_backwards_matches
               mapping92_) && ((encdec_reg_backwards_matches
                 mapping93_) && ((width_enc_backwards_matches
                   mapping94_) && (encdec_reg_backwards_matches
                   mapping95_)))))) && (((Sail.BitVec.extractLsb
               v__1499
               31
               27) == (0b00010#5 : (BitVec 5))) && (((Sail.BitVec.extractLsb
                 v__1499
                 24
                 20) == (0b00000#5 : (BitVec 5))) && (((Sail.BitVec.extractLsb
                   v__1499
                   14
                   14) == (0#1 : (BitVec 1))) && ((Sail.BitVec.extractLsb
                   v__1499
                   6
                   0) == (0b0101111#7 : (BitVec 7))))))) : Bool)
    then
      (do
        let mapping95_ : (BitVec 5) :=
          (Sail.BitVec.extractLsb
            v__1499
            11
            7)
        let mapping94_ : (BitVec 2) :=
          (Sail.BitVec.extractLsb
            v__1499
            13
            12)
        let mapping93_ : (BitVec 5) :=
          (Sail.BitVec.extractLsb
            v__1499
            19
            15)
        let mapping92_ : (BitVec 1) :=
          (Sail.BitVec.extractLsb
            v__1499
            25
            25)
        let mapping91_ : (BitVec 1) :=
          (Sail.BitVec.extractLsb
            v__1499
            26
            26)
        match ((bool_bit_backwards
          mapping91_), (bool_bit_backwards
          mapping92_), (← (encdec_reg_backwards
            mapping93_)), (width_enc_backwards
          mapping94_), (← (encdec_reg_backwards
            mapping95_))) with
        | (aq, rl, rs1, width, rd) =>
          (do
            if (((← (currentlyEnabled
                     Ext_Zalrsc)) && (lrsc_width_valid
                   width)) : Bool)
            then
              (pure (some
                  (LOADRES
                    (aq, rl, rs1, width, rd))))
            else
              (pure none)))
    else
      (pure none)) with
  | r => jp r

/-- Block 36 of `encdec_backwards`, passing its result to the continuation `jp`. -/
def _root_.FlapjackRiscvCheck.decodeBlock36 (jp : Option instruction → SailM instruction)
    (head_exp_ : BitVec 32) : SailM instruction := do
  match (← do
    let v__1495 :=
      head_exp_
    if (((let mapping99_ : (BitVec 5) :=
           (Sail.BitVec.extractLsb
             v__1495
             19
             15)
         let mapping98_ : (BitVec 5) :=
           (Sail.BitVec.extractLsb
             v__1495
             24
             20)
         let mapping97_ : (BitVec 1) :=
           (Sail.BitVec.extractLsb
             v__1495
             25
             25)
         let mapping96_ : (BitVec 1) :=
           (Sail.BitVec.extractLsb
             v__1495
             26
             26)
         let mapping101_ : (BitVec 5) :=
           (Sail.BitVec.extractLsb
             v__1495
             11
             7)
         let mapping100_ : (BitVec 2) :=
           (Sail.BitVec.extractLsb
             v__1495
             13
             12)
         ((bool_bit_backwards_matches
             mapping96_) && ((bool_bit_backwards_matches
               mapping97_) && ((encdec_reg_backwards_matches
                 mapping98_) && ((encdec_reg_backwards_matches
                   mapping99_) && ((width_enc_backwards_matches
                     mapping100_) && (encdec_reg_backwards_matches
                     mapping101_))))))) && (((Sail.BitVec.extractLsb
               v__1495
               31
               27) == (0b00011#5 : (BitVec 5))) && (((Sail.BitVec.extractLsb
                 v__1495
                 14
                 14) == (0#1 : (BitVec 1))) && ((Sail.BitVec.extractLsb
                 v__1495
                 6
                 0) == (0b0101111#7 : (BitVec 7)))))) : Bool)
    then
      (do
        let mapping99_ : (BitVec 5) :=
          (Sail.BitVec.extractLsb
            v__1495
            19
            15)
        let mapping98_ : (BitVec 5) :=
          (Sail.BitVec.extractLsb
            v__1495
            24
            20)
        let mapping97_ : (BitVec 1) :=
          (Sail.BitVec.extractLsb
            v__1495
            25
            25)
        let mapping96_ : (BitVec 1) :=
          (Sail.BitVec.extractLsb
            v__1495
            26
            26)
        let mapping101_ : (BitVec 5) :=
          (Sail.BitVec.extractLsb
            v__1495
            11
            7)
        let mapping100_ : (BitVec 2) :=
          (Sail.BitVec.extractLsb
            v__1495
            13
            12)
        match ((bool_bit_backwards
          mapping96_), (bool_bit_backwards
          mapping97_), (← (encdec_reg_backwards
            mapping98_)), (← (encdec_reg_backwards
            mapping99_)), (width_enc_backwards
          mapping100_), (← (encdec_reg_backwards
            mapping101_))) with
        | (aq, rl, rs2, rs1, width, rd) =>
          (do
            if (((← (currentlyEnabled
                     Ext_Zalrsc)) && (lrsc_width_valid
                   width)) : Bool)
            then
              (pure (some
                  (STORECON
                    (aq, rl, rs2, rs1, width, rd))))
            else
              (pure none)))
    else
      (pure none)) with
  | r => jp r

/-- Block 37 of `encdec_backwards`, passing its result to the continuation `jp`. -/
def _root_.FlapjackRiscvCheck.decodeBlock37 (jp : Option instruction → SailM instruction)
    (head_exp_ : BitVec 32) : SailM instruction := do
  match (← do
    let v__1492 :=
      head_exp_
    if (((let mapping105_ : (BitVec 5) :=
           (Sail.BitVec.extractLsb
             v__1492
             11
             7)
         let mapping104_ : (BitVec 3) :=
           (Sail.BitVec.extractLsb
             v__1492
             14
             12)
         let mapping103_ : (BitVec 5) :=
           (Sail.BitVec.extractLsb
             v__1492
             19
             15)
         let mapping102_ : (BitVec 5) :=
           (Sail.BitVec.extractLsb
             v__1492
             24
             20)
         ((encdec_reg_backwards_matches
             mapping102_) && ((encdec_reg_backwards_matches
               mapping103_) && ((encdec_mul_op_backwards_matches
                 mapping104_) && (encdec_reg_backwards_matches
                 mapping105_))))) && (((Sail.BitVec.extractLsb
               v__1492
               31
               25) == (0b0000001#7 : (BitVec 7))) && ((Sail.BitVec.extractLsb
               v__1492
               6
               0) == (0b0110011#7 : (BitVec 7))))) : Bool)
    then
      (do
        let mapping105_ : (BitVec 5) :=
          (Sail.BitVec.extractLsb
            v__1492
            11
            7)
        let mapping104_ : (BitVec 3) :=
          (Sail.BitVec.extractLsb
            v__1492
            14
            12)
        let mapping103_ : (BitVec 5) :=
          (Sail.BitVec.extractLsb
            v__1492
            19
            15)
        let mapping102_ : (BitVec 5) :=
          (Sail.BitVec.extractLsb
            v__1492
            24
            20)
        match ((← (encdec_reg_backwards
            mapping102_)), (← (encdec_reg_backwards
            mapping103_)), (← (encdec_mul_op_backwards
            mapping104_)), (← (encdec_reg_backwards
            mapping105_))) with
        | (rs2, rs1, mul_op, rd) =>
          (do
            if (((← (currentlyEnabled
                     Ext_M)) || (← (currentlyEnabled
                     Ext_Zmmul))) : Bool)
            then
              (pure (some
                  (MUL
                    (rs2, rs1, rd, mul_op))))
            else
              (pure none)))
    else
      (pure none)) with
  | r => jp r

/-- Block 38 of `encdec_backwards`, passing its result to the continuation `jp`. -/
def _root_.FlapjackRiscvCheck.decodeBlock38 (jp : Option instruction → SailM instruction)
    (head_exp_ : BitVec 32) : SailM instruction := do
  match (← do
    let v__1488 :=
      head_exp_
    if (((let mapping109_ : (BitVec 5) :=
           (Sail.BitVec.extractLsb
             v__1488
             11
             7)
         let mapping108_ : (BitVec 1) :=
           (Sail.BitVec.extractLsb
             v__1488
             12
             12)
         let mapping107_ : (BitVec 5) :=
           (Sail.BitVec.extractLsb
             v__1488
             19
             15)
         let mapping106_ : (BitVec 5) :=
           (Sail.BitVec.extractLsb
             v__1488
             24
             20)
         ((encdec_reg_backwards_matches
             mapping106_) && ((encdec_reg_backwards_matches
               mapping107_) && ((bool_bit_backwards_matches
                 mapping108_) && (encdec_reg_backwards_matches
                 mapping109_))))) && (((Sail.BitVec.extractLsb
               v__1488
               31
               25) == (0b0000001#7 : (BitVec 7))) && (((Sail.BitVec.extractLsb
                 v__1488
                 14
                 13) == (0b10#2 : (BitVec 2))) && ((Sail.BitVec.extractLsb
                 v__1488
                 6
                 0) == (0b0110011#7 : (BitVec 7)))))) : Bool)
    then
      (do
        let mapping109_ : (BitVec 5) :=
          (Sail.BitVec.extractLsb
            v__1488
            11
            7)
        let mapping108_ : (BitVec 1) :=
          (Sail.BitVec.extractLsb
            v__1488
            12
            12)
        let mapping107_ : (BitVec 5) :=
          (Sail.BitVec.extractLsb
            v__1488
            19
            15)
        let mapping106_ : (BitVec 5) :=
          (Sail.BitVec.extractLsb
            v__1488
            24
            20)
        match ((← (encdec_reg_backwards
            mapping106_)), (← (encdec_reg_backwards
            mapping107_)), (bool_bit_backwards
          mapping108_), (← (encdec_reg_backwards
            mapping109_))) with
        | (rs2, rs1, is_unsigned, rd) =>
          (do
            if ((← (currentlyEnabled
                   Ext_M)) : Bool)
            then
              (pure (some
                  (DIV
                    (rs2, rs1, rd, is_unsigned))))
            else
              (pure none)))
    else
      (pure none)) with
  | r => jp r

/-- Block 39 of `encdec_backwards`, passing its result to the continuation `jp`. -/
def _root_.FlapjackRiscvCheck.decodeBlock39 (jp : Option instruction → SailM instruction)
    (head_exp_ : BitVec 32) : SailM instruction := do
  match (← do
    let v__1484 :=
      head_exp_
    if (((let mapping113_ : (BitVec 5) :=
           (Sail.BitVec.extractLsb
             v__1484
             11
             7)
         let mapping112_ : (BitVec 1) :=
           (Sail.BitVec.extractLsb
             v__1484
             12
             12)
         let mapping111_ : (BitVec 5) :=
           (Sail.BitVec.extractLsb
             v__1484
             19
             15)
         let mapping110_ : (BitVec 5) :=
           (Sail.BitVec.extractLsb
             v__1484
             24
             20)
         ((encdec_reg_backwards_matches
             mapping110_) && ((encdec_reg_backwards_matches
               mapping111_) && ((bool_bit_backwards_matches
                 mapping112_) && (encdec_reg_backwards_matches
                 mapping113_))))) && (((Sail.BitVec.extractLsb
               v__1484
               31
               25) == (0b0000001#7 : (BitVec 7))) && (((Sail.BitVec.extractLsb
                 v__1484
                 14
                 13) == (0b11#2 : (BitVec 2))) && ((Sail.BitVec.extractLsb
                 v__1484
                 6
                 0) == (0b0110011#7 : (BitVec 7)))))) : Bool)
    then
      (do
        let mapping113_ : (BitVec 5) :=
          (Sail.BitVec.extractLsb
            v__1484
            11
            7)
        let mapping112_ : (BitVec 1) :=
          (Sail.BitVec.extractLsb
            v__1484
            12
            12)
        let mapping111_ : (BitVec 5) :=
          (Sail.BitVec.extractLsb
            v__1484
            19
            15)
        let mapping110_ : (BitVec 5) :=
          (Sail.BitVec.extractLsb
            v__1484
            24
            20)
        match ((← (encdec_reg_backwards
            mapping110_)), (← (encdec_reg_backwards
            mapping111_)), (bool_bit_backwards
          mapping112_), (← (encdec_reg_backwards
            mapping113_))) with
        | (rs2, rs1, is_unsigned, rd) =>
          (do
            if ((← (currentlyEnabled
                   Ext_M)) : Bool)
            then
              (pure (some
                  (REM
                    (rs2, rs1, rd, is_unsigned))))
            else
              (pure none)))
    else
      (pure none)) with
  | r => jp r

/-- Block 40 of `encdec_backwards`, passing its result to the continuation `jp`. -/
def _root_.FlapjackRiscvCheck.decodeBlock40 (jp : Option instruction → SailM instruction)
    (head_exp_ : BitVec 32) : SailM instruction := do
  match (← do
    let v__1480 :=
      head_exp_
    if (((let mapping116_ : (BitVec 5) :=
           (Sail.BitVec.extractLsb
             v__1480
             11
             7)
         let mapping115_ : (BitVec 5) :=
           (Sail.BitVec.extractLsb
             v__1480
             19
             15)
         let mapping114_ : (BitVec 5) :=
           (Sail.BitVec.extractLsb
             v__1480
             24
             20)
         ((encdec_reg_backwards_matches
             mapping114_) && ((encdec_reg_backwards_matches
               mapping115_) && (encdec_reg_backwards_matches
               mapping116_)))) && (((Sail.BitVec.extractLsb
               v__1480
               31
               25) == (0b0000001#7 : (BitVec 7))) && (((Sail.BitVec.extractLsb
                 v__1480
                 14
                 12) == (0b000#3 : (BitVec 3))) && ((Sail.BitVec.extractLsb
                 v__1480
                 6
                 0) == (0b0111011#7 : (BitVec 7)))))) : Bool)
    then
      (do
        let mapping116_ : (BitVec 5) :=
          (Sail.BitVec.extractLsb
            v__1480
            11
            7)
        let mapping115_ : (BitVec 5) :=
          (Sail.BitVec.extractLsb
            v__1480
            19
            15)
        let mapping114_ : (BitVec 5) :=
          (Sail.BitVec.extractLsb
            v__1480
            24
            20)
        match ((← (encdec_reg_backwards
            mapping114_)), (← (encdec_reg_backwards
            mapping115_)), (← (encdec_reg_backwards
            mapping116_))) with
        | (rs2, rs1, rd) =>
          (do
            if (((xlen == 64) && ((← (currentlyEnabled
                       Ext_M)) || (← (currentlyEnabled
                       Ext_Zmmul)))) : Bool)
            then
              (pure (some
                  (MULW
                    (rs2, rs1, rd))))
            else
              (pure none)))
    else
      (pure none)) with
  | r => jp r

/-- Block 41 of `encdec_backwards`, passing its result to the continuation `jp`. -/
def _root_.FlapjackRiscvCheck.decodeBlock41 (jp : Option instruction → SailM instruction)
    (head_exp_ : BitVec 32) : SailM instruction := do
  match (← do
    let v__1476 :=
      head_exp_
    if (((let mapping120_ : (BitVec 5) :=
           (Sail.BitVec.extractLsb
             v__1476
             11
             7)
         let mapping119_ : (BitVec 1) :=
           (Sail.BitVec.extractLsb
             v__1476
             12
             12)
         let mapping118_ : (BitVec 5) :=
           (Sail.BitVec.extractLsb
             v__1476
             19
             15)
         let mapping117_ : (BitVec 5) :=
           (Sail.BitVec.extractLsb
             v__1476
             24
             20)
         ((encdec_reg_backwards_matches
             mapping117_) && ((encdec_reg_backwards_matches
               mapping118_) && ((bool_bit_backwards_matches
                 mapping119_) && (encdec_reg_backwards_matches
                 mapping120_))))) && (((Sail.BitVec.extractLsb
               v__1476
               31
               25) == (0b0000001#7 : (BitVec 7))) && (((Sail.BitVec.extractLsb
                 v__1476
                 14
                 13) == (0b10#2 : (BitVec 2))) && ((Sail.BitVec.extractLsb
                 v__1476
                 6
                 0) == (0b0111011#7 : (BitVec 7)))))) : Bool)
    then
      (do
        let mapping120_ : (BitVec 5) :=
          (Sail.BitVec.extractLsb
            v__1476
            11
            7)
        let mapping119_ : (BitVec 1) :=
          (Sail.BitVec.extractLsb
            v__1476
            12
            12)
        let mapping118_ : (BitVec 5) :=
          (Sail.BitVec.extractLsb
            v__1476
            19
            15)
        let mapping117_ : (BitVec 5) :=
          (Sail.BitVec.extractLsb
            v__1476
            24
            20)
        match ((← (encdec_reg_backwards
            mapping117_)), (← (encdec_reg_backwards
            mapping118_)), (bool_bit_backwards
          mapping119_), (← (encdec_reg_backwards
            mapping120_))) with
        | (rs2, rs1, is_unsigned, rd) =>
          (do
            if (((xlen == 64) && (← (currentlyEnabled
                     Ext_M))) : Bool)
            then
              (pure (some
                  (DIVW
                    (rs2, rs1, rd, is_unsigned))))
            else
              (pure none)))
    else
      (pure none)) with
  | r => jp r

/-- The first blocks of `encdec_backwards`, continuing with `tail` when none match. -/
def _root_.FlapjackRiscvCheck.decodePrefix (tail : BitVec 32 → SailM instruction)
    (head_exp_ : BitVec 32) : SailM instruction :=
  FlapjackRiscvCheck.decodeBlock1 (fun r => match r with
    | .some result => pure result
    | none => FlapjackRiscvCheck.decodeBlock2 (fun r => match r with
    | .some result => pure result
    | none => FlapjackRiscvCheck.decodeBlock3 (fun r => match r with
    | .some result => pure result
    | none => FlapjackRiscvCheck.decodeBlock4 (fun r => match r with
    | .some result => pure result
    | none => FlapjackRiscvCheck.decodeBlock5 (fun r => match r with
    | .some result => pure result
    | none => FlapjackRiscvCheck.decodeBlock6 (fun r => match r with
    | .some result => pure result
    | none => FlapjackRiscvCheck.decodeBlock7 (fun r => match r with
    | .some result => pure result
    | none => FlapjackRiscvCheck.decodeBlock8 (fun r => match r with
    | .some result => pure result
    | none => FlapjackRiscvCheck.decodeBlock9 (fun r => match r with
    | .some result => pure result
    | none => FlapjackRiscvCheck.decodeBlock10 (fun r => match r with
    | .some result => pure result
    | none => FlapjackRiscvCheck.decodeBlock11 (fun r => match r with
    | .some result => pure result
    | none => FlapjackRiscvCheck.decodeBlock12 (fun r => match r with
    | .some result => pure result
    | none => FlapjackRiscvCheck.decodeBlock13 (fun r => match r with
    | .some result => pure result
    | none => FlapjackRiscvCheck.decodeBlock14 (fun r => match r with
    | .some result => pure result
    | none => FlapjackRiscvCheck.decodeBlock15 (fun r => match r with
    | .some result => pure result
    | none => FlapjackRiscvCheck.decodeBlock16 (fun r => match r with
    | .some result => pure result
    | none => FlapjackRiscvCheck.decodeBlock17 (fun r => match r with
    | .some result => pure result
    | none => FlapjackRiscvCheck.decodeBlock18 (fun r => match r with
    | .some result => pure result
    | none => FlapjackRiscvCheck.decodeBlock19 (fun r => match r with
    | .some result => pure result
    | none => FlapjackRiscvCheck.decodeBlock20 (fun r => match r with
    | .some result => pure result
    | none => FlapjackRiscvCheck.decodeBlock21 (fun r => match r with
    | .some result => pure result
    | none => FlapjackRiscvCheck.decodeBlock22 (fun r => match r with
    | .some result => pure result
    | none => FlapjackRiscvCheck.decodeBlock23 (fun r => match r with
    | .some result => pure result
    | none => FlapjackRiscvCheck.decodeBlock24 (fun r => match r with
    | .some result => pure result
    | none => FlapjackRiscvCheck.decodeBlock25 (fun r => match r with
    | .some result => pure result
    | none => FlapjackRiscvCheck.decodeBlock26 (fun r => match r with
    | .some result => pure result
    | none => FlapjackRiscvCheck.decodeBlock27 (fun r => match r with
    | .some result => pure result
    | none => FlapjackRiscvCheck.decodeBlock28 (fun r => match r with
    | .some result => pure result
    | none => FlapjackRiscvCheck.decodeBlock29 (fun r => match r with
    | .some result => pure result
    | none => FlapjackRiscvCheck.decodeBlock30 (fun r => match r with
    | .some result => pure result
    | none => FlapjackRiscvCheck.decodeBlock31 (fun r => match r with
    | .some result => pure result
    | none => FlapjackRiscvCheck.decodeBlock32 (fun r => match r with
    | .some result => pure result
    | none => FlapjackRiscvCheck.decodeBlock33 (fun r => match r with
    | .some result => pure result
    | none => FlapjackRiscvCheck.decodeBlock34 (fun r => match r with
    | .some result => pure result
    | none => FlapjackRiscvCheck.decodeBlock35 (fun r => match r with
    | .some result => pure result
    | none => FlapjackRiscvCheck.decodeBlock36 (fun r => match r with
    | .some result => pure result
    | none => FlapjackRiscvCheck.decodeBlock37 (fun r => match r with
    | .some result => pure result
    | none => FlapjackRiscvCheck.decodeBlock38 (fun r => match r with
    | .some result => pure result
    | none => FlapjackRiscvCheck.decodeBlock39 (fun r => match r with
    | .some result => pure result
    | none => FlapjackRiscvCheck.decodeBlock40 (fun r => match r with
    | .some result => pure result
    | none => FlapjackRiscvCheck.decodeBlock41 (fun r => match r with
    | .some result => pure result
    | none => tail head_exp_) head_exp_) head_exp_) head_exp_) head_exp_) head_exp_) head_exp_) head_exp_) head_exp_) head_exp_) head_exp_) head_exp_) head_exp_) head_exp_) head_exp_) head_exp_) head_exp_) head_exp_) head_exp_) head_exp_) head_exp_) head_exp_) head_exp_) head_exp_) head_exp_) head_exp_) head_exp_) head_exp_) head_exp_) head_exp_) head_exp_) head_exp_) head_exp_) head_exp_) head_exp_) head_exp_) head_exp_) head_exp_) head_exp_) head_exp_) head_exp_) head_exp_

end Functions
end LeanRV64D
end
